### ISSUE TITLE
Exposing service using Nginx Ingress Controller and load balancing (question)

### ISSUE THREAD

**Issue by pvsousalima** [kubeflow/kubeflow#1214]
Hey guys! First of all, thanks for this amazing project!

Well, I was just able to expose this service using the Nginx Ingress Controller and a previous LoadBalancer I had, this LoadBalancer also balances some other services in my cluster, and I have made a specific ingress configuration to deploy kubeflow to the world.

Can it be a contribution for the project? I struggled to find such information, since the actual documentation provides a way to create a dedicated LoadBalancer to expose it, which means more $.

Thanks!

**Comment by jlewi** [comment]
You were able to expose which service using the Nginx Ingress Controller?

Ambassador?

Can you explain in more detail, I'm not sure I follow.

**Comment by jlewi** [comment]
See kubeflow/kubeflow#11

I'm not sure that's the right thing to do. Kubeflow will consist of multiple webservices all of which sit behind a reverse proxy. The point of the reverse proxy is to give people a single service that they have to expose in order to easily access all Kubeflow services.

So if you wanted to make it easy to expose Ambassador using some other ingress controller/solution. That would make sense to me.

**Comment by pvsousalima** [comment]
Yes, that is what I was trying to do.

Well, I had issues with notebooks not connecting due to WebSocket proxy on ingress-nginx, so one ingress configuration made that possible to work in my case.

My ingress configuration is simple as this (with tf-hub being a NodePort type of service):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tf-tld-ingress
  namespace: kubeflow
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/websocket-services: "tf-hub-lb"
spec:
    rules:
      - host: domain.tld.com
        http:
          paths:
            - backend:
                  serviceName: tf-hub-lb
                  servicePort: 80
              path: "/"
```

I wonder if the right thing would be to create a configurable service pointing to Ambassador, so people would be able to configure their ingresses as they go.
