### ISSUE TITLE
presubmit build is failing with a quota error

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1562]
See this [build](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1535/kubeflow-presubmit/3366/)

The Error is:
```
ERROR: (gcloud.services.enable) RESOURCE_EXHAUSTED: Insufficient tokens for quota 'servicemanagement.googleapis.com/default_requests' and limit 'DefaultRequestsPe
rMinutePerProject' of service 'servicemanagement.googleapis.com' for consumer 'project_number:593963025935'.
```

**Comment by jlewi** [comment]
This is coming from project kubeflow-ci

```
gcloud projects describe 593963025935
createTime: '2018-02-09T23:13:03.601Z'
lifecycleState: ACTIVE
name: kubeflow-ci
parent:
 id: '714441643818'
 type: organization
projectId: kubeflow-ci
projectNumber: '593963025935'
```

Here's a graph of the enable service API 
![requests](https://user-images.githubusercontent.com/777219/45725768-2e763f00-bb71-11e8-9e36-4d3865ff9432.png)

We are definitely hitting the 120 requests per minute. Looks like the usage has increased since September 13.

I believe this is coming from our E2E tests calling kfctl.sh which enables APIs. 

The current quota limit is 120 requests per minute; can't increase it without applying for more quota.

An alternate fix would be to skip API enablement in our E2E tests.
