### ISSUE TITLE
Certificate not working

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1567]
I am seeing error in certificate: 
` ACME server does not allow selected challenge type or no provider is configured for domain `

certificate spec:
```
spec:
    acme:
      config:
      - domains:
        - kfdeploy10.endpoints.kai-test2.cloud.goog
        http01:
          ingress: envoy-ingress
```
issuer spec:
```
spec:
    acme:
      email: lunkai@google.com
      privateKeySecretRef:
        key: ""
        name: letsencrypt-prod-secret
      server: https://acme-v02.api.letsencrypt.org/directory
```
I am guessing the `http01: {}` got trimmed from issuer spec

**Comment by lluunn** [comment]
Result of doing ks show locally:
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  labels:
    ksonnet.io/component: vm
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    email: abc
    privateKeySecretRef:
      name: letsencrypt-prod-secret
    server: https://acme-v02.api.letsencrypt.org/directory
```

**Comment by lluunn** [comment]
Verified after I patched the issuer with `http01: `, the certificate works now.

Issuer spec:
```
spec:
    acme:
      email: lunkai@google.com
      http01: {}
      privateKeySecretRef:
        key: ""
        name: letsencrypt-prod-secret
      server: https://acme-v02.api.letsencrypt.org/directory
```
