### ISSUE TITLE
TFJob will not run if the TFJob CRD includes scope: Namespaced

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1606]
@jlewi There is a subtle issue in tf-job-operator

this works and results in tf-job-simple running
```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ksonnet.io/component: tf-job-operator
  name: tfjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: TFJob
    plural: tfjobs
    singular: tfjob
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            tfReplicaSpecs:
              properties:
                Chief:
                  properties:
                    replicas:
                      maximum: 1
                      minimum: 1
                      type: integer
                PS:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
                Worker:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
  version: v1alpha2
```
and this doesn't (difference is the inclusion of the scope attribute).
There are no errors that I can see and tf-job-simple never runs.

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ksonnet.io/component: tf-job-operator
  name: tfjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: TFJob
    plural: tfjobs
    singular: tfjob
  scope: cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            tfReplicaSpecs:
              properties:
                Chief:
                  properties:
                    replicas:
                      maximum: 1
                      minimum: 1
                      type: integer
                PS:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
                Worker:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
  version: v1alpha2
```

Since the default for CustomResourceDefinition scope is [Namespaced](https://godoc.org/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions) is seems like this would be a bug. I couldn't find in tf-operator repo where this is referenced.
