### ISSUE TITLE
Jupyterlab service account token

### ISSUE THREAD

**Issue by jamborta** [kubeflow/kubeflow#1648]
I am trying to start a k8s Spark cluster from Jupyter notebook using jupyterlab, but it fails because it cannot find a token to authenticate the cluster.

I think the reason for that is jupyter pods disable service account tokens in the pods (automountServiceAccountToken set to false). Any suggestion how to get around that limitation?

**Comment by jlewi** [comment]
Can you provide the pod spec of your Jupyter notebook?

Where are you seeing automountServiceAccount token set? When I look at my Jupyter pod I see a service token mounted

```
  terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/jovyan
      name: volume-jlewi-40google-2ecom
    - mountPath: /var/run/secrets/sa
      name: user-gcp-sa
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jupyter-notebook-token-x4pjc
      readOnly: true
```

Are you sure this isn't a role binding issue?
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/jupyterhub.libsonnet#L256

I think we provide limited permissions to the service account in the jupyter pod. So you might have insufficient permissions to create a spark cluster.
