### ISSUE TITLE
Provide an option to deploy an application-controller that will deploy the kubeflow application in-cluster

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1831]
The application-controller will watch one or more applications and claim ownership of the applications children
- [ ] Each child will have annotations and labels applied that is reference in the Application.Spec.Components
```yaml
    {
          annotations+: {
            "kubernetes.io/application": params.name,
          },
          labels+: {
            "app.kubernetes.io/name": params.name,
            "app.kubernetes.io/component": resource.metadata.name,
            app: params.name,
            component: resource.metadata.name,
    }
```
- [ ] Maintain [healthStatus](https://github.com/kow3ns/community/blob/8cb87419883197032f4e5cce8d5518c9c5792f6c/keps/sig-apps/0003-kubernetes-application-api.md#health-status-reporting)
- [ ] Maintain Status.[installed](https://github.com/kow3ns/community/blob/8cb87419883197032f4e5cce8d5518c9c5792f6c/keps/sig-apps/0003-kubernetes-application-api.md#api)
- [ ] Increment Status.[ObservedGeneration](https://github.com/kow3ns/community/blob/8cb87419883197032f4e5cce8d5518c9c5792f6c/keps/sig-apps/0003-kubernetes-application-api.md#generation-observation) per update
- [ ] Reparenting of the children will be made to point to the controller
- [ ] Deletion of child components will occur if the application is deleted
