### ISSUE TITLE
Job not stopping once chief is complete - v0.2.0-rc.1

### ISSUE THREAD

**Issue by matthen** [kubeflow/kubeflow#1853]
I'm using `v0.2.0-rc.1`. I would like my TFJobs to finish when the chief exits successfully, but currently the workers, ps and evaluators pods stay running, and the chief stays up with a "Succeeded" state and a "Completed" pod.

below is my yaml spec (running on GKE):

```
apiVersion: "kubeflow.org/v1alpha2"
kind: "TFJob"
metadata:
  name: {{JOB_NAME}}
spec:
  tfReplicaSpecs:

    Chief:
      replicas: 1
      template:
        spec:
          containers:
            - image: {{IMAGE}}
              name: tensorflow
              command: ["/bin/bash", "-c"]
              args: ["./train_model.pex --task CHIEF {{TRAIN_MODEL_ARGS}}"]
              env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/auth/storage-credentials.json"
              volumeMounts:
              - name: storage-credentials
                mountPath: /auth
                readOnly: true
              resources:
                requests:
                  cpu: 1000m
                  memory: {{MASTER_MEMORY}}
          volumes:
          - name: storage-credentials
            secret:
              secretName: storage-auth-credentials
              items:
                - key: credentials
                  path: storage-credentials.json
          restartPolicy: OnFailure

    Worker:
      replicas: {{NUM_WORKERS}}
      template:
        spec:
          containers:
            - image: {{IMAGE}}
              name: tensorflow
              command: ["/bin/bash", "-c"]
              args: ["./train_model.pex --task WORKER {{TRAIN_MODEL_ARGS}}"]
              env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/auth/storage-credentials.json"
              volumeMounts:
              - name: storage-credentials
                mountPath: /auth
                readOnly: true
              resources:
                requests:
                  cpu: 1000m
                  memory: {{MEMORY}}
          volumes:
          - name: storage-credentials
            secret:
              secretName: storage-auth-credentials
              items:
                - key: credentials
                  path: storage-credentials.json
          restartPolicy: OnFailure


    Evaluator:
      replicas: {{NUM_EVALUATORS}}
      template:
        spec:
          containers:
            - image: {{IMAGE}}
              name: tensorflow
              command: ["/bin/bash", "-c"]
              args: ["./train_model.pex --task EVALUATOR {{TRAIN_MODEL_ARGS}}"]
              env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/auth/storage-credentials.json"
              volumeMounts:
              - name: storage-credentials
                mountPath: /auth
                readOnly: true
              resources:
                requests:
                  memory: {{MEMORY}}
          volumes:
          - name: storage-credentials
            secret:
              secretName: storage-auth-credentials
              items:
                - key: credentials
                  path: storage-credentials.json
          restartPolicy: OnFailure

    Ps:
      replicas: {{NUM_PS}}
      template:
        spec:
          containers:
            - image: {{IMAGE}}
              name: tensorflow
              command: ["/bin/bash", "-c"]
              args: ["./train_model.pex --task PS {{TRAIN_MODEL_ARGS}}"]
              resources:
                requests:
                  memory: {{MEMORY}}
          restartPolicy: Always
```

Is there something I need to add to get the pods to be deleted when the chief is complete?
