### ISSUE TITLE
Which jubyterhub disks param name to use when assigning GCFS as PV

### ISSUE THREAD

**Issue by IMBurbank** [kubeflow/kubeflow#1934]
This is related to issues I laid out in #1912 

I've read everything I can find in docs [[1](https://www.kubeflow.org/docs/started/getting-started-gke/ 'Kubernetes Engine for Kubeflow')] [[2](https://www.kubeflow.org/docs/guides/gke/troubleshooting-gke/ 'Troubleshooting Deployments on GKE')] [[3](https://www.kubeflow.org/docs/guides/gke/cloud-filestore/ 'Using Cloud Filestore')] [[4](https://www.kubeflow.org/docs/guides/gke/customizing-gke/ 'Advanced Customizations')], open issues and closed issues about assigning a GCP GCFS as a volume mount for jupyter. 

I think my issue stems from Kubeflow deploying the GCFS using the Deployment Manager, but not assigning it as a PV, when following [the instructions](https://www.kubeflow.org/docs/guides/gke/cloud-filestore/ 'Using Cloud Filestore'). This results in the GCFS not being found when the jupyterhub server is spawned.

As I continue to trouble-shoot why following the quick-start instructions exactly results in an error mounting the PV to jupyter when spawning a server - it would be helpful to know what the `name` parameter in `ks param set jupyterhub disks <name>` is supposed to represent. If i can limit my debugging to the intended name, I should be able to resolve this much faster.

The most likely candidate seems to be the `instance name`, but this didn't work for me - and the note for instance name in `gcfs.yaml` make the choice of name seem unimportant.

`gcfs.yaml`
```yaml

# Modify this instance to create a GCFS file store.
# 1. Change the zone to the desired zone
# 2. Change the instanceId to the desired id
# 3. Change network if needed 
# 4. Change the capacity if desired.
resources:
- name: filestore
  type: gcp-types/file-v1beta1:projects.locations.instances
  properties:
    parent: projects/isolated-project/locations/us-west1-b
    # Any name of the instance would do
    instanceId: YOUR_DEPLOYMENT_NAME
    tier: STANDARD
    description: Filestore for Kubeflow
    networks:
    - network: default
    fileShares:
    - name: kubeflow
      capacityGb: 1024
```

The next candidate would be the `fileShares` name `kubeflow`, but no examples use this as the `jupyter disks` param - and it also didn't work.

The last candidate is the name of the deployment itself, which it assigned the name `${DEPLOYMENT_NAME}-gcfs`. It is appended with '-gcfs' as are the param names given in examples, but this didn't work for me either.

Help on the greater issue would be appreciated, but at this point I would be happy to know the designer's intent for this parameter.
