### ISSUE TITLE
Can TFJob be parameterized by replica index

### ISSUE THREAD

**Issue by sdeoras** [kubeflow/kubeflow#1943]
Hi Folks, I am trying to understand if TFJob can be parameterized using replica index. My use case is that each worker would use a different PVC. Is it possible to do so? Thanks.

**Comment by sdeoras** [comment]
I was able to assign different pvc's parameterized by replica index using labels as follows. If we think this is the approach in the right direction I am happy to work on a PR.

```
apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  creationTimestamp: null
  name: tf-job
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 3
      template:
        metadata:
          labels:
            app: tf-app
            parameterize-pvc-by-replica-index: tf-pvc
...
```

It results in three pods, using PVC's tf-pvc-0, tf-pvc-1 and tf-pvc-2 respectively. Thanks.
