### ISSUE TITLE
Error persistentvolumeclaim "nfs" not found while host model from NFS

### ISSUE THREAD

**Issue by zxsimple** [kubeflow/kubeflow#1964]
Follow [Serve a local model using Tensorflow Serving](https://github.com/kubeflow/kubeflow/blob/a8c0dda2f2d90bae67497652211cc6224c8f73cd/components/k8s-model-server/Serve%20a%20local%20model%20using%20Tensorflow%20Serving.md#serve-a-local-model-using-tensorflow-serving) to host inception model from NFS I got _persistentvolumeclaim "nfs" not found_ Error.

`kubectl get pv`
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                  STORAGECLASS   REASON    AGE
nfs                                        1Mi        RWX            Retain           Bound     default/nfs                                     2m
```

`kubectl get pvc`
```
NAME      STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nfs       Bound     nfs       1Mi        RWX                           6m
```

Note the `tf-serving` component is created under `kubeflow` namespace

**Comment by zxsimple** [comment]
Fixed by adding `namespace` and `storageClassName`.
- pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: NFS_SERVER_IP
    path: ""
```
- pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi
```
