### ISSUE TITLE
Replace ambassador with Istio

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2261]
We are moving toward Istio.
> Current architecture:
> 
> ```
> Ingress -->        Envoy        --> Ambassador --> Other services
>               (JWT valdation)
> ```
> The plan is to use istio-ingressgateway for both JWT validation and routing, and thus:
> 
> ```
> Ingress  --> istio-ingressgateway --> Other services
> ```

There are several tasks needed:

1. Ingress:
Ingress and the NodePort service right behind it must be in the same namespace (https://github.com/kubernetes/kubernetes/issues/17088). I think it's easier to move ingress to istio-system (comparing to moving istio stuffs to kubeflow namespace) because Istio manifest assumes the namespace is istio-system in many places.
- [ ] move ingress and related resources (BackendConfig, oauth secret etc) to istio-namespace

2. Routing
- [ ] For services that are routed by ambassador, remove the annotation and add Istio routes.

3. JWT validation
- [ ] migrate the current envoy config to istio-ingressgateway
- [ ] We need a job/deployment to get the backendService ID for JWT audience, and apply the Policy.

Example policy:
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ingress-jwt
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
    ports:
    - number: 80
  origins:
  - jwt:
      issuer: https://cloud.google.com/iap
      jwksUri: https://www.gstatic.com/iap/verify/public_key-jwk
      audiences:
      - /projects/711890160434/global/backendServices/8282354174894887635
      jwtHeaders:
      - x-goog-iap-jwt-assertion
      trigger_rules:
      - excluded_paths: 
        - exact: /healthz
  principalBinding: USE_ORIGIN
```

cc @kunmingg @jlewi
