### ISSUE TITLE
Ambassador routes for new jupyter notebooks don't work

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2590]
Here's the service definition

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: notebook_kf-jlewi_jlewi-1_mapping
      prefix: /notebook/kf-jlewi/jlewi-1
      rewrite: /kf-jlewi/jlewi-1
      timeout_ms: 300000
      service: jlewi-1.kf-jlewi:8888
      use_websocket: true

```

When I navigate to:

```
https://jlewi-0228.endpoints.cloud-ml-dev.cloud.goog/notebook/kf-jlewi/jlewi-1/
```

I get upstream connect error.

Is it supposed to be rewriting it to `/kf-jlewi/jlewi-1`

/cc @kimwnasptd @lluunn
