### ISSUE TITLE
kfctl could not generate kfApp no hostname

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2670]
I tried running kfctl using `v0.4.0-rc.1-204-g6fa88b7c` 

I get the following error

```
ERRO[0005] couldn't generate KfApp: coordinator Generate failed for none: Failed to set param basic-auth-ingress hostname : value is invalid: value was blank 
```

Here is the contents of app.yaml.

So it looks like hostname is set.

```
kind: Gcp
metadata:
  creationTimestamp: null
  name: jlewi-basic-0308
  namespace: kubeflow
spec:
  appdir: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-basic-0308
  email: jlewi@google.com
  hostname: jlewi-basic-0308.endpoints.cloud-ml-dev.cloud.goog
  ipName: jlewi-basic-0308-ip
  platform: gcp
  project: cloud-ml-dev
  repo: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-basic-0308/.cache/master/kubeflow
  skipInitProject: true
  useBasicAuth: true
  version: master
  zone: us-east1-d
```
