### ISSUE TITLE
kfctl creates invalid IAM policy binding file if email not set

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2707]
I didn't set `-email` when calling `kfctl init`. 

As a result I ended up with the following iam policy binding YAML file.

This turns out to generate an error when trying to apply it because we are missing an email for the user 

```
- members:
  - user:
  roles:
  - roles/iap.httpsResourceAccessor
```

Full YAML

```
bindings:
- members:
  - serviceAccount:kfctl-2220-76b7-admin@kubeflow-ci-deployment.iam.gserviceaccount.com
  roles:
  # Grant permissions needed to push the app to a cloud repository
  - roles/source.admin
  # servicemanagement.admin is needed by CloudEndpoints controller so we can create a service to get a hostname.
  - roles/servicemanagement.admin
  # Network admin is needed to enable IAP and configure network settings like backend timeouts and health checks
  - roles/compute.networkAdmin
- members:
  - serviceAccount:kfctl-2220-76b7-user@kubeflow-ci-deployment.iam.gserviceaccount.com
  roles:
  # Grant permissions needed to submit builds to Google Cloud Container Builder
  - roles/cloudbuild.builds.editor
  # roles/viewer is required for viewing the logs of a GCB build
  - roles/viewer
  # Grant permissions needed to push the app to a cloud repository
  - roles/source.admin
  - roles/storage.admin
  - roles/bigquery.admin
  - roles/dataflow.admin
  - roles/ml.admin
  - roles/dataproc.editor
  - roles/cloudsql.admin
- members:
  - serviceAccount:kfctl-2220-76b7-vm@kubeflow-ci-deployment.iam.gserviceaccount.com
  roles:
  # VM service account is used to write logs
  - roles/logging.logWriter
  # VM service account is used to write monitoring data
  - roles/monitoring.metricWriter
  # VM service account is used to pull image from gcr
  - roles/storage.objectViewer
- members:
  - user:
  roles:
  - roles/iap.httpsResourceAccessor

```

/cc @gabrielwen
