### ISSUE TITLE
ipName and zone are being written to app.yaml even when no platform is specified

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2773]
steps to reproduce
1. kfctl init ~/kubeflow
2. cd ~/kubeflow
3. kfctl generate all

app.yaml

```
apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kubeflow
  namespace: kubeflow
spec:
  appdir: /Users/kdkasrav/kubeflow
  componentParams:
    ambassador:
    - name: ambassadorServiceType
      value: NodePort
    application:
    - name: components
      value: '["ambassador" ,"argo" ,"centraldashboard" ,"jupyter" ,"jupyter-web-app"
        ,"katib" ,"notebook-controller" ,"pipeline" ,"profiles" ,"pytorch-operator"
        ,"tensorboard" ,"tf-job-operator"]'
    jupyter:
    - name: platform
      value: none
  components:
  - ambassador
  - application
  - argo
  - centraldashboard
  - jupyter
  - jupyter-web-app
  - katib
  - metacontroller
  - notebook-controller
  - pipeline
  - profiles
  - pytorch-operator
  - tensorboard
  - tf-job-operator
  ipName: kubeflow-ip
  packages:
  - argo
  - application
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pipeline
  - profiles
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  repo: /Users/kdkasrav/kubeflow/.cache/master/kubeflow
  useBasicAuth: false
  useIstio: false
  version: master
  zone: us-east1-d
status: {}
```
