### ISSUE TITLE
Launching TFJOB with GPU request does not autoscale the gpu-pool

### ISSUE THREAD

**Issue by Svendegroote91** [kubeflow/kubeflow#2789]
Hi all,

When I deploy Kubeflow on GKE via the bash script procedure, I tweak the permission params in the cluster.jinja and iam_bindings.yaml so the kubeflow vm service account has extra permissions than the default and the nodes have cloud-platform scopes.

I also adjust the cluster-kubeflow.yaml on gpu-pool-max-nodes: 1 because I want to run a TFJob with a GPU.

When the kubeflow script is ran, I can see the gpu-pool in the cluster with 0 nodes.

When I launch the TFJob, I would expect the gpu-pool to scale but instead another pool (nap-n1-standard-1-gpu-..) gets provisioned with the default compute service account, and as a result my TFJob fails because that default service account does not have the necessary permissions (as the permissions granted on the kubeflow vm service account).

![image](https://user-images.githubusercontent.com/33965133/54870488-73409400-4da7-11e9-8d6d-6975d6142b71.png)

Can anyone tell me why this deployment is triggering another provisioning and how this mechanism works? Any suggestions on how I can point my TFJob to the gpu-pool? Explicitly mentioning nodeselector in my jsonnet/yaml file also does not solve the problem as it does not trigger the gpu-pool to scale.

I'm using Kubeflow v0.4.1 here. The scenario above used to work with the Kubeflow v0.3.1.

The yaml file that is deployed is the following:
```
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  labels:
    ksonnet.io/component: train
  name: trainingjobgpu
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - python
            - run_preprocess_and_train.py
            - --model=DeepModel
            - --epochs=30001
            - --bucket=kf-finance
            - --version=3
            image: gcr.io/sven-sandbox/kubeflow/gpu:v2
            name: tensorflow
            resources:
              limits:
                nvidia.com/gpu: 1
            workingDir: /opt/workdir
          restartPolicy: OnFailure

```
