### ISSUE TITLE
kfctl attribute deleteStorage is appearing in app.yaml when platform is not gcp

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2826]
steps to reproduce

1 run `kfctl init kubeflow`

The files looks like

```
apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kubeflow
  namespace: kubeflow
spec:
  appdir: /Users/kdkasrav/kubeflow
  componentParams:
    ambassador:
    - name: ambassadorServiceType
      value: NodePort
    application:
    - name: components
      value: <list-of-components>
  components:
  - ambassador
  - application
  - argo
  - centraldashboard
  - jupyter-web-app
  - katib
  - metacontroller
  - notebook-controller
  - pipeline
  - profiles
  - pytorch-operator
  - tensorboard
  - tf-job-operator
  deleteStorage: false
  packages:
  - argo
  - application
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pipeline
  - profiles
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  repo: /Users/kdkasrav/kubeflow/.cache/master/kubeflow
  useBasicAuth: false
  useIstio: false
  version: master
status: {}
```

The deleteStorage attribute appears even though no platform was specified
