### ISSUE TITLE
TFJob does not show in TFJob dashboard

### ISSUE THREAD

**Issue by Svendegroote91** [kubeflow/kubeflow#2886]
Hi all,

When submitting several TFjobs, I don't see them appearing any longer in the `tfjobs/ui/#/` UI page. Not in the 'all namespaces' and also not in the 'kubeflow' namespace.

I am using kubeflow v0.4.0.
Here is one example of a TFjob:

```
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  labels:
    ksonnet.io/component: train
  name: trainingjobgpu
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - python
            - run_preprocess_and_train.py
            - --model=DeepModel
            - --epochs=30001
            - --bucket=kf-finance
            - --version=3
            image: gcr.io/sven-sandbox/kubeflow/gpu:v3
            name: tensorflow
            resources:
              limits:
                nvidia.com/gpu: 1
            workingDir: /opt/workdir
          restartPolicy: OnFailure

```

Can anyone tell me what's going wrong here?
