### ISSUE TITLE
admission webhook overwrites NB_PREFIX env var

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2896]
The admission webhook successfully inject the volume/env var, but it seems overwrites env var instead of appends to it.
```
env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secrets/gcp-service-account-credentials/user-gcp-sa.json
image: ...
```

So the notebook is not working properly 404:
<img width="362" alt="Screen Shot 2019-04-01 at 15 45 15" src="https://user-images.githubusercontent.com/32310205/55364345-29d20200-5495-11e9-9ea4-ca3fe9334254.png">

**Comment by lluunn** [comment]
cc @abhi-g @r2d4

**Comment by lluunn** [comment]
https://github.com/kubeflow/kubeflow/blob/master/components/gcp-admission-webhook/main.go#L51-L53

This is our patch string

**Comment by lluunn** [comment]
volume is fine:
```
volumes:
  - name: volume-test2
    persistentVolumeClaim:
      claimName: test2
  - name: default-token-xw5gd
    secret:
      defaultMode: 420
      secretName: default-token-xw5gd
  - name: gcp-credentials
    secret:
      defaultMode: 420
      secretName: user-gcp-sa
```

Seems I should remove "[" and "]" in patch string above
