### ISSUE TITLE
How can I access own service deployed in kubeflow via ambassador?

### ISSUE THREAD

**Issue by tjhgit** [kubeflow/kubeflow#2975]
Here is my service definition:
```
apiVersion: v1
kind: Service
metadata:
  name: ml-backend-api
  annotations:
    getambassador.io/config: |

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: ml-backend-api-post
      prefix: /api/upload/
      rewrite: /api/upload/:upload
      method: POST
      service: ml-backend-api.kubeflow:8080
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: ml-backend-api-get
      prefix: /api/results/
      rewrite: /api/results/:results
      method: GET
      service: ml-backend-api.kubeflow:8080
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    type: api
    service: ml-backend
```
How can I access now this service from outside?
