### ISSUE TITLE
Notebook Spawner should check for edit permissions before spawning the notebook

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2981]
When talking to k8s API, Notebook Spawner backend should 
* read user id from jwt 
* impersonate as k8s user account
* k8s master then block or proceed based on rbac rule of k8s user account

**Comment by yanniszark** [comment]
Following from [PR#3234](https://github.com/kubeflow/kubeflow/pull/3234), I think we should discuss how the userid will be inferred from the JWT.
The current implementation uses a google-specific header to get the userid, making it not work for other platforms.
I can think of two solutions for this:

1. Add a flag in each operator interacting with those headers (profile controller, notebook spawner doing impersonation etc), denoting which header it should use to read the userid. We should also add an option to infer it from the claims of the JWT.
2. Rewrite the platform-specific header or appropriate claim onto a new pre-agreed-upon header (like `x-kubeflow-authenticated-user-email`) using Istio Rules.

I have tried the 2nd option with this Rule and it works:
```yaml
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: google-header-rewrite
  namespace: istio-system
spec:
  match: source.labels["istio"] == "ingressgateway"
  requestHeaderOperations:
  - name: kubeflow-authenticated-user-email
    values:
      - request.headers["x-goog-authenticated-user-email"]
```

In addition, we should also be able to reference jwt claims, [as others have been able to](https://discuss.istio.io/t/question-decode-jwt-and-put-sub-into-a-request-header/1213/8?u=yanniszark).

**Comment by jlewi** [comment]
@yanniszark Any update on the current plan based on our April 12 meeting? Unfortunately, the update @vkoukis posted into slack is no longer accessible.

IIRC correctly I think the plan is

* Each name space will have some service accounts with read or write permissions
* Web app will use that service account to create resources
* We discussed creating some sort of lookup service to map users to namespace.

Does the access management API provide the necessary functionality?
https://github.com/kubeflow/kubeflow/tree/master/components/access-management

**Comment by jlewi** [comment]
Actually  here are @vkoukis notes
https://groups.google.com/forum/#!msg/kubeflow-discuss/Yu9DtqexIi4/ZPEc-NNGDAAJ

**Comment by kunmingg** [comment]
access management API  can answer:
if user A can access namespace B.
So Notebook Spawner backend can behave like:
For each coming request:
1. parse user identity from header (provide by IAP or basic auth or LDAP)
2. query [access management API ](https://github.com/kubeflow/kubeflow/tree/master/components/access-management) to check if this user can access target namespace.
3. proceed or block.

We can start with IAP case?

**Comment by kunmingg** [comment]
Impersonate or query access management API will both block unauthorized requests, 
we can choose an easier option.

**Comment by jlewi** [comment]
Not sure this is really P0. 

@kunmingg  What is this blocking?

**Comment by kimwnasptd** [comment]
@jlewi I think this isn't blocking something, but is needed for multi user jupyter. We need to move away from having the webapp use a privileged ServiceAccount in order to have a multi user experience.

Although it might make sense to not have this included in the 0.6, since its really close, and add it in a following 0.6.X version.

Regarding the implementation, the changes I am thinking to make are:
1. When the webapp receives a request it checks the `userid-{header, prefix}` headers (which will be parameterizable) and:
	* If it finds them, then it will make any necessary k8s API calls by impersonating this user
	* if it doesn't find these headers, then it will make the calls by impersonating the anonymous user
2. Create a `Role/RoleBinding` in the manifests to give the webapp permission to impersonate any user:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyter-webapp-impersonator
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
```

The second part has some security considerations since another app inside the cluster could make a direct request and set the userid header to `admin/any user`. But it would be a first step and we could then iterate on that.

Then, as a next step, we could give permissions in the role to impersonate specific users and not all. We could keep the list of impersonate-able users in sync with `kfam`'s Bindings. When we create a new Binding with `kfam` to give `edit` permissions to a user we could also patch the list in the `Role` to add that user. And vice versa when we delete a Binding.

@jlewi @kunmingg WDYT?
