### ISSUE TITLE
[Suggestion] Centraldashboard Service as LoadBalancer 

### ISSUE THREAD

**Issue by spaghettifunk** [kubeflow/kubeflow#3085]
I was wondering if it was possible to deploy the Centraldashboard with `service type` as `LoadBalancer` instead of `ClusterIP`. I think it would be useful for those people that are not familiar with `kubectl` command line.

I tried to remove the current `svc/centraldashboard` and convert it to `LoadBalancer` as below

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: centralui-mapping
      prefix: /
      rewrite: /
      service: centraldashboard.kubeflow
  labels:
    app: centraldashboard
    app.kubernetes.io/name: eks-kubeflow
    ksonnet.io/component: application
  name: centraldashboard
  namespace: kubeflow
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: centraldashboard
  sessionAffinity: None
  type: LoadBalancer
```

but when I access the UI the redirect to the various pages doesn't work properly. Maybe there is a redirection problem. 
Anyway, this is just a suggestion :)
