### ISSUE TITLE
tfjob container name is in use

### ISSUE THREAD

**Issue by lcax200000** [kubeflow/kubeflow#3220]
### i have get  "container name  is already in use "  error often times when create tfjobs

* **[root@k8s-m1 mnist]# _cat dst.yaml_** 

       apiVersion: kubeflow.org/v1beta1
        kind: TFJob
        metadata:
          name: train2
        spec:
          tfReplicaSpecs:
            PS:
              replicas: 1
              restartPolicy: Never
              template:
                spec:
                  containers:
                  - command:
                    - python
                    - /app/tf-example.py
                    env:
                    - name: TEST_TMPDIR
                      value: /app/mnist-data
                    image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
                    imagePullPolicy: IfNotPresent
                    name: tensorflow
                    volumeMounts:
                    - mountPath: /app
                      name: kubeflow-nfs
                    resources:
                      limits:
                        nvidia.com/gpu: 1
                  restartPolicy: OnFailure
                  volumes:
                  - name: kubeflow-nfs
                    nfs:
                      path: /share/mnist/mnist-data
                      server: 10.101.98.7
            Worker:
              replicas: 1
              restartPolicy: Never
              template:
                spec:
                  containers:
                  - command:
                    - python
                    - /app/tf-example.py
                    env:
                    - name: TEST_TMPDIR
                      value: /app/mnist-data
                    image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
                    imagePullPolicy: IfNotPresent
                    name: tensorflow
                    resources:
                      limits:
                        nvidia.com/gpu: 1
                    volumeMounts:
                    - mountPath: /app
                      name: kubeflow-nfs
                  restartPolicy: OnFailure
                  volumes:
                  - name: kubeflow-nfs
                    nfs:
                      path: /share/mnist/mnist-data
                      server: 10.101.98.7

* **_[root@k8s-m1 mnist]# kubectl create -f dst.yaml_** 

        tfjob.kubeflow.org/train2 created
* **_[root@k8s-m1 mnist]# kubectl get tfjobs_**

        NAME     STATE     AGE
        train2   Created   6s

![image](https://user-images.githubusercontent.com/9493082/57359386-2de6f300-71aa-11e9-8b1f-f60419398e14.png)

* **_[root@k8s-m1 mnist]# kubectl describe po  train2-worker-0_**

        Name:               train2-worker-0
        Namespace:          default
        Priority:           0
        PriorityClassName:  <none>
        Node:               12025414/11.226.240.18
        Start Time:         Wed, 08 May 2019 15:56:03 +0800
        Labels:             group-name=kubeflow.org
                            tf-job-name=train2
                            tf-job-role=master
                            tf-replica-index=0
                            tf-replica-type=worker
        Annotations:        <none>
        Status:             Failed
        IP:                 10.244.6.207
        Controlled By:      TFJob/train2
        Containers:
          tensorflow:
            Container ID:  docker://96150ddc43ee39e91d60c9702d7cb681c85aeefa5074e617c8b3ee015702f406
            Image:         gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
            Image ID:      docker://sha256:75d23c5409097c53495a6a0888e4f2fd8ba0c61a501781777c1e0e8f46ff62ea
            Port:          2222/TCP
            Host Port:     0/TCP
            Command:
              python
              /app/tf-example.py
            State:          Waiting
              Reason:       CreateContainerError
            Last State:     Terminated
              Exit Code:    0
              Started:      Mon, 01 Jan 0001 00:00:00 +0000
              Finished:     Mon, 01 Jan 0001 00:00:00 +0000
            Ready:          False
            Restart Count:  0
            Limits:
              nvidia.com/gpu:  1
            Requests:
              nvidia.com/gpu:  1
            Environment:
              TEST_TMPDIR:  /app/mnist-data
              TF_CONFIG:    {"cluster":{"ps":["train2-ps-0.default.svc:2222"],"worker":["train2-worker-0.default.svc:2222"]},"task":{"type":"worker","index":0},"environment":"cloud"}
            Mounts:
              /app from kubeflow-nfs (rw)
              /var/run/secrets/kubernetes.io/serviceaccount from default-token-q5fnp (ro)
        Conditions:
          Type              Status
          Initialized       True 
          Ready             False 
          ContainersReady   False 
          PodScheduled      True 
        Volumes:
          kubeflow-nfs:
            Type:      NFS (an NFS mount that lasts the lifetime of a pod)
            Server:    10.101.98.7
            Path:      /share/mnist/mnist-data
            ReadOnly:  false
          default-token-q5fnp:
            Type:        Secret (a volume populated by a Secret)
            SecretName:  default-token-q5fnp
            Optional:    false
        QoS Class:       BestEffort
        Node-Selectors:  <none>
        Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                         node.kubernetes.io/unreachable:NoExecute for 300s
        Events:
          Type     Reason     Age                 From               Message
          ----     ------     ----                ----               -------
          Normal   Scheduled  3m6s                default-scheduler  Successfully assigned default/train2-worker-0 to 12025414
          Warning  Failed     66s                 kubelet, 12025414  Error: context deadline exceeded
          Normal   Pulled     38s (x4 over 3m6s)  kubelet, 12025414  Container image "gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1" already present on machine
          Warning  Failed     38s (x3 over 66s)   kubelet, 12025414  Error: Error response from daemon: Conflict. The container name "/k8s_tensorflow_train2-worker-0_default_ba751528-7166-11e9-b5bd-001fe241766d_0" is already in use by container "96150ddc43ee39e91d60c9702d7cb681c85aeefa5074e617c8b3ee015702f406". You have to remove (or rename) that container to be able to reuse that name.

**Comment by yylin1** [comment]
Can you rearrange the formatting in the question. (follow Markdown)

```
$ cat dst.yaml
...
```

**Comment by jlewi** [comment]
Which version of K8s are you using? And are you using a hosted version of K8s?

It seems to me like there is something going on with the kubelet and not the TFJob controller. 
It looks like the kubelet is having trouble starting the container and not cleaning up the failed container properly before starting it.

To confirm this you might try creating a Deployment or Pod with the same spec and not using TFJob.

You might also want to try removing GPUs and seeing if that works.

**Comment by lcax200000** [comment]
> Which version of K8s are you using? And are you using a hosted version of K8s?
> 
> It seems to me like there is something going on with the kubelet and not the TFJob controller.
> It looks like the kubelet is having trouble starting the container and not cleaning up the failed container properly before starting it.
> 
> To confirm this you might try creating a Deployment or Pod with the same spec and not using TFJob.
> 
> You might also want to try removing GPUs and seeing if that works.

I used kubeadm to deploy version 1.14.0 of k8s on my own two machines(ubuntu 16.04,  kubeflow 0.5.0).

**Comment by yylin1** [comment]
@lcax200000 
Do you try to run the kubeflow gpu example?  or run some gpu-pod test your environment.

**Comment by lcax200000** [comment]
@yylin1
yes , I have successfully run this example code many times before
https://github.com/cheyang/tensorflow-sample-code/blob/master/tfjob/docker/distributed-mnist/main.py?spm=a2c4e.11153940.blogcont602109.18.3a2b5325jvCOzF&file=main.py

**Comment by lcax200000** [comment]
> @lcax200000
> Do you try to run the kubeflow gpu example? or run some gpu-pod test your environment.

yes , I have successfully run this example code many times before
https://github.com/cheyang/tensorflow-sample-code/blob/master/tfjob/docker/distributed-mnist/main.py?spm=a2c4e.11153940.blogcont602109.18.3a2b5325jvCOzF&file=main.py

images: gcr.io/kubeflow-images-public/tensorflow-1.10.0-notebook-gpu:v0.3.0

**Comment by lcax200000** [comment]
> spec

@yylin1 

i'm create tfjob with this yaml:
```

apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: train2
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - command:
            - python
            - /app/tf-example.py
            env:
            - name: TEST_TMPDIR
              value: /app/mnist-data
            image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
            imagePullPolicy: IfNotPresent
            name: tensorflow
            volumeMounts:
            - mountPath: /app
              name: kubeflow-nfs
            resources:
              limits:
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
          volumes:
          - name: kubeflow-nfs
            nfs:
              path: /share/mnist/mnist-data
              server: 10.11.98.77
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - command:
            - python
            - /app/tf-example.py
            env:
            - name: TEST_TMPDIR
              value: /app/mnist-data
            image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
            imagePullPolicy: IfNotPresent
            name: tensorflow
            resources:
              limits:
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /app
              name: kubeflow-nfs
          restartPolicy: OnFailure
          volumes:
          - name: kubeflow-nfs
            nfs:
              path: /share/mnist/mnist-data
              server: 10.11.98.77
```

get error： 

![image](https://user-images.githubusercontent.com/9493082/57593149-c267a180-756c-11e9-813b-c53d79decb89.png)


![image](https://user-images.githubusercontent.com/9493082/57592774-08bc0100-756b-11e9-986d-fa66d6d629b5.png)


And this deployment Can be successfully created：

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train2
spec:
  replicas: 1
  selector:
      matchLabels:
        app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - command:
        - python
        - /app/tf-example.py
        env:
        - name: TEST_TMPDIR
          value: /app/mnist-data
        image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
        imagePullPolicy: IfNotPresent
        name: tensorflow
        volumeMounts:
        - mountPath: /app
          name: kubeflow-nfs
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: kubeflow-nfs
        nfs:
          path: /share/mnist/mnist-data
          server: 180.101.98.77
```


The current solution is to change the meta.name



it's can running
PS:  I just have 1 master and 1 node(gpu) in k8s
![image](https://user-images.githubusercontent.com/9493082/57592976-027a5480-756c-11e9-8b06-c0afb877179c.png)
![image](https://user-images.githubusercontent.com/9493082/57593190-ec20c880-756c-11e9-8245-fca9a107f565.png)

**Comment by lcax200000** [comment]
> Which version of K8s are you using? And are you using a hosted version of K8s?
> 
> It seems to me like there is something going on with the kubelet and not the TFJob controller.
> It looks like the kubelet is having trouble starting the container and not cleaning up the failed container properly before starting it.
> 
> To confirm this you might try creating a Deployment or Pod with the same spec and not using TFJob.
> 
> You might also want to try removing GPUs and seeing if that works.



@yylin1 

i'm create tfjob with this yaml:
```

apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: train2
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - command:
            - python
            - /app/tf-example.py
            env:
            - name: TEST_TMPDIR
              value: /app/mnist-data
            image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
            imagePullPolicy: IfNotPresent
            name: tensorflow
            volumeMounts:
            - mountPath: /app
              name: kubeflow-nfs
            resources:
              limits:
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
          volumes:
          - name: kubeflow-nfs
            nfs:
              path: /share/mnist/mnist-data
              server: 10.11.98.77
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - command:
            - python
            - /app/tf-example.py
            env:
            - name: TEST_TMPDIR
              value: /app/mnist-data
            image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
            imagePullPolicy: IfNotPresent
            name: tensorflow
            resources:
              limits:
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /app
              name: kubeflow-nfs
          restartPolicy: OnFailure
          volumes:
          - name: kubeflow-nfs
            nfs:
              path: /share/mnist/mnist-data
              server: 10.11.98.77
```

get error： 

![image](https://user-images.githubusercontent.com/9493082/57593149-c267a180-756c-11e9-813b-c53d79decb89.png)


![image](https://user-images.githubusercontent.com/9493082/57592774-08bc0100-756b-11e9-986d-fa66d6d629b5.png)


And this deployment Can be successfully created：

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train2
spec:
  replicas: 1
  selector:
      matchLabels:
        app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - command:
        - python
        - /app/tf-example.py
        env:
        - name: TEST_TMPDIR
          value: /app/mnist-data
        image: gcr.io/kubeflow-images-public/tensorflow-1.10.1-notebook-gpu:v0.3.1
        imagePullPolicy: IfNotPresent
        name: tensorflow
        volumeMounts:
        - mountPath: /app
          name: kubeflow-nfs
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: kubeflow-nfs
        nfs:
          path: /share/mnist/mnist-data
          server: 180.101.98.77
```


The current solution is to change the meta.name



it's can running
PS:  I just have 1 master and 1 node(gpu) in k8s
![image](https://user-images.githubusercontent.com/9493082/57592976-027a5480-756c-11e9-8b06-c0afb877179c.png)
![image](https://user-images.githubusercontent.com/9493082/57593190-ec20c880-756c-11e9-8245-fca9a107f565.png)
