### ISSUE TITLE
[kfctl] kfctl init with ISTIO still deploys ambassador

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#3282]
We already removed ambassador from components when using ISTIO.  Somehow if we deploy from HEAD ambassador is deployed despite of using ISTIO.

**Comment by gabrielwen** [comment]
when running `kfctl init`, with params `--platform gcp --project <project> -V --skip-init-gcp-project`, app.yaml looks like this:
```yaml
apiVersion: kfdef.apps.kubeflow.org/v1alpha1                                                                                                                                                                        
kind: KfDef
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: presubmit-testing
  name: presubmit-testing
  namespace: kubeflow
spec:
  appdir: /usr/local/google/home/gabrielwen/kubeflow/presubmit-testing
  componentParams:
    ambassador:
    - name: ambassadorServiceType
      value: NodePort
    argo:
    - initRequired: true
      name: injectIstio
      value: "true"
    centraldashboard:
    - initRequired: true
      name: injectIstio
      value: "true"
    cert-manager:
    - initRequired: true
      name: acmeEmail
      value: johnDoe@acme.com
    cloud-endpoints:
    - name: secretName
      value: admin-gcp-sa
    iap-ingress:
    - initRequired: true
      name: ipName
      value: ipName
    - initRequired: true
      name: hostname
      value: <deployName>.endpoints.<project>.cloud.goog
    jupyter-web-app:
    - initRequired: true
      name: injectIstio
      value: "true"
    katib:
    - initRequired: true
      name: injectIstio
      value: "true"
    notebook-controller:
    - name: injectGcpCredentials
      value: "true"
    spartakus:
    - initRequired: true
      name: usageId
      value: <randomly-generated-id>
    - initRequired: true
    - initRequired: true
      name: reportUsage
      value: "true"
    tensorboard:
    - initRequired: true
      name: injectIstio
      value: "true"
    tf-job-operator:
    - initRequired: true
      name: injectIstio
      value: "true"
  components:
  - metacontroller
  - ambassador
  - argo
  - centraldashboard
  - jupyter-web-app
  - katib
  - notebook-controller
  - pytorch-operator
  - tensorboard
  - tf-job-operator
  - pipeline
  - cert-manager
  - cloud-endpoints
  - gpu-driver
  - iap-ingress
  - spartakus
  email: gabrielwen@google.com
  packageManager: ksonnet
  packages:
  - argo
  - common
  - examples
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  - pipeline
  - gcp
  platform: gcp
  project: gabrielwen-learning
  repo: /usr/local/google/home/gabrielwen/kubeflow/presubmit-testing/.cache/kubeflow/master/kubeflow
  serverVersion: file:/usr/local/google/home/gabrielwen/kubeflow/presubmit-testing/.cache/kubeflow/master/bootstrap/k8sSpec/v1.11.7/api/openapi-spec/swagger.json
  skipInitProject: true
  useBasicAuth: false
  useIstio: true
  version: master
status: {}
```
