### ISSUE TITLE
TF Serving on AWS: model_base_path does not set correctly

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kubeflow#3323]
I am performing the following steps in order to serve a simple model from S3 using TF serving:

```
# set parameters
export MODEL_NAME=testmodel
export MODEL_COMPONENT=${MODEL_NAME}-v1
export SERVICE_NAME=${MODEL_NAME}-service
export BASE_DIR=/tmp/tf_serving/
export APP_DIR=${BASE_DIR}/${MODEL_NAME}
export MODEL_PATH=s3://rs-modeling/kubeflow-testing/${MODEL_NAME}

### Service

# fetch registry
rm -rf ${APP_DIR}
cd ${BASE_DIR}
ks init ${MODEL_NAME}
cd ${MODEL_NAME}

ks registry add kubeflow github.com/google/kubeflow/tree/master/kubeflow
export GITHUB_TOKEN=<my github token> #necessary to get higher rate limit, or next step will fail
ks pkg install kubeflow/tf-serving@master

# generate template
ks generate tf-serving ${SERVICE_NAME}

# set params
ks param set ${SERVICE_NAME} modelName ${MODEL_NAME}    # match your deployment model name,
# ks param set ${SERVICE_NAME} modelBasePath ${MODEL_PATH}    #This does not seem to have an effect, even if set it results in model_base_path=null
ks param set ${SERVICE_NAME} trafficRule v1:100    # optional, it's the default value
ks param set ${SERVICE_NAME} serviceType LoadBalancer    # optional, change type to LoadBalancer to expose external IP


### Deployment
# generate template
ks generate tf-serving-deployment-aws ${MODEL_COMPONENT} --name=${MODEL_NAME}

# create secret
export SECRET_NAME=aws-s3-access
export SECRET_FILENAME=secret.yaml
export SECRET_DIR=${BASE_DIR}/secret

kubectl apply -f ${SECRET_DIR}/${SECRET_FILENAME}


# set params
ks param set ${MODEL_COMPONENT} modelBasePath ${MODEL_PATH}
ks param set ${MODEL_COMPONENT} s3Enable true
ks param set ${MODEL_COMPONENT} s3SecretName aws-s3-access
ks param set ${MODEL_COMPONENT} numGpus 1
ks param set ${MODEL_COMPONENT} s3AwsRegion us-east-1
ks param set ${MODEL_COMPONENT} s3Endpoint s3.us-east-1.amazonaws.com # URL for your s3-compatible endpoint.

# deploy
export KF_ENV=default
ks apply ${KF_ENV} -c ${SERVICE_NAME}
ks apply ${KF_ENV} -c ${MODEL_COMPONENT}
```

As far as I can see this is correctly configured (at least based on what is suggested here: https://www.kubeflow.org/docs/components/tfserving_new/).

However, when running this the following happens:

```
$ kubectl get pods
NAME                                    READY     STATUS             RESTARTS   AGE
testmodel-7b77fb47c5-g7qt5              0/1       CrashLoopBackOff   9          26m
testmodel-service-v1-6b87cdcd88-twcj6   0/1       CrashLoopBackOff   9          26m
```

`testmodel-service-v1-6b87cdcd88-twcj6` will not start, resulting in following logs:

```
$ kubectl logs testmodel-service-v1-6b87cdcd88-twcj6
2019-05-21 09:24:44.179726: I tensorflow_serving/model_servers/server.cc:82] Building single TensorFlow model file config:  model_name: testmodel model_base_path: null
2019-05-21 09:24:44.280104: I tensorflow_serving/core/basic_manager.cc:280] Unload all remaining servables in the manager.
Failed to start server. Error: Invalid argument: Expected model testmodel to have an absolute path or URI; got base_path()=null
```

You can clearly see that the parameter is being set as `-model_base_path=null`

```
$ kubectl describe pod testmodel-service-v1-6b87cdcd88-twcj6
Name:               testmodel-service-v1-6b87cdcd88-twcj6
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               ip-192-168-25-23.ec2.internal/192.168.25.23
Start Time:         Tue, 21 May 2019 08:58:11 +0000
Labels:             app=testmodel-service
                    pod-template-hash=6b87cdcd88
                    version=v1
Annotations:        <none>
Status:             Running
IP:                 192.168.10.247
Controlled By:      ReplicaSet/testmodel-service-v1-6b87cdcd88
Containers:
  testmodel-service:
    Container ID:  docker://f520a68a8cd25b604335059929eb5d5c13908858a745bc83db750b9951e84fc0
    Image:         tensorflow/serving:1.11.1
    Image ID:      docker-pullable://tensorflow/serving@sha256:a01c6475c69055c583aeda185a274942ced458d178aaeb84b4b842ae6917a0bc
    Port:          9000/TCP
    Host Port:     0/TCP
    Command:
      /usr/bin/tensorflow_model_server
    Args:
      --port=9000
      --model_name=testmodel
      --model_base_path=null
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 21 May 2019 09:24:44 +0000
      Finished:     Tue, 21 May 2019 09:24:44 +0000
    Ready:          False
    Restart Count:  10
    Limits:
      cpu:     4
      memory:  4Gi
    Requests:
      cpu:        1
      memory:     1Gi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2m5hm (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-2m5hm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2m5hm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                                    Message
  ----     ------     ----                ----                                    -------
  Normal   Scheduled  27m                 default-scheduler                       Successfully assigned default/testmodel-service-v1-6b87cdcd88-twcj6 to ip-192-168-25-23.ec2.internal
  Normal   Pulled     26m (x5 over 27m)   kubelet, ip-192-168-25-23.ec2.internal  Container image "tensorflow/serving:1.11.1" already present on machine
  Normal   Created    26m (x5 over 27m)   kubelet, ip-192-168-25-23.ec2.internal  Created container
  Normal   Started    26m (x5 over 27m)   kubelet, ip-192-168-25-23.ec2.internal  Started container
  Warning  BackOff    2m (x116 over 27m)  kubelet, ip-192-168-25-23.ec2.internal  Back-off restarting failed container
```

I have tried setting `ks param set ${SERVICE_NAME} modelBasePath ${MODEL_PATH} ` but this doesn't seem to have any kind of influence. Is there any other way that the model_base_path can be set?

### EDIT:

As a workaround I was able to export the deployments as yaml files, then set the parameter manually as follows.

testmodel-service-v1.yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    ksonnet.io/managed: '{"pristine":"H4sIAAAAAAAA/5SSQY8TMQyF7/wMn2c6E2kvROoBgbTignqBy6qq0tQtEUkcYqdsVeW/I09F6WE5cLPGX+z3nucKroRvWDlQBgv4Kpi15uls9ijOwAA/Qj6AhU9YIl0SZoEBEoo7OHFgrxDdHiNr5UoBC4IsiQ4YR8Z6Dh51BlPOKKtAk6dUKOuYt9A+QHYJ3+qNZ1WjXS7OK3LAo2tR9BEX9CpBMJXoBLX+X5Hnew5nA70PULHE4B2DNX83eMriQsbKYF+u4OpJCxjHQlXW7+d5hgHGcRm+U7Xr+66Hxt4x7oqT7+vcYoTtAJ5Scpr0C0yN67QPedJrUD1G+rW7PVOxWBUPyZ1uMf1BpsVJPlmzMmalWS3MpsW4oRj8BSx8Pn4h2VTk2xn/FTUMoG5uDu+GN1QFrDrsWw2HqVWPS6gxpCBL5UsDC0/LP5Ko6tKn5wBLmj8b8iNlHimjlF4SfatBLh8pC76K0kd+rtQKWDPP8wC15Q/8lbHePvS+7b33d78BAAD//wEAAP//fPWekMwCAAA="}'
  creationTimestamp: null
  generation: 1
  labels:
    app: testmodel-service
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: testmodel-service
  name: testmodel-service-v1
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/testmodel-service-v1
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testmodel-service
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testmodel-service
        version: v1
    spec:
      containers:
      - args:
        - --port=9000
        - --model_name=testmodel
        - --model_base_path=s3://rs-modeling/kubeflow-testing/testmodel
        command:
        - /usr/bin/tensorflow_model_server
        image: tensorflow/serving:1.11.1
        imagePullPolicy: IfNotPresent
        name: testmodel-service
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          procMount: Default
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```

Then executed with `kubectl apply -f testmodel-service-v1.yaml`. The pod `  testmodel-service-v1-6b87cdcd88-twcj6` is now running correctly, so can confirm that if the parameter is correctly set the rest will work.
