### ISSUE TITLE
How to access Tensorboard and Argo from Kubeflow central dashboard?

### ISSUE THREAD

**Issue by dongdan39** [kubeflow/kubeflow#3353]
Hi, Experts,
  Can someone tell me how to access Tensorboard and Argo dashboard from Kubeflow central dashboard? Or if that is as designed, is it possible to add links to them on the central dashboards? Currently only the following 5 buttons visible:
Home
Kubeflow docs
Notebooks
TFJob Dashboard
Katib Dashboard
Pipeline Dashboard

  Thanks!
  Dan

**Comment by Rohithzr** [comment]
I too want to know how to get argo dashboard to display. This ingress throws a blank page with the following error. `SyntaxError: expected expression, got '<' main.f6e517525a3ff95bf2c8.js:1​` 
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: argo-ui
  namespace: kubeflow
spec:
  tls:
  - hosts:
    - kubeflow.kube.labroots.inkeystone.com
    secretName: kubeflow-kube-secret
  rules:
  - host: "kubeflow.domain.com"
    http:
      paths:
      - path: /argo
        backend:
          serviceName: argo-ui
          servicePort: 80
```
