### ISSUE TITLE
unknown field "allowSSH" in aws_config/cluster_config.yaml

### ISSUE THREAD

**Issue by gautamkmr** [kubeflow/kubeflow#3359]
Following this doc https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ to install kubeflow but failed by customizing it for GPU with allow ssh

https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/
https://www.kubeflow.org/docs/aws/customizing-aws/

[✖]  loading config file "/tmp/kubeflow-aws/kfapp/aws_config/cluster_config.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "allowSSH"

**Comment by Jeffwan** [comment]
Thanks for reporting this issue. eksctl APIVersion has some breaking changes in latetest. The template we are providing is based on older version.

Please check `https://github.com/weaveworks/eksctl/blob/master/pkg/apis/eksctl.io/v1alpha5/types.go` for latest changes. I think `allowSSH` is changed to `NodeGroupSSH.allow`

**Comment by jonin** [comment]
I get the same error for "NodeGroupSSH.allow: true"

**Comment by mbaijal** [comment]
Thanks @jonin, that helped. 
In addition to the path (using `PublicKeyPath`), you can also directly provide a key name that exists in your aws account as follows:
```
nodeGroups:
  - name: gpu-nodegroup
    instanceType: p2.8xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 30
    ssh:
      allow: true
      publicKeyName: <key-name>
```
