### ISSUE TITLE
Notebook: no status available

### ISSUE THREAD

**Issue by amarrella** [kubeflow/kubeflow#3403]
Hi, I'm trying to spawn a notebook but now i get notebook status unavailable for a very long time. I'm running v0.5-branch on AWS.

`notebook-controller` logs these error messages:
```json
{
  "level": "error",
  "ts": 1559667966.841203,
  "logger": "kubebuilder.controller",
  "msg": "Reconciler error",
  "controller": "notebook-controller",
  "request": "kubeflow/kf",
  "error": "the server could not find the requested resource (put notebooks.kubeflow.org kf)",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88"
}
```

which seem to suggest that it's not able to call the apiserver to put the notebook?

The notebook is there though, when i run `kubectl get notebook kf --namespace kubeflow`:
```yaml
Name:         kf
Namespace:    kubeflow
Labels:       app=notebook
Annotations:  <none>
API Version:  kubeflow.org/v1alpha1
Kind:         Notebook
Metadata:
  Creation Timestamp:  2019-06-04T17:06:06Z
  Generation:          1
  Resource Version:    111632
  Self Link:           /apis/kubeflow.org/v1alpha1/namespaces/kubeflow/notebooks/kf
  UID:                 0ac7998d-86eb-11e9-adb6-0ee87f503a4c
Spec:
  Template:
    Spec:
      Containers:
        Env:
        Image:  gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-cpu:v0.5.0
        Name:   kf
        Resources:
          Limits:
          Requests:
            Cpu:     1
            Memory:  1.0Gi
        Volume Mounts:
          Mount Path:              /home/jovyan
          Name:                    kubeflow-storage
      Service Account Name:        jupyter-notebook
      Ttl Seconds After Finished:  300
      Volumes:
        Name:  kubeflow-storage
        Persistent Volume Claim:
          Claim Name:  kubeflow-storage
Status:
  Conditions:
    Type:               Ready
  Created:              true
  Observed Generation:  1
  Phase:                Active
Events:                 <none>
```

Any idea on what might be happening?
Thanks again for your help, this project is amazing!
