### ISSUE TITLE
minio-pvc and mysql-pv-claim Pods stuck in Pending state although I have created 3 persistent volume

### ISSUE THREAD

**Issue by asispatra** [kubeflow/kubeflow#3481]
I was following [Kubeflow Troubleshooting](https://www.kubeflow.org/docs/other-guides/troubleshooting/) document section "Pods stuck in Pending state". One pvc become "Bound" state. but rest two are still pending although I have created three persistent volume.

```
$ kubectl -n kubeflow get pvc
NAME             STATUS    VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS   AGE
katib-mysql      Bound     pv-volume3   10Gi       RWO                           70m
minio-pvc        Pending                                                         69m
mysql-pv-claim   Pending                                                         69m

$ kubectl -n kubeflow describe pvc minio-pvc
Name:          minio-pvc
Namespace:     kubeflow
StorageClass:
Status:        Pending
Volume:
Labels:        app.kubernetes.io/deploy-manager=ksonnet
               ksonnet.io/component=pipeline
Annotations:   ksonnet.io/managed:
                 {"pristine":"H4sIAAAAAAAA/ySOPU/EMBBEe37G1OGzTEtBhUAUR4Eo9pwBrWLvGq9zFKf8d+Sje3oaPc0ZUvXAFuqGGad7TFjVFsx4HTY6rR88b4WPWbRgQmGXRbpgPiPLkTkGr...
               kubecfg.ksonnet.io/garbage-collect-tag: gc-tag
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Type       Reason         Age                  From                         Message
  ----       ------         ----                 ----                         -------
  Normal     FailedBinding  21s (x303 over 75m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
Mounted By:  minio-5f6b9b5b7-ms5kb

$ kubectl -n kubeflow describe pvc mysql-pv-claim
Name:          mysql-pv-claim
Namespace:     kubeflow
StorageClass:
Status:        Pending
Volume:
Labels:        app.kubernetes.io/deploy-manager=ksonnet
               ksonnet.io/component=pipeline
Annotations:   ksonnet.io/managed:
                 {"pristine":"H4sIAAAAAAAA/yyOPU8DMRBEe37G1Be+SrcUVAhEEQpEsfENyDp71/H6glB0/x05Svf0dvU0Z0hNezZPpgg4PWDCknRGwNuw3ql9b3ktfMqSCiYUdpmlC8IZWQ7MP...
               kubecfg.ksonnet.io/garbage-collect-tag: gc-tag
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Type       Reason         Age                  From                         Message
  ----       ------         ----                 ----                         -------
  Normal     FailedBinding  38s (x303 over 75m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
Mounted By:  mysql-657f87857d-dfxb7
```

Environment details:
OS: Ubuntu 18.04
Platform: x86

Thanks.

**Comment by hall** [comment]
This is because the docs are wrong :smile: the 2 pending PVCs are requesting 20Gi:

**Comment by hall** [comment]
This is because the docs are wrong :smile: the 2 pending PVCs are requesting 20Gi:
```
kubectl get pvc -o custom-columns='name:{.metadata.name},storage:{.spec.resources.requests.storage}'
name             storage
katib-mysql      10Gi
minio-pvc        20Gi
mysql-pv-claim   20Gi
```

**Comment by hall** [comment]
Here's a PR suggesting the change: https://github.com/kubeflow/website/pull/854

**Comment by AGKhalil** [comment]
I'm having trouble with this too. I get the following when I look at the pvc requests.
```
$ kubectl get pvc -o custom-columns='name:{.metadata.name},storage:{.spec.resources.requests.storage}' -n kubeflow
name                storage
katib-mysql         10Gi
metadata-mysql      10Gi
minio-pv-claim      20Gi
mysql-pv-claim      20Gi
```
And when I look at the pv I created, I get:
```
$ kubectl get pv -n kubeflow
NAME         CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                              STORAGECLASS    REASON   AGE
pv-volume2   10Gi       RWO            Retain           Bound    kubeflow/metadata-mysql            local-storage            65s
pv-volume3   10Gi       RWO            Retain           Bound    kubeflow/katib-mysql               local-storage            65s
pv-volume4   20Gi       RWO            Retain           Bound    ahmed/workspace-myfirst-notebook   local-storage            65s
pv-volume5   20Gi       RWO            Retain           Bound    ahmed/workspace-first-notebook     local-storage            65s
```
Nevertheless, looking at my pvcs I still get pending statuses.
```
kubectl get pvc -n kubeflow
NAME             STATUS    VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS    AGE
katib-mysql      Bound     pv-volume3   10Gi       RWO            local-storage   8s
metadata-mysql   Bound     pv-volume2   10Gi       RWO            local-storage   10s
minio-pv-claim   Pending                                          local-storage   8s
mysql-pv-claim   Pending                                          local-storage   8s
```
As a reference, here's my pv.yaml:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume2
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume3
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume4
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv4"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume5
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv5"
---
```
Any insight on this would be appreciated.
