### ISSUE TITLE
kfctl: kustomize component discovery logic is flawed

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#3491]
`kfctl` uses a function called `mapDirs` to discover the components available and map each component's name to its path.
However, the logic it uses for discovery is flawed and can lead to perplexing errors.

https://github.com/kubeflow/kubeflow/blob/24c39e3cd66862b9433f23f7f9cc2937c70a39dd/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go#L522-L523

In the above check, to check if a folder is a component, we check if the folder is a package name and a component name.
This makes the discovery's results _depend_ on what the user has asked.
The component discovery should yield the same results no matter what components the user asks for.

eg.
For a structure like:
```
|-- admission-webhook
    |-- bootstrap
        |-- base
    |-- webhook
        |-- base
```

If the KfDef is wrong like the following, the discovery code will think that the `admission-webhook` folder is a component, because of the check above.
```yaml
packages:
  - admission-webhook
components:
  - admission-webhook
```

If instead the KfDef is like the following, the components `bootstrap` and `webhook` will be discovered correctly.
```yaml
packages:
  - admission-webhook
components:
  - bootstrap
  - webhook
```

**Comment by jlewi** [comment]
Should we refactor the spec and get rid of components, packages, and componentParams?

This terminology no longer really makes sense now that we are using ksonnet.

Should we just refactor this into a list of applications

```
Applications:
   -  name: central-dashboard
      repoName:
      repoPath: 
      overlays:
         - overlay1 
         - overlay2
     parameters:
         - name: 
           value
``` 

For each application we can no specify its relative path within the repo so there's no more magic discovery going on.

**Comment by jlewi** [comment]
@yanniszark Can you help me understand what is release blocking? Unfortunately I think @kkasravi is OOO this rest of the week.

Why do we have packages and components? These concepts don't really make sense to me in the context of kustomize?

Should we pick one maybe packages and treat the value as a path to a kusotmization.yaml file.

So instead of 

```
packages:
  - admission-webhook
components:
  - bootstrap
  - webhook
```

We just do

```
components:
  - admission-webhook/bootstrap
  - admission-webhook/webhook
```

And treat the value as the relative path to the kustomization file?

Alternatively we could add something like application_types 

```
Applications:
   -  name: central-dashboard
      repoName:
      repoPath: 
      overlays:
         - overlay1 
         - overlay2
      parameters:
          - name: 
             value
```

And then add a method to try to auto populate Applications from packages/componentParams/componets perhaps by using the existing logic.

The advantage of this approach is that its much closer to a long term fix which decreases the likelihood that we run into other problems.

Providing a method to auto-populate Applications from packages/componentParams/componets means we don't have to update all existing usages in one go.

We can also write a unittest to verify the mapping happens correctly. 

Another advantage of this approach is that if need be we can just hardcode specific paths to use for existing components because any future changes should be using the new spec.

I think I favor this approach.
