### ISSUE TITLE
Expose the notebook by nodeport, the nodeport number changed everytime

### ISSUE THREAD

**Issue by BlodwenZ** [kubeflow/kubeflow#3602]
Hello,
I have deloyed kubeflow v0.5.1. Afterward I have build the notebook by UI, everything is fine till I wish to export this exact notebook via nodeport in order that our business user can be only access notebook without use the centre dashboard for test purpose. (I have not yet tried istios or other authentication)
I found out after I define the notebook service to be "NodePort" type and exact port number. The nodeport always changed.
Could someone help to fix it please?
Thanks in advance.

**Comment by emmayang** [comment]
@BlodwenZ Maybe I understand it wrong, but I think that is how NodePort works. It will randomly point the service to a random port above 30000, unless you specifically declare port number with `nodePort` like below:

```
  ports:
  - name: ambassador
    nodePort: 32032
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: ambassador
  type: NodePort
```
