### ISSUE TITLE
EKS GPU Support Issue (nvidia-device-plugin-daemonset crashes)

### ISSUE THREAD

**Issue by jerrylam** [kubeflow/kubeflow#3617]
I'm using kubeflow v0.5-branch and k8s version 1.12

I followed the instruction on updating the cluster_config.yaml to include this:
```
  - name: Tesla-V100
    instanceType: p2.xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 2
    volumeSize: 50
    ssh:
      allow: true
      publicKeyPath: '~/.ssh/id_rsa.pub'
```

After the nodegroup starts and apply k8s, I noticed that `nvidia-device-plugin-daemonset` pod crashed. 

Looking at the error, this is what I got:
```
  Warning  Failed     8m2s                   kubelet, ip-x.ap-south-1.compute.internal  Error: failed to start 
container "nvidia-device-plugin-ctr": Error response from daemon: OCI runtime create failed: 
container_linux.go:348: starting container process caused "process_linux.go:402: container init caused 
\"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , 
stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --
ldconfig=@/sbin/ldconfig --device=all --utility --pid=28909 
/var/lib/docker/overlay2/d2a5b4a4bad7f9f3b6c9c2c10137e76958c225b9a056475f0129a3f84b13dd8
f/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is 
detected\\\\n\\\"\"": unknown
```

There is only one nodegroup that is the p2.xlarge above. 

Anyone knows what I'm missing?

Thanks!
