### ISSUE TITLE
Kfctl create profile for user by default

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3639]
With 0.6.0 a user can no longer create notebooks in the "kubeflow" namespace. They need to create a profile (see https://bit.ly/2UOzzxB) which will create the namespace with appropriate service accounts.

```
apiVersion: kubeflow.org/v1alpha1
kind: Profile
metadata:
  name: <name of the name space to be used>
spec:
  owner:
    kind: User
    name: <ID of the user to use it>
```

We are planning a UI based flow to do that but the UI hasn't landed yet.

In the meantime, we could have `kfctl` automatically create profile for ${USER} running kfctl.
This would mean out of the box the user has a namespace they can run Kubeflow workloads in.

@yanniszark @kkasravi WDYT? Are either of you able to pick this up?
