### ISSUE TITLE
Liveness/Readiness checks for TF Serving

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#368]
See #64.

We should configure liveness and readiness probes for TF Serving. 

Its not clear if TF Serving out of the box has handlers that would be suitable for use in a liveness/readiness probe. I don't know that a gRPC server provides any either. So this could potentially require upstream work to TFServing.

**Comment by jlewi** [comment]
Does anyone know if TFServing provides a suitable handler that we could use for a basic readiness or liveness probe?

What about using the latest version of TFServing which has a REST interface?

**Comment by jlewi** [comment]
From Peng Yu in Slack

They are using the gRPC port

```
    readinessProbe:
          tcpSocket:
            port: 8500
          initialDelaySeconds: 60
          timeoutSeconds: 300
```
