### ISSUE TITLE
Notebook Controller should surface StatefulSet status in the Notebook CR if Pod is not created

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#3772]
The Notebook Controller sets the `status.containerState` in the Notebook CR only when the Pod is created. So, if there would be a problem with a missing Service Account or an unbound PVC, then the Pod will not be scheduled and thus the status in the Notebook CR will not be updated to provide the relative info.

The Controller should set the status in the Notebook CR even when the Pod is not scheduled. In this case, the Notebook Controller will need to query the [Events](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#event-v1-core) API and select the ones with
```yaml
involvedObject:
    apiVersion: apps/v1
    kind: StatefulSet
    name: <Notebook Name>
    namespace: <Notebook Namespace>
```

From the selected events, it should then only keep the latest one. From this event we need the `.message` field.

Lastly, in order for the jupyter-web-app to show a spinner and the status, the Notebook Controller will need to set the `status.containerState` in the CR to `waiting` and the `waiting.reason` to be the StatefulSet's event message.

/cc @lluunn
