### ISSUE TITLE
No Namespaces in Central Dashboard

### ISSUE THREAD

**Issue by SheharyarTkxel** [kubeflow/kubeflow#3870]
Kubeflow Dashboard doesn't have any Namespace in the dropdown. I've already gone through this [fix](https://github.com/kubeflow/manifests/pull/159/commits/273395ad7a45338815827f72dfda7348e32ad0f0) but it wasn't required since the yaml files in 0.6.1 version already includes those additions which have been suggested in the fix.

**Environment:**

- Kubeflow version: v0.6.1-rc.2-1-g3a37cbc6
- Kubernetes version: 1.13

**Comment by dss77** [comment]
I have the same issue here. I found that I'm using the file https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_k8s_istio.yaml as the config file for the `kfctl init` stage. This file makes Kubeflow always pull the head version from the repository which could be broken by frequent commits.

```yaml
...
spec:
  repos:
  - name: manifests
    root: manifests-master
    uri: https://github.com/kubeflow/manifests/archive/master.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
...
```
I changed the URLs to point at a defined release version from the repository, and it worked for me:

```
...
spec:
  repos:
  - name: manifests
    root: manifests-master
    uri: https://github.com/kubeflow/manifests/archive/v0.6.1.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/v0.6.1.tar.gz
```

Hope it helps.
