### ISSUE TITLE
What does "desiredCapacity" mean in the cluster_config.yaml file?

### ISSUE THREAD

**Issue by SheharyarTkxel** [kubeflow/kubeflow#3908]
**Scenario**
I am trying to autoscale GPU nodes from 0 to N. I configure my cluster_config.yaml file like this:
```
    desiredCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
    instanceType: p2.xlarge
    labels:
      k8s.amazonaws.com/accelerator: nvidia-tesla-k80
    maxSize: 3
    minSize: 0
    name: gpu-nodegroup
    volumeSize: 50
```
But when it deploys, the jupyter pod doesn't let me create a Notebook and instead says that there are insufficient GPUs. Now alternatively if I deploy with desiredCapacity=1, the notebook creates successfully. 

**Question**
I want to know what is this desiredCapacity? Does it mean that if I specify desiredCapacity=1 then my GPU node is active? If yes then what is the purpose of minSize=0?

**What I am Aiming for**
A successful creation of jupyter notebook means GPU nodes have scaled up. This is how I am testing the Cluster Autoscaler (CA). But since keeping desiredCapacity=1 successfully creates the jupyter notebook so it leads to confusion for me. Let me know if my testing method is correct, i.e. expecting the GPU nodes to scale up with desirecCapaity=0
