### ISSUE TITLE
Disable istio-injection in namespace profile controller creates? 

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#3935]
/kind enhancement

**Why you need this feature:**
Training job by default is not working because profile controller enables istio-injection in the namespace data scientist will work on. 

In order to ask istio not inject sidecar, user has to explicitly add annotations to pods like this

```
apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "distributed-tensorflow-job"
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 4
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: tensorflow
              image: gcr.io/kubeflow-ci/tf-dist-mnist-test:1.0
``` 

I am thinking if we should make it namespace level switch on by default. If there're more workloads using istio, it's worth, otherwise, it's better use pod level control. 

Seems user uses jupyter notebook needs sidecar. For most other components, there's no need to inject sidecar

**Describe the solution you'd like:**
Namespace:  `istio-injection=disabled`
Pod:  sidecar.istio.io/inject: "true"

**Anything else you would like to add:**
