### ISSUE TITLE
Istio-Gateway for created Notebook Servers is not configurable

### ISSUE THREAD

**Issue by crauterb** [kubeflow/kubeflow#3945]
/kind bug

**What steps did you take and what happened:**

I deployed v0.6.1. of Kubeflow in an existing Kubernetes Cluster with an existing Istio-Setup.
After adapting all _virtual-service_ definitions, I got stuck on deploying new notebooks: I was not able to configure the created virtual service for the created notebook server.

The default version that is deployed is:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notebook-kubeflow-my-jupyter
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /notebook/kubeflow/my-jupyter
    rewrite:
      uri: /notebook/kubeflow/my-jupyter
    route:
    - destination:
        host: my-jupyter.kubeflow.svc.cluster.local
        port:
          number: 80
    timeout: 300s
```
... and if I am not mistaken, this is hard-coded in the [notebook-controller.go](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/pkg/controller/notebook/notebook_controller.go#L431)

**What did you expect to happen:**

I expected to be able to configure the gateway using a `.yaml` file or environment variable.

**Anything else you would like to add:**

I generated the `.yaml` configuration using [this documentation](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/). 

**Environment:**

- Kubeflow version: : v.0.6.1
- kfctl version: : v0.6.1-rc.2-1-g3a37cbc6
- Kubernetes platform: on-premise Kubernetes cluster
- Kubernetes client version: (use `kubectl version`): v1.15.2
- Kubernetes server version: (use `kubectl version`): v1.11.3
- OS: Ubuntu

**Comment by yanniszark** [comment]
Seems like a limitation of the notebook controller.
Possible solution:
1. Add option in notebook controller to define the Istio Gateway.
2. Expose that option as a parameter in kubeflow/manifests.
3. Set that parameter to your desired value in the KfDef config file.

```yaml
applications:
- name: notebook-controller
  kustomizeConfig:
    overlays:
    - istio
    - application
    parameters:
    - name: istio-gateway
      value: mygateway
    repoRef:
      name: manifests
      path: jupyter/notebook-controller
```

/cc @kunmingg
