### ISSUE TITLE
Enable Oauth without Istio ?

### ISSUE THREAD

**Issue by menardorama** [kubeflow/kubeflow#3963]
/kind question

**Question:**
Hi
I just saw that Oauth is available on 0.6 release which is really great.

But default setup seems to need istio, that we don't want to use (too complicated to implement on our cluster, we already made choices for ingress controler that we don't want to reconsider)

We are already using OIDC for some of our applications (such as Kubernetes dashboard for instance) using a keycloak server and keycloak OIDC proxy.

Is it possible to avoid using istio ? 

Can I just update to Kubeflow 0.6 without any OIDC and just put my proxy in front of kubeflow or do I have to setup something else ?

At least if it's not possible right now, it would be great to have the option to avoid using Istio.

Thanks a lot for your help

**Comment by krishnadurai** [comment]
@menardorama You should be able to deploy Kubeflow with the following instructions:
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

To avoid OIDC and Istio installation, when you need to use this config [kfctl-k8s-istio](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_k8s_istio.yaml) instead. You can copy it and have a local copy to edit the config and follow instructions in these lines:
[Istio installation step](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_k8s_istio.yaml#L18)
[Istio resources defined for Kubeflow](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_k8s_istio.yaml#L35)

**Comment by menardorama** [comment]
ok thanks so once I have succeeded to dpeloy kubeflow without auth, I can put my OIDC proxy in front

**Comment by menardorama** [comment]
this seems not so easy to get it working
the profiles-deployment manager don't start is trying to find stuff related to istio (which I didn't deploy as I don't want it)

```
{"level":"info","ts":1566398664.7743032,"logger":"entrypoint","msg":"setting up client for manager"}
{"level":"info","ts":1566398664.7747223,"logger":"entrypoint","msg":"setting up manager"}
{"level":"info","ts":1566398664.830817,"logger":"entrypoint","msg":"Registering Components."}
{"level":"info","ts":1566398664.830859,"logger":"entrypoint","msg":"setting up scheme"}
{"level":"info","ts":1566398664.8310685,"logger":"entrypoint","msg":"Setting up controller"}
{"level":"info","ts":1566398664.8311505,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"profile-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1566398664.8313208,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"profile-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1566398664.831373,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"ServiceRole.rbac.istio.io","error":"no matches for kind \"ServiceRole\" in version \"rbac.istio.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/source/source.go:89\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:122\ngithub.com/kubeflow/kubeflow/components/profile-controller/pkg/controller/profile.add\n\t/go/src/github.com/kubeflow/kubeflow/components/profile-controller/pkg/controller/profile/profile_controller.go:91\ngithub.com/kubeflow/kubeflow/components/profile-controller/pkg/controller/profile.Add\n\t/go/src/github.com/kubeflow/kubeflow/components/profile-controller/pkg/controller/profile/profile_controller.go:64\ngithub.com/kubeflow/kubeflow/components/profile-controller/pkg/controller.AddToManager\n\t/go/src/github.com/kubeflow/kubeflow/components/profile-controller/pkg/controller/controller.go:29\nmain.main\n\t/go/src/github.com/kubeflow/kubeflow/components/profile-controller/cmd/manager/main.go:73\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}
{"level":"error","ts":1566398664.8314555,"logger":"entrypoint","msg":"unable to register controllers to the manager","error":"no matches for kind \"ServiceRole\" in version \"rbac.istio.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nmain.main\n\t/go/src/github.com/kubeflow/kubeflow/components/profile-controller/cmd/manager/main.go:74\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}
```
And tf-job-operator fail to start because of missing resource

```
{"filename":"app/server.go:75","level":"info","msg":"EnvKubeflowNamespace not set, use default namespace","time":"2019-08-21T14:44:24Z"}
{"filename":"app/server.go:79","level":"info","msg":"Using cluster scoped operator","time":"2019-08-21T14:44:24Z"}
{"filename":"app/server.go:85","level":"info","msg":"[API Version: v1 Version: v0.1.0-alpha Git SHA: Not provided. Go Version: go1.12 Go OS/Arch: linux/amd64]","time":"2019-08-21T14:44:24Z"}
W0821 14:44:24.398856       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"filename":"tf-operator.v1/main.go:40","level":"info","msg":"Setting up client for monitoring on port: 8443","time":"2019-08-21T14:44:24Z"}
{"filename":"app/server.go:209","level":"error","msg":"the server could not find the requested resource (get tfjobs.kubeflow.org)","time":"2019-08-21T14:44:24Z"}
{"filename":"app/server.go:109","level":"info","msg":"CRD doesn't exist. Exiting","time":"2019-08-21T14:44:24Z"}
```

I have used this config
```
apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: kubeflow_app
  namespace: kubeflow
spec:
  repos:
  - name: manifests
    root: manifests-master
    uri: https://github.com/kubeflow/manifests/archive/master.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/application-crds
    name: application-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: application/application
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: argo
    name: argo
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/centraldashboard
    name: centraldashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/webhook
    name: webhook
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: jupyter/jupyter-web-app
    name: jupyter-web-app
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-db
    name: katib-db
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-manager
    name: katib-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-controller
    name: katib-controller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-ui
    name: katib-ui # Issue: https://github.com/kubeflow/manifests/issues/151
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metadata
    name: metadata
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/metrics-collector
    name: metrics-collector
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/suggestion
    name: suggestion
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: jupyter/notebook-controller
    name: notebook-controller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-job-crds
    name: pytorch-job-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-operator
    name: pytorch-operator
  - kustomizeConfig:
      parameters:
      - initRequired: true
        name: usageId
        value: <randomly-generated-id>
      - initRequired: true
        name: reportUsage
        value: "true"
      repoRef:
        name: manifests
        path: common/spartakus
    name: spartakus
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: tensorboard
    name: tensorboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: tf-training/tf-job-operator
    name: tf-job-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/api-service
    name: api-service
  - kustomizeConfig:
      parameters:
      - name: minioPvcName
        value: minio-pv-claim
      repoRef:
        name: manifests
        path: pipeline/minio
    name: minio
  - kustomizeConfig:
      parameters:
      - name: mysqlPvcName
        value: mysql-pv-claim
      repoRef:
        name: manifests
        path: pipeline/mysql
    name: mysql
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/persistent-agent
    name: persistent-agent
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/pipelines-runner
    name: pipelines-runner
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/pipelines-ui
    name: pipelines-ui
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/pipelines-viewer
    name: pipelines-viewer
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/scheduledworkflow
    name: scheduledworkflow
  - kustomizeConfig:
      parameters:
      - initRequired: true
        name: admin
        value: tmenard@pasteur.fr
      repoRef:
        name: manifests
        path: profiles
    name: profiles
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: seldon/seldon-core-operator
    name: seldon-core-operator
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
```
