### ISSUE TITLE
[Central Dashboard] Shows user as anyonmous@kubeflow.org when logged in via IAP

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3986]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I'm logged into Kubeflow 0.6.2  (RC 0.2) using this [kfctl_gcp_iap.0.6.rc.2.yaml](https://raw.githubusercontent.com/kubeflow/kubeflow/c3199d931b9b82c8717057c7aca883d76bb5e1d5/bootstrap/config/kfctl_gcp_iap.0.6.2rc.yaml). When I log into the central dashboard via IAP it is showing I am `anonymous@kubeflow.org`.

This looks like a bug in the kustomize manifest. It doesn't look like the environment variables USERID_HEADER is set correctly.

```
  - env:
    - name: USERID_HEADER
      value: $(userid-header)
    - name: USERID_PREFIX
      value: $(userid-prefix)
    - name: PROFILES_KFAM_SERVICE_HOST
      value: profiles-kfam.kubeflow
``` 

See: https://github.com/kubeflow/kubeflow/issues/3900#issuecomment-524343425

Full pod spec is attached
[centraldashboard.spec.yaml.txt](https://github.com/kubeflow/kubeflow/files/3535036/centraldashboard.spec.yaml.txt)

@avdaredevil What is impacted by the failure to set USERID_HEADER and PREFIX correctly? Is it just which user is displayed in the centraldashboard? Does it have any impact on the profiles users will see.
