### ISSUE TITLE
kfctl_existing_arrikto doesn't create a username/password by default

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3997]
/kind bug

**What steps did you take and what happened:**

I installed kubeflow using kfctl_existing_arrikto.yaml following the instructions
https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/

I was expecting that a username/password would be created using the environment variables KUBEFLOW_USERNAME and KUBEFLOW_PASSWORD.

But after deploying kubeflow I could not login using that username and password.

Looking at the dex configmap it doesn't look like there is any user specified.

```
issuer: https://35.231.133.227:5556/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
oauth2:
  skipApprovalScreen: true
enablePasswordDB: true

staticClients:
- id: kubeflow-authservice-oidc
  redirectURIs:
  # After authenticating and giving consent, dex will redirect to
  # this url for the specific client.
  - https://35.231.133.227/login/oidc
  name: 'Kubeflow AuthService OIDC'
  secret: <...>
# Options for controlling the logger.
logger:
  level: "debug"
  format: "text"

```

**What did you expect to happen:**
Expected Dex to be configured with the username and password I set

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
 v0.6.2-rc.2
- Kubernetes platform: (e.g. `minikube`)
GKE
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/cc @yanniszark
