### ISSUE TITLE
Notebook controller scalability testing - # concurrent notebooks

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#4019]
/kind feature

In preparation for 1.0 we should do some scalability testing. We should define what dimensions of scalability we want to test but a good starting point would be number of concurrent notebooks resources.

For reference we could look at what we did for TFJob
kubeflow/tf-operator#829

**Comment by jlewi** [comment]
/lifecycle frozen

I think we can do something pretty minimal for 1.0; e.g.

* Write a pytest to spin up a 100 notebooks
* Manually check they are ok.

I think for 1.0 a manual test is ok.

**Comment by jlewi** [comment]
@fediazgon you mentioned in 
https://github.com/kubeflow/kubeflow/issues/3657#issuecomment-585248754

That you were working on updating 
https://github.com/jlewi/kubeflow/blob/1690703d261d29ccd7e1d5ff154d79064473d9d8/kubeflow/jupyter/tests/jupyter_test.py#L85

How's that going?

Could we use that as a basis for a load test? i.e. just run a for loop to create multiple notebooks?

**Comment by jlewi** [comment]
It looks like the latest code is here
https://github.com/kubeflow/kfctl/blob/master/py/kubeflow/kfctl/testing/pytests/jupyter_test.py

It looks like it has already been updated.
So I think we just have to modify it to do a scalability test.

**Comment by jlewi** [comment]
@zhenghuiwang said he could start work on this today.

**Comment by zhenghuiwang** [comment]
I successfully tested 15 concurrent notebook creations. ( More loads are unschedulable because my KF cluster only has 4 nodes)

I used a slightly different yaml template with PVC as follows:
```
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: jupyter-test
spec:
  template:
    spec:
      serviceAccountName: default-editor
      volumes:
        - name: test-vol
          persistentVolumeClaim:
            claimName: test-pvc
        - emptyDir:
            medium: Memory
          name: dshm
      containers:
      - image: gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-cpu:v1.0.0
        name: notebook
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
          - mountPath: /home/jovyan
            name: test-vol
          - mountPath: /dev/shm
            name: dshm
```

and 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

![Screen Shot 2020-02-13 at 6 13 23 PM](https://user-images.githubusercontent.com/8263977/74495791-a1323980-4e8d-11ea-9e9d-dea919cbe640.png)
