### ISSUE TITLE
"Couldn't copy application istio-ingress" error during kfctl generate on EKS

### ISSUE THREAD

**Issue by danieldn** [kubeflow/kubeflow#4057]
/kind bug

**What steps did you take and what happened:**

Followed documentation for deploying Kubeflow on AWS https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

Created EKS cluster using eksctl beforehand
```
$ eksctl create cluster \
--name demo02 \
--version 1.13 \
--nodegroup-name standard-workers \
--node-type t3.medium \
--nodes 3 \
--nodes-min 1 \
--nodes-max 4 \
--node-ami auto
```

Completed steps 1 and 2 for fetching kfctl v0.6.2, editing kfctl_aws.yaml with IAM role name
 ```
$ aws iam list-roles \
    | jq -r ".Roles[] \
    | select(.RoleName \
    | startswith(\"eksctl-$AWS_CLUSTER_NAME\") and contains(\"NodeInstanceRole\")) \
    .RoleName"

eksctl-demo02-nodegroup-standard-NodeInstanceRole-RBG4TXIX840Q
```

Received error on step 3 when running `kfctl generate all -V`

```
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application istio-ingress
```

**What did you expect to happen:**

`kfctl generate all` should not throw error

**Anything else you would like to add:**

First attempt running KF on AWS so appreciate any advice or guides in case missing something obvious.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): v0.6.2
- Kubernetes platform: (e.g. `minikube`) : AWS
- Kubernetes version: (use `kubectl version`): 1.13
- OS (e.g. from `/etc/os-release`):

**Comment by gigi-at-zymergen** [comment]
Getting the same thing. I'm wondering if it's related to https://github.com/kubeflow/manifests/pull/221 and wondering if I can just mkdir and just copy all the base files into a folder under ${KFAPP}/kustomize/istio-ingress

**Comment by gigi-at-zymergen** [comment]
I think this is an issue with a mismatch between the kubeflow/manifests `master` and the `v0.6-branch` archives. 

Master has recently merged istio-ingress manifests under an aws subfolder. I found I was able to generate if I modified my kfctl_aws.yaml config file to specify :
```
repos:
    - name: kubeflow
      root: kubeflow-0.6-branch
      uri: https://github.com/kubeflow/kubeflow/archive/v0.6-branch.tar.gz
    - name: manifests
      root: manifests-0.6-branch
      uri: https://github.com/kubeflow/manifests/archive/master.tar.gz

```
