### ISSUE TITLE
PVCs for jupyterhub notebook are not being created dynamically

### ISSUE THREAD

**Issue by catalinad90** [kubeflow/kubeflow#4104]
/kind bug

I have Kubeflow installed on Kubernetes cluster with the kustomize solution and kfctl. When I try to spawn a Jupyterhub notebook from the Kubeflow UI, the PVC of the notebook is not being created dynamically. I need to have a PVC already created (manually) in the namespace and then add the name of the PVC in the workspace volume section.

The default Storage Class of Kubernetes cluster is already set and is Hedvig.

**What did you expect to happen:**
 
The PVC of Jupyterhub Notebook should be created dynamically.
Example: Notebook with name test should also get PVC workspace-test on the fly once the Notebook was launched.

Expected:
kubectl get pvc workspace-test -n kubeflow
workspace-test  Bound ...

Actual result:
kubectl get pvc workspace-test -n kubeflow
No resources found

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: v1beta1
- kfctl version: (use `kfctl version`): v0.6.1-rc.2-1
- Kubernetes platform: (e.g. `minikube`) Kubernetes cluster on HyperV
- Kubernetes version: (use `kubectl version`): v1.14 
- OS (e.g. from `/etc/os-release`): CentOS Linux 7
 
Also, I get this warning once I try to spawn a new notebook. 
![image](https://user-images.githubusercontent.com/52741776/64609597-f5fcf000-d3d5-11e9-8bd0-2df8f2ab9489.png)

**Comment by jlewi** [comment]
@catalinad90 the error message is indicating that your cluster doesn't have a default storage class and that is why the PVC isn't created.

Above you said

> The default Storage Class of Kubernetes cluster is already set and is Hedvig.

Can you provide the output of 

```
kubectl get storageclass -o yaml 
```

So we can confirm that you have a default storage class defined.

/cc @kimwnasptd

**Comment by catalinad90** [comment]
Maybe is there a way to specify the storage type for the dynamic PVC in the kustomize file?

**Comment by catalinad90** [comment]
Yes, after some troubleshooting the storage was not set as default in kubernetes cluster. 
Is there a way to explicitly set the default storage in the kustomize deployment, without having to set the default storage in kubernetes?

For instance, in the jupyterhub deployment with helm there is a way to explicitly specify the default storage in the configuration.

singleuser:
  extraTolerations: []
  nodeSelector: {}
  extraNodeAffinity:
    required: []
    preferred: []
  extraPodAffinity:
    required: []
    preferred: []
  extraPodAntiAffinity:
    required: []
    preferred: []
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: '0.8.2'
  cloudMetadata:
    enabled: false
    ip: 169.254.169.254
  networkPolicy:
    enabled: false
    egress:
    # Required egress is handled by other rules so it's safe to modify this
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
  events: true
  extraAnnotations: {}
  extraLabels:
    hub.jupyter.org/network-access-hub: 'true'
  extraEnv: {}
  lifecycleHooks:
  initContainers: []
  extraContainers: []
  uid: 1000
  fsGid: 100
  serviceAccountName:
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: '0.8.2'
    pullPolicy: IfNotPresent
  imagePullSecret:
    enabled: false
    registry:
    username:
    email:
    password:
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: jupyterhub-singleuser
  defaultUrl: "/lab"

singleuser:
  extraTolerations: []
  nodeSelector: {}
  extraNodeAffinity:
    required: []
    preferred: []
  extraPodAffinity:
    required: []
    preferred: []
  extraPodAntiAffinity:
    required: []
    preferred: []
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: '0.8.2'
  cloudMetadata:
    enabled: false
    ip: 169.254.169.254
  networkPolicy:
    enabled: false
    egress:
    # Required egress is handled by other rules so it's safe to modify this
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
  events: true
  extraAnnotations: {}
  extraLabels:
    hub.jupyter.org/network-access-hub: 'true'
  extraEnv: {}
  lifecycleHooks:
  initContainers: []
  extraContainers: []
  uid: 1000
  fsGid: 100
  serviceAccountName:
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: '0.8.2'
    pullPolicy: IfNotPresent
  imagePullSecret:
    enabled: false
    registry:
    username:
    email:
    password:
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: jupyterhub-singleuser
  defaultUrl: "/lab"

```yaml
singleuser:
  extraTolerations: []
  nodeSelector: {}
  extraNodeAffinity:
    required: []
    preferred: []
  extraPodAffinity:
    required: []
    preferred: []
  extraPodAntiAffinity:
    required: []
    preferred: []
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: '0.8.2'
  cloudMetadata:
    enabled: false
    ip: 169.254.169.254
  networkPolicy:
    enabled: false
    egress:
    # Required egress is handled by other rules so it's safe to modify this
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
  events: true
  extraAnnotations: {}
  extraLabels:
    hub.jupyter.org/network-access-hub: 'true'
  extraEnv: {}
  lifecycleHooks:
  initContainers: []
  extraContainers: []
  uid: 1000
  fsGid: 100
  serviceAccountName:
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    **dynamic:**
      **storageClass:**
      **pvcNameTemplate:** claim-{username}{servername}
      **volumeNameTemplate:** volume-{username}{servername}
      **storageAccessModes:** [ReadWriteOnce]
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: '0.8.2'
    pullPolicy: IfNotPresent
  imagePullSecret:
    enabled: false
    registry:
    username:
    email:
    password:
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: jupyterhub-singleuser
  defaultUrl: "/lab"
```

Thanks a lot for the fast response!

**Comment by catalinad90** [comment]
This is the config file used with kfctl:
```
# This is the config to install Kubeflow on an existing k8s cluster.
# If the cluster already has istio, comment out the istio install part (2 places) below.
apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: demo
  namespace: {{namespace}}
spec:
  componentParams:
    application:
    - name: overlay
      value: application
    argo:
    - name: overlay
      value: istio
    centraldashboard:
    - name: overlay
      value: istio
    # Istio install. If not needed, comment out istio-crds and istio-install.
    istio-crds:
    - name: namespace
      value: istio-system
    istio-install:
    - name: namespace
      value: istio-system
    jupyter:
    - name: overlay
      value: application
    jupyter-web-app:
    - name: overlay
      value: istio
    - name: overlay
      value: application
    katib-ui: # Issue: https://github.com/kubeflow/manifests/issues/151
    - name: overlay
      value: istio
    metadata:
    - name: overlay
      value: istio
    minio:
    - name: minioPd
      value: dls-kf-storage-artifact-store
    - name: minioPvName
      value: minio-pv
    - name: minioPvcName
      value: minio-pv-claim
    mysql:
    - name: mysqlPd
      value: dls-kf-storage-metadata-store
    - name: mysqlPvName
      value: mysql-pv
    - name: mysqlPvcName
      value: mysql-pv-claim
    notebook-controller:
    - name: overlay
      value: istio
    - name: overlay
      value: application
    pipelines-ui:
    - name: overlay
      value: istio
    profiles:
    - name: overlay
      value: istio
    - initRequired: true
      name: admin
      value: {{email}}
    spartakus:
    - initRequired: true
      name: usageId
      value: <randomly-generated-id>
    - initRequired: true
      name: reportUsage
      value: "true"
    tensorboard:
    - name: overlay
      value: istio
    tf-job-operator:
    - name: overlay
      value: istio
  components:
  # Istio install. If not needed, comment out istio-crds and istio-install.
  - istio-crds
  - istio-install
  # This component is the istio resources for Kubeflow (e.g. gateway), not about installing istio.
  - istio
  - application-crds
  - application
  - metacontroller
  - argo
  - centraldashboard
  - bootstrap
  - webhook
  - jupyter-web-app
  - katib-db
  - katib-manager
  - katib-controller
  - katib-ui
  - metadata
  - metrics-collector
  - suggestion
  - notebook-controller
  - pytorch-job-crds
  - pytorch-operator
  - spartakus
  - tensorboard
  - tf-job-operator
  - api-service
  - minio
  - mysql
  - persistent-agent
  - pipelines-runner
  - pipelines-ui
  - pipelines-viewer
  - scheduledworkflow
  - profiles
  enableApplications: true
  packageManager: kustomize
  packages:
  - argo
  - common
  - examples
  - admission-webhook
  - istio
  - jupyter
  - katib-v1alpha2
  - metacontroller
  - metadata
  - modeldb
  - mpi-job
  - pytorch-job
  - tensorboard
  - tf-serving
  - tf-training
  - pipeline
  - profiles
  - application
  useIstio: true
  repos:
  - name: manifests
    root: manifests-master
    uri: https://github.com/kubeflow/manifests/archive/master.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
```
