### ISSUE TITLE
Cannot create new node groups in EKS

### ISSUE THREAD

**Issue by sushkov-r** [kubeflow/kubeflow#4111]
/kind bug

Node groups that are created after Kubeflow has been deployed don't get the same rights as the original node groups. Because of that pods that run on these nodes cannot do certain things, such as downloading data from S3.

**What steps did you take and what happened:**
I created an EKS cluster with two initial node groups [`cpu`, `gpu-1`] using `eksctl` and deployed KF on it. After KF has been deployed, I added a new node group [`gpu-2`] with the same definition as `gpu-1`.
After that, I ran the same task in Pipelines that downloads some data from S3 using both `gpu-1` and `gpu-2`.
The data are downloaded using AWS CLI: `aws s3 sync $1 .`
I was able to download those data on `gpu-1`, but not on `gpu-2`.

**What did you expect to happen:**
I expected both jobs to succeed. 

**Anything else you would like to add:**
Copying IAM inline policies from `gpu-1` Role to `gpu-2` in AWS Console fixes the issue. However, I think that kubeflow should be able to do this automatically.

`eksctl` cluster config:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kf
  region: eu-west-1
  version: "1.13"
nodeGroups:
- desiredCapacity: 2
  instanceType: m5.xlarge
  maxSize: 3
  minSize: 0
  name: cpu-nodegroup
  volumeSize: 30
- desiredCapacity: 0
  instanceType: p2.xlarge
  maxSize: 1
  minSize: 0
  name: gpu-nodegroup
  volumeSize: 40
- desiredCapacity: 0
  instanceType: p2.xlarge
  maxSize: 1
  minSize: 0
  name: gpu-nodegroup-2
  volumeSize: 40
```

**Environment:**

- Kubeflow version: `812ca7f`
- kfctl version: `v0.6.2-0-g47a0e4c7`
- Kubernetes platform: AWS EKS
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Ubuntu 18.10
