### ISSUE TITLE
Issue while merging PatchesJson6902 in MergeKustomizations

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/kubeflow#4136]
/kind bug

**What steps did you take and what happened:**
Added one more overlay for argo componet to update ClusterRoles using PatchesJson6902

content of argo kustomization(**argo/overlays/csf/kustomization.yaml**) as below 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: argo
  path: patch.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: argo-ui
  path: patch2.yaml
```
**patch.yaml &  patch2.yaml** contents are as below
- op: add
  path: /rules/0
  value:
    apiGroups:
      - extensions
    resourceNames:
      - privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use

**What did you expect to happen:**
After kfctl generate I was expecting two patch files argo-ClusterRole.yaml &  argo-ui-ClusterRole.yaml will get created with proper patch link in  new kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
configurations:
- overlays/istio/params.yaml
kind: Kustomization
namespace: kubeflow
patchesJson6902:
- path: argo-ClusterRole.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: argo
    version: v1beta1
- path: argo-ui-ClusterRole.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: argo-ui
    version: v1beta1
resources:
- overlays/istio/virtual-service.yaml
```
Instead i see only argo-ui-ClusterRole.yaml file is created with both patches added which is wrong
```
ls kustomize/argo/
argo-ui-ClusterRole.yaml  base  kustomization.yaml  overlays
```

**Anything else you would like to add:**
I could see problem in this line https://github.com/kubeflow/kubeflow/blob/0d52bb563d5f2f28da0def25f9b55fa99eefb740/bootstrap/pkg/kfapp/kustomize/kustomize.go#L972 where differnt path is added  for each PatchesJson6902 key(name) patch but while creating new patch files only one file is created https://github.com/kubeflow/kubeflow/blob/0d52bb563d5f2f28da0def25f9b55fa99eefb740/bootstrap/pkg/kfapp/kustomize/kustomize.go#L993 

**Environment:**

- Kubeflow version: `build version v0.6.2`
- kfctl version: `kfctl v0.6.2-0-g47a0e4c7`
- Kubernetes platform: `k8s cluster`
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS :
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
