### ISSUE TITLE
Presubmit for notebook-test is failing

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#4221]
Error:

```
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --namespace=kubeflow
 inifile: None
 rootdir: /
```

The namespace is passed here:
https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py#L407

This codepath hasn't changed in a long time, not sure why it is breaking now.

**Comment by jlewi** [comment]
I think @scottilee is updating that test in #4171 but it hasn't been merged yet.

**Comment by jlewi** [comment]
@richardsliu if this is in a presubmit could the problem be in the PR itself?

postsubmits look green but I'm not sure I see that particular test.
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-postsubmit

**Comment by jlewi** [comment]
kubeflow/kubeflow periodic master
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-master

here's a periodic run
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-periodic-master/1179501557733920774

63/64 tests passed and 1 was skipped.

But some of the argo workflows are failing
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-periodic-master-kfctl-go-iap-endpoint-0774-baaa?tab=workflow

The notebook_test step failed. I couldn't find any logs for that step. The events show the pod for that step started just fine.

**Comment by jlewi** [comment]
namespace is listed in conftest.py
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/jupyter/tests/conftest.py

It doesn't look like the working directory is set for that step.

```
- activeDeadlineSeconds: 3000
    container:
      command:
      - pytest
      - jupyter_test.py
      - -s
      - --namespace=kubeflow
      - --timeout=500
      - --junitxml=/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177/output/artifacts/junit_kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177/junit_jupyter-test.xml
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/gcp-credentials/key.json
      - name: PYTHONPATH
        value: /mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177/src/kubeflow/kubeflow:/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177/src/kubeflow/testing/py:/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177/src/kubeflow/tf-operator/py
      - name: GOPATH
        value: /mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177
      - name: KUBECONFIG
        value: /mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177/kfctl_test/.kube/kubeconfig
      - name: BUILD_ID
        value: '1179440908370710535'
      - name: JOB_SPEC
        value: '{"type":"periodic","job":"kubeflow-periodic-master","buildid":"1179440908370710535","prowjobid":"f81b70fc-e535-11e9-8742-32d4b56136c3"}'
      - name: REPO_OWNER
        value: kubeflow
      - name: PROW_JOB_ID
        value: f81b70fc-e535-11e9-8742-32d4b56136c3
      - name: JOB_TYPE
        value: periodic
      - name: JOB_NAME
        value: kubeflow-periodic-master
      - name: REPO_NAME
        value: kubeflow
      image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 4Gi
        requests:
          cpu: '1'
          memory: 1536Mi
      volumeMounts:
      - mountPath: /mnt/test-data-volume
        name: kubeflow-test-volume
      - mountPath: /secret/gcp-credentials
        name: gcp-credentials
    inputs: {}
    metadata:
      annotations:
        kubeflow.org/logs: https://console.cloud.google.com/logs/viewer?project=kubeflow-ci&advancedFilter=resource.type%3D%22k8s_container%22%0Ametadata.userLabels.step_name%3D%22notebook-test%22%0Ametadata.userLabels.%22workflows.argoproj.io%2Fworkflow%22%3D%22kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177%22%0Aresource.labels.container_name%3D%22main%22%0A&interval=P7D
      labels:
        BUILD_ID: '1179440908370710535'
        JOB_NAME: kubeflow-periodic-master
        JOB_TYPE: periodic
        PROW_JOB_ID: f81b70fc-e535-11e9-8742-32d4b56136c3
        REPO_NAME: kubeflow
        REPO_OWNER: kubeflow
        step_name: notebook-test
        workflow: kubeflow-periodic-master-kfctl-go-iap-endpoint-0535-1177
        workflow_template: kfctl_e2e
    name: notebook-test
    outputs: {}
```

That seems problematic.
