### ISSUE TITLE
Issue while merging PatchesJson6902 multiple targets with same path file in MergeKustomization

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/kubeflow#4247]
/kind bug

**What steps did you take and what happened:**
Issue is extension of #4136 
Added overlay to update multiple ClusterRoles(eg: argo and argo-ui) using PatchesJson6902 using same target.path file 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: argo
  path: patch.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: argo-ui
  path: patch.yaml
```
patch.yaml content is as below
```
- op: add
  path: /rules/0
  value:
    apiGroups:
      - extensions
    resourceNames:
      - privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use
```

**What did you expect to happen:**
After kfctl generate I was expecting two patch files argo-ClusterRole.yaml & argo-ui-ClusterRole.yaml will get created with proper patch link in new kustomization.yaml(kustomize is patching two clusterroles with content from patch.yaml) where as kfctl is ignoring 2nd clusterrole

**Anything else you would like to add:**
I could see problem in these lines - **not  sure whether this was done intentionally!**
https://github.com/kubeflow/kubeflow/blob/2395c5fc0d384cf6dd4d7167bbe9010cd1315b54/bootstrap/pkg/kfapp/kustomize/kustomize.go#L851
```
		if _, ok := kustomizationMaps[patchesJson6902Map][patchJson.Path]; !ok {
			parent.PatchesJson6902 = append(parent.PatchesJson6902, *patchJson)
			kustomizationMaps[patchesJson6902Map][patchJson.Path] = true
		}
```

**Environment:**

- Kubeflow version: build version v0.6.2
- kfctl version: kfctl v0.6.2-0-g47a0e4c7
- Kubernetes platform: k8s cluster
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS :
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
