### ISSUE TITLE
Upgrade fails when baseconfigpath is a directory path instead of HTTP uri

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#4301]
Suppose that this is our upgrade config:

```
apiVersion: kfupgrade.apps.kubeflow.org/v1alpha1
kind: KfUpgrade
metadata:
  name: update-kf-upgrade
spec:
  currentKfDef:
    name: kf-latest
  newKfDef:
    name: kf-latest
    version: v0.7.1
  baseConfigPath: ~/demo/deploy/kfctl_gcp_iap.yaml
```

This will fail with the following error:

```
parse ~/demo/deploy/kfctl_gcp_iap.yaml: invalid URI for request  filename="v1alpha1/application_types.go:322"
```
