### ISSUE TITLE
Upgrade expects kfdef version to match with the specified version in KfUpgrade file

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#4302]
For example, suppose this is the KfUpgrade file:
```
apiVersion: kfupgrade.apps.kubeflow.org/v1alpha1
kind: KfUpgrade
metadata:
  name: update-kf-upgrade
spec:
  currentKfDef:
    name: kf-latest
  newKfDef:
    name: kf-latest
    version: v0.7.1
  baseConfigPath: /usr/local/google/home/ricliu/demo/deploy/kfctl_gcp_iap.yaml
```

This means when we apply, kfctl will look for a KfDef with name `kf-latest` and version `v0.7.1`. If one is not found, then we will create one. 

This logic assumes that `version` is set to `v0.7.1` in the base config file. Otherwise, we will still generate a KfApp but with the wrong KfDef version. This will cause the apply step to fail.
