### ISSUE TITLE
How do I get automatic onboarding? 

### ISSUE THREAD

**Issue by jamesthegiantpeach** [kubeflow/kubeflow#4330]
/kind question

**Question:**
[Here](https://www.kubeflow.org/docs/other-guides/multi-user-overview/) I see that users are automatically on boarded. However, I checked out kubeflow/kubeflow tag v0.6.2 and kubeflow/manifests tag v0.6.2 and applied this kfdef

```
# This is the config to install Kubeflow on an existing K8s cluster, with support
# for multi-user and LDAP auth using Dex.
apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: demo
  namespace: kubeflow
spec:
  # Platform existing for pre-existing K8s
  platform: existing_arrikto
  componentParams:
    argo:
    - name: overlay
      value: istio
    centraldashboard:
    - name: overlay
      value: istio
    jupyter-web-app:
    - name: overlay
      value: istio
    katib-ui: # Issue: https://github.com/kubeflow/manifests/issues/151
    - name: overlay
      value: istio
    metadata:
    - name: overlay
      value: istio
    minio:
    - name: minioPvName
      value: minio-pv
    - name: minioPvcName
      value: minio-pv-claim
    mysql:
    - name: mysqlPvName
      value: mysql-pv
    - name: mysqlPvcName
      value: mysql-pv-claim
    notebook-controller:
    - name: overlay
      value: istio
    pipelines-ui:
    - name: overlay
      value: istio
    tensorboard:
    - name: overlay
      value: istio
    tf-job-operator:
    - name: overlay
      value: istio
  components:
  - metacontroller
  - argo
  - centraldashboard
  - bootstrap
  - webhook
  - jupyter-web-app
  - katib-db
  - katib-manager
  - katib-controller
  - katib-ui
  - metadata
  - metrics-collector
  - suggestion
  - notebook-controller
  - pytorch-job-crds
  - pytorch-operator
  - tensorboard
  - tf-job-operator
  - api-service
  - minio
  - mysql
  - persistent-agent
  - pipelines-runner
  - pipelines-ui
  - pipelines-viewer
  - scheduledworkflow
  - profiles
  packageManager: kustomize
  packages:
  - argo
  - common
  - examples
  - admission-webhook
  - jupyter
  - katib-v1alpha2
  - metacontroller
  - metadata
  - modeldb
  - mpi-job
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  - pipeline
  - profiles
  useIstio: true
  repos:
  - name: manifests
    uri: file://localhost/home/james/myome/manifests
  - name: kubeflow
    uri: file://localhost/home/james/myome/kubeflow

```
and everything seems to work fine except for the automatic onboarding doesn't happen. I just authenticate with Dex and it shows me a namespace called kubeflow-anonymous.

I am assuming that I have the wrong version of a repo checked out. What version supports automatic onboarding?

**Comment by jamesthegiantpeach** [comment]
nvm these repos ended up working fine sorry for the noise

```
  repos:
  - name: kubeflow
    uri: https://github.com/kubeflow/kubeflow/archive/77381fe66ae7bb1e83a48beacf7f3c20b4c289d8.tar.gz
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/56e2fb15db286198f7a53723cb1fbfecf3fe83fb.tar.gz
```
