### ISSUE TITLE
OIDC Authservice needs to work with a public IP for Dex

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kubeflow#4517]
/kind bug
/priority p1

**What steps did you take and what happened:**
When Dex's issuer is set to public IP and likewise OIDC Authservice's corresponding parameter for OIDC issuer is set to the same IP, the initial handshake fails.
This happens since OIDC Authservice blocks necessary open routes to Dex:
/keys - For JWKS
/.well-known/openid-configuration - for handshake
These paths should be whitelisted in the build for OIDC Authservice.

**Environment:**

- Kubeflow version: v0.7.0
- Kubernetes platform: (e.g. `minikube`): On-prem Dex based installation

**Comment by frosenberg** [comment]
I'm not sure my issue is related but I struggle to get Kubeflow+Dex+Microsoft connector to work with a DNS name. I essentially followed this guide: https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/ (I run the cluster on AKS, have configured a LB and LetsEncrypt to get a cert - that's all working fine)

I use the following Dex config in the config map called `dex`:

```yaml
issuer: https://kubeflow.mydomain.tech/dex
# issuer: http://dex.auth.svc.cluster.local:5556/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
oauth2:
  skipApprovalScreen: true
staticClients:
- id: kubeflow-oidc-authservice
  redirectURIs: ["/login/oidc"]
  name: 'Dex Login Application'
  secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
connectors:
- type: oidc
  # Required field for connector id.
  id: microsoft
  # Required field for connector name.
  name: Microsoft
  config:
    issuer: https://login.microsoftonline.com/<tenandId>/v2.0
    # Credentials can be string literals or pulled from the environment.
    clientID: <myclientId>
    clientSecret: <myclientsecret>
    redirectURI: https://kubeflow.mydomain.tech/dex/callback
    tenant: <tenandId>
    insecureSkipEmailVerified: true # not sure anymore why I added this
```

In addition to the above I registered an app in Azure AD for the above Microsoft provider with the callback url as specified above in the `redirectURI` field of the connector. 

I see this error in the log then:

```sh
k -n istio-system logs -l app=authservice -f
```

```
time="2019-11-24T15:34:29Z" level=info msg="URI is whitelisted. Accepted without authorization." ip=10.244.1.27 request="/dex/approval?req=muna7lqf7hy2yklhupzas57y3"
time="2019-11-24T15:34:29Z" level=error msg="Not able to verify ID token: oidc: id token issued by a different provider, expected \"http://dex.auth.svc.cluster.local:5556/dex\" got \"https://kf.mydomain.tech/dex\"" ip=10.244.1.27 request="/login/oidc?code=ksldtt22ny5zxkzx7aelplhqj&state=MTU3NDYwOTY0NnxFd3dBRUdwQlVsRlVNbEpXYUZaeWRERXpVRFk9fBp_WNVi6F9632dYOLheXpq_RhPyXfUjpWoZOj5YfaiT"
```

I can understand that error somewhat but if I change following in `kfctl_existing_arrikto.0.7.0.yaml` to change the `oidc_provider` to `http://kubeflow.mydomain.tech/dex`

 - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: namespace
        value: istio-system
      - name: userid-header
        value: kubeflow-userid
      - name: oidc_provider
        #value: http://dex.auth.svc.cluster.local:5556/dex
        value: http://kubeflow.mydomain.tech/dex
      - name: oidc_redirect_uri
        value: /login/oidc
      - name: oidc_auth_url
        value: /dex/auth
      - name: skip_auth_uri
        value: /dex
      - name: client_id
        value: kubeflow-oidc-authservice
      repoRef:
        name: manifests
        path: istio/oidc-authservice
    name: oidc-authservice


If I do that the `authservice` logs throw a 403 because they cannot fetch the OIDC config. 

Not sure how to proceed, I spend days debugging this so far.
