### ISSUE TITLE
Source input in the Artifact's tab of the pipeline runs is GCS specific 

### ISSUE THREAD

**Issue by barambani** [kubeflow/kubeflow#4534]
/kind bug

**What steps did you take and what happened:**
The source input in the Artifact's tab of the pipeline runs is GCS specific (see image)
![Screenshot 2019-11-27 at 16 22 07](https://user-images.githubusercontent.com/201339/69741259-a73c3800-1132-11ea-9ca2-a03b9f07efca.jpg)

**What did you expect to happen:**
I deploy kubeflow to AWS EKS and I would expect to allow also artifacts stored in S3

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.7.0
- Kubernetes platform: (e.g. `minikube`): AWS EKS
- Kubernetes version: (use `kubectl version`): 
```
clientVersion:
  buildDate: "2019-11-14T04:24:34Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.13
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-25T00:55:38Z"
  compiler: gc
  gitCommit: b8860f6c40640897e52c143f1b9f011a503d6e46
  gitTreeState: clean
  gitVersion: v1.14.8-eks-b8860f
  goVersion: go1.12.10
  major: "1"
  minor: 14+
  platform: linux/amd64
```
