### ISSUE TITLE
Pipeline's Artifacts ui doesn't show artifacts

### ISSUE THREAD

**Issue by barambani** [kubeflow/kubeflow#4535]
/kind bug

**What steps did you take and what happened:**
The pipeline's Artifacts ui doesn't show artifacts 
![Screenshot 2019-11-27 at 16 54 26](https://user-images.githubusercontent.com/201339/69743936-2cc1e700-1137-11ea-9f25-fcf18866e3e5.jpg)

**What did you expect to happen:**
I deploy kubeflow to AWS EKS and my default artifact repo is on S3. After some pipelines produce artifacts I was expecting to see them in the Artifacts page of the Pipelines UI. My repo definition is

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    artifactRepository:
      s3:
        bucket: {{ .Values.bucketName }}
        keyPrefix: {{ .Values.artifactsRoot }}
        endpoint: s3.amazonaws.com

```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.7.0
- Kubernetes platform: (e.g. `minikube`): AWS EKS
- Kubernetes version: (use `kubectl version`): 
```
clientVersion:
  buildDate: "2019-11-14T04:24:34Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.13
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-25T00:55:38Z"
  compiler: gc
  gitCommit: b8860f6c40640897e52c143f1b9f011a503d6e46
  gitTreeState: clean
  gitVersion: v1.14.8-eks-b8860f
  goVersion: go1.12.10
  major: "1"
  minor: 14+
  platform: linux/amd64
```
