### ISSUE TITLE
How to add default ports to Notebooks

### ISSUE THREAD

**Issue by szinck1** [kubeflow/kubeflow#4543]
/kind question

**Question:**
I need to be able to launch our Jupyter Notebooks with customized settings. i.e. Below is a working configuration that I need to duplicate in Kubeflow/JupyterHub. 

What's the recommended way of achieving this in Kubeflow? I looked at `PodDefault` but that seems to be for runtime configuration

Here's my config that works fine when I start it via `kubectl`,  I need to replicate it for pods launched by Kubeflow.

```
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  containers:
  - name: jupyter
    image: jupyter/all-spark-notebook
    ports:
    - name: notebook
      containerPort: 8888
    - name: comm
      containerPort: 37371
    - name: blockmngr
      containerPort: 6060
  serviceAccountName: spark
```
