### ISSUE TITLE
[AWS] Provide managed MYSQL solution for kubeflow

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#4546]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
Kubeflow components use Mysql for metadata. There's feedback asking to use managed  mysql solution like [RDS](https://aws.amazon.com/rds/) for reliability and maintenance purpose. 

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
We can expose an option in manifest plugin for user to specify this option, infra apply part, we can create RDS instance. Pipeline overlay also need to be changed

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by descampsk** [comment]
This feature is necessary if we want to go into production with kubeflow. 
There is this issue https://github.com/kubeflow/community/issues/188 but not very active :(

**Comment by descampsk** [comment]
I found a Config Map ml-pipeline-config : 

```
# The configuration for the ML pipelines APIServer
# Based on https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/config/config.json
apiVersion: v1
data:
  # apiserver assumes the config is named config.json
  config.json: |
    {
      "DBConfig": {
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "mlpipeline"
      },
      "ObjectStoreConfig":{
        "AccessKey": "minio",
        "SecretAccessKey": "minio123",
        "BucketName": "mlpipeline"
      },
      "InitConnectionTimeout": "6m",
      "DefaultPipelineRunnerServiceAccount": "pipeline-runner",
      "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST": "ml-pipeline-ml-pipeline-visualizationserver",
      "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_PORT": 8888
    }
kind: ConfigMap
metadata:
  name: ml-pipeline-config
```

@Jeffwan Do you think it will work if I change this config to point to an external rds database ?

**Comment by Jeffwan** [comment]
@descampsk 
Right now, by default it points to the mysql svc kubeflow bring up. I think you can update config to connect to external storage but I have not try it yet and I doubt following parameters are  generic enough. 

```
"DBConfig": {
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "mlpipeline"
      },
```

What we need to do is
1. Provision external resources when we deploy kubeflow.  Make sure connectivity in the same VPC
2. Make sure pipeline configurations are generic enough for external storages
3. Bring external configurations in pipeline/manifest

**Comment by descampsk** [comment]
@Jeffwan 
I did some tests and here is what I achieved : 

I achieve to connect Kubeflow to an external rds database using this configmap:

```
apiVersion: v1
data:
  config.json: |
    {
      "DBConfig": {
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "mlpipeline",
        "User": "${user}",
        "Password": "${password}",
        "Host": "${host}",
        "Port": "3306"
      },
      "ObjectStoreConfig":{
        "AccessKey": "minio",
        "SecretAccessKey": "minio123",
        "BucketName": "mlpipeline"
      },
      "InitConnectionTimeout": "6m",
      "DefaultPipelineRunnerServiceAccount": "pipeline-runner",
      "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST": "ml-pipeline-ml-pipeline-visualizationserver",
      "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_PORT": 8888
    }
kind: ConfigMap
metadata:
  name: ml-pipeline-config
```
See params available here: https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/client_manager.go

It seems to works well.

With more tests, I discovered that if you install Kubeflow, then remove it and reinstall it with the same external rds (already initialized), Kubeflow doesn't work well anymore.

It seems that the minio server must be initialized at the same time than the mysql instance.

Today I will try to externalize also the minio server to a S3 Bucket.

I keep you informed of my investigations.

**Comment by barambani** [comment]
I also managed to use a managed solution as Pipelines db. In my case I used env variable (this works nicely with the secrets that need to be used for the credentials). I used Aurora (but shouldn't be different for other RDS types. I wrote a customization like 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-api-server
        env:
        - name: DBCONFIG_HOST
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: host
        - name: DBCONFIG_PORT
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: port
        - name: DBCONFIG_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: DBCONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: DBCONFIG_DBNAME
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: PIPELINES_DB_NAME
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

```
where `my-secret` is clearly a secret in Secret Manager that provides those keys and `my-config-map` is a Config Map that provides specialized db names.
I'm also having troubles at the moment in moving the Pipelines graph data to S3 (it looks like that at the moment they are stored in Minio's fs that goes to pvc).
I hope it help.
