### ISSUE TITLE
kfctl_k8s_istio metadata deployments missing namespace reference

### ISSUE THREAD

**Issue by Atreus-Technologies** [kubeflow/kubeflow#4562]
/kind bug

**What happened:**

The `kfctl_k8s_istio.0.7.0.yaml` build, installed via `kfctl` does not appear adjust the namespaces in the metadata deployment's command. Deploying into a namespace other than `kubeflow` causes problems.

NB: This applies to both the grpc-server deployment as well as the other deployment (helpfully called 'deployment' in the same file).

**What did you expect to happen:**

e.g. the grpc-deployment should look like this - 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deployment
  labels:
    component: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grpc-server
  template:
    metadata:
      labels:
        component: grpc-server
    spec:
      containers:
        - name: container
          image: gcr.io/tfx-oss-public/ml_metadata_store_server:0.15.1
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: metadata-db-secrets
                key: password
          - name: MYSQL_USER_NAME
            valueFrom:
              secretKeyRef:
                name: metadata-db-secrets
                key: username
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: metadata-db-configmap
                key: mysql_database
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: metadata-db-configmap
                key: mysql_port
          command: ["/bin/metadata_store_server"]
          args: ["--grpc_port=8080",
                 "--mysql_config_host=metadata-db.$(POD_NAMESPACE)",
                 "--mysql_config_database=$(MYSQL_DATABASE)",
                 "--mysql_config_port=$(MYSQL_PORT)",
                 "--mysql_config_user=$(MYSQL_USER_NAME)",
                 "--mysql_config_password=$(MYSQL_ROOT_PASSWORD)"
          ]
          ports:
            - name: grpc-backendapi
              containerPort: 8080
```

**Environment:**

- Kubeflow version: 0.7.0
- kfctl version: (use `kfctl version`): kfctl v0.7.0-rc.8
