### ISSUE TITLE
Tensorboard Viewer pod not mounting service account credentials properly

### ISSUE THREAD

**Issue by chrisstockton** [kubeflow/kubeflow#4735]
/kind bug

**What steps did you take and what happened:**
I ran the mnist pipeline from the [examples](https://github.com/kubeflow/examples/blob/master/pipelines/mnist-pipelines/mnist_pipeline.py), but updated [model.py](https://github.com/kubeflow/examples/blob/master/mnist/model.py) file to include a tensorboard output field:

```
  if is_chief:
    print("Export saved model")
    classifier.export_savedmodel(args.tf_export_dir, serving_input_receiver_fn=serving_fn)
    print("Done exporting the model")
    # output tensorboard
    metadata = {
        'outputs' : [{
        'type': 'tensorboard',
            'source': args.tf_export_dir
        }]
    }
    with open('/mlpipeline-ui-metadata.json', 'w') as f:
        json.dump(metadata, f)
```

I then started a tensorboard for the output, but when I clicked the "Open Tensorboard" button
![image](https://user-images.githubusercontent.com/8291994/73822806-4455d400-483a-11ea-859a-1c43cb6cf908.png) 
A new tab opened with the following error message: 
```
Error occured while trying to proxy to: kubeflow.endpoints.<project_id>.cloud.googviewer-c6c1759a2bebee7a8538948f4f3838ef77637a83-service.kubeflow.svc.cluster.local:80/tensorboard/viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83/
```

I checked the logs of the newly created viewer pod `viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83-deploymentm6hgk` and saw the following error in the logs:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 586, in _reload
    multiplexer.AddRunsFromDirectory(path, name)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 189, in AddRunsFromDirectory
    for subdir in io_wrapper.GetLogdirSubdirectories(path):
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/io_wrapper.py", line 178, in GetLogdirSubdirectories
    if not tf.io.gfile.exists(path):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 280, in file_exists_v2
    pywrap_tensorflow.FileExists(compat.as_bytes(path))
PermissionDeniedError: Error executing an HTTP request: HTTP response code 403 with body '{
  "error": {
    "code": 403,
    "message": "Primary: /namespaces/<project_id>.svc.id.goog with additional claims does not have storage.objects.get access to <project_id>-kubeflow-bucket/export.",
    "errors": [
      {
        "message": "Primary: /namespaces/<project_id>.svc.id.goog with additional claims does not have storage.objects.get access to <project_id>-kubeflow-bucket/export.",
        "domain": "global",
        "reason": "forbidden"
  '
	 when reading metadata of gs://<bucket>/export
```

The service account (kubeflow-user@<project_id>.iam.gserviceaccount.com) is a `Storage Admin` and should be able to read from GCS, however the deployment shows that the secret is mounted incorrectly and `GOOGLE_APPLICATION_CREDENTIALS` is pointing to a directory.

```
$ kubectl describe deployment viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83-deployment
Name:                   viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83-deployment
Namespace:              kubeflow
CreationTimestamp:      Wed, 05 Feb 2020 15:51:17 +0900
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=viewer,deployment=viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83-deployment,viewer=viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=viewer
           deployment=viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83-deployment
           viewer=viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83
  Containers:
   viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83-pod:
    Image:      tensorflow/tensorflow
    Port:       6006/TCP
    Host Port:  0/TCP
    Args:
      tensorboard
      --logdir=gs://mercari-data-infra-test-kubeflow-bucket/export
      --path_prefix=/tensorboard/viewer-c6c1759a2bebee7a8538948f4f3838ef77637a83/
    Environment:
      GOOGLE_APPLICATION_CREDENTIALS:  /secret/gcp-credentials/user-gcp-sa.json
    Mounts:
      /secret/gcp-credentials/user-gcp-sa.json from gcp-credentials (ro)
  Volumes:
   gcp-credentials:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
```

The `Mount` should be `/secret/gcp-credentials` instead of `/secret/gcp-credentials/user-gcp-sa.json`.

**What did you expect to happen:**
The tensorboard viewer-deployment yaml should mount the secret as `/secret/gcp-credentials` and open without error.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 0.7.0
- kfctl version: kfctl v1.0-rc.1-0-g963c787
- Kubernetes platform: GCP
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.0", GitCommit:"a988db14950de3628f9e21773f3de0bf52485534", GitTreeState:"clean", BuildDate:"2019-12-11T22:37:55Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
cc @jessiezcc

**Comment by kim-sardine** [comment]
exactly same problem here!

**Comment by kim-sardine** [comment]
just in case of `secret/gcp-credentials` path issue, I'll attach a part ofmy viewer-deployments's yaml file
```
      containers:
      - args:
        - tensorboard
        - --logdir=gs://MY-BUCKET/output/logs
        - --path_prefix=/tensorboard/viewer-3e75f8012f366e91ec84b49e6ed193e10a3690f5/
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/user-gcp-sa.json
        image: tensorflow/tensorflow
        imagePullPolicy: Always
        name: viewer-3e75f8012f366e91ec84b49e6ed193e10a3690f5-pod
        ports:
        - containerPort: 6006
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secret/gcp-credentials/user-gcp-sa.json
          name: gcp-credentials
          readOnly: true
```

whereas my compiled pipeline yaml file is using different path

```
      "volumeMounts":
      - "mountPath": |-
          /secret/gcp-credentials
        "name": |-
          gcp-credentials-user-gcp-sa
```

I'm using latest kubeflow. I re-installed whole cluster yesterday.
