### ISSUE TITLE
For alb-ingress-controller the cluster-name arg defaults to name of folder where kfdef is stored

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kubeflow#4802]
When rolling out KF1.0 using `kfctl_aws_cognito.1.0.1.yaml` (and also `kfctl_aws.1.0.1.yaml`) , the `cluster-name` arg in the alb container spec defaults to the name of the folder in which the kfdef file is, regardless of what is input into the kustomize config.

For example, deploying kubeflow with:

`/path/to/kfctl apply -V -f /path/to/my_folder/kfctl_aws_cognito.1.0.1.yaml`

`kubectl -n kubeflow get deployment/alb-ingress-controller -o yaml` yields:

```
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
  template:
    spec:
      containers:
      - args:
        - --ingress-class=alb
        - --cluster-name=my_folder
        image: docker.io/amazon/aws-alb-ingress-controller:v1.1.2
        imagePullPolicy: Always
        name: alb-ingress-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

```

Currently this has to be patched manually afterward deployment.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): dev_local
- kfctl version: (use `kfctl version`): v1.0.1
- Kubernetes platform: (e.g. `minikube`): EKS
- Kubernetes version: (use `kubectl version`): 1.1.4
- OS (e.g. from `/etc/os-release`):
