### ISSUE TITLE
Notebook auto-scaling

### ISSUE THREAD

**Issue by fsaina** [kubeflow/kubeflow#4839]
/kind question

**Question:**
I've installed kubeflow (1.0) on AWS on a EKS cluster with autoscaling. Min number of instances 0, max number of instances 4, and desired 2.

I was under the impression that as I request for more notebooks (and resources for it) Kubeflow would be smart enough to auto-scale by itself until it hits the max limit (4 instances in my case). Is that the intended behavior or auto-scaling is intended to be done manually trough the underlying EKS cluster ?

**Comment by Jeffwan** [comment]
Hi, please check here. 
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#scaling-a-node-group-to-0

In that case, you need to configure PodDefault in your notebook servers and then use node group selector. Autoscaler will find node template and trigger it. If it hit ASG maximum, then it won't be able to scale out again.

**Comment by fsaina** [comment]
Ok thanks! 

Just to expand on my intentions for notebook aut-scaling, I have a cluster containing multiple CPU and GPU nodegroups. To avoid having my CPU workload end up on expensive GPU nodes I've added taints to those nodegroups.

How would I go about adding a nodeSelector/tolerations to my notebook pods for which the user requires GPU (non GPU workload would be without nodeSelector/tolerations so it ends up on CPU nodes) ?

**Comment by fsaina** [comment]
I've created and applied the following PodDefault:
```
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: gpu-notebook
  namespace: kubeflow-anonymous
spec:
 selector:
    matchLabels:
      gpu-notebook: "true"
 desc: "GPU notebook"
 nodeSelector:
  - nvidia.com/gpu: "true"
 tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
```

But my "nvidia.com/gpu" toleration does not get applied to new notebook pods. Could anyone suggest why? According to my understanding of [this](https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/README.md) the notebook-controller should intercept all pod creation requests with _gpu-notebook: "true"_ flag and append the _nodeSelector_ and _tolerations_ descriptors. That doesn't happen since when I do `kubectl get pods -n kubeflow-anonymous -o json | jq '.items[].spec.tolerations'` only the kubeflow default ones are liste ('node.kubernetes.io/unreachable' and 'node.kubernetes.io/not-ready')
