### ISSUE TITLE
Profile controller's AwsIamForServiceAccount plugin is not recognized

### ISSUE THREAD

**Issue by shuaibiyy** [kubeflow/kubeflow#4843]
/kind bug

**What steps did you take and what happened:**
I deployed Kubeflow on EKS using the instructions outlined in https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/
I then created a profile that should have access to an IAM role using the following template:
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-anonymous
spec:
  owner:
    kind: User
    name: anonymous@kubeflow.org
  plugins:
  - kind: AwsIamForServiceAccount
    spec:
      awsIamRole: arn:aws:iam::XXXXXXXXX:role/xxxxxxxxxxxxxxxxxxxxxxx
```
However, the **IAM plugin for profile controller** appears to be unavailable based on the controller's logs:
```
INFO  controllers.Profile  Plugin not recgonized:  {"profile": "kubeflow-anonymous", "Kind": "AwsIamForServiceAccount"}
INFO  controllers.Profile  Plugin not recgonized:  {"profile": "kubeflow-anonymous", "Kind": "AwsIamForServiceAccount"}
```
I looked at the [manifest](https://github.com/kubeflow/manifests/archive/v1.0.0.tar.gz) used by kfctl and it seems the controller's image is quite old: gcr.io/kubeflow-images-public/profile-controller:v20190619-v0-219-gbd3daa8c-dirty-1ced0e

Support for IAM roles was added in https://github.com/kubeflow/kubeflow/pull/4751 a few weeks ago before the release of v1.0, and I thought it made it into the release. Maybe I got it wrong?

**What did you expect to happen:**

I expected a profile to be created configured with a service account that has the permissions granted via the IAM role.

**Environment:**

- Kubeflow version: 1.0
- kfctl version: (use `kfctl version`): v1.0-0-g94c35cf
- Kubernetes platform: (e.g. `minikube`): AWS
- Kubernetes version: (use `kubectl version`): v1.17.3
- OS (e.g. from `/etc/os-release`): macOS Mojave
