### ISSUE TITLE
Kubeflow UI install + GCP Cloud Filestore

### ISSUE THREAD

**Issue by FKSI** [kubeflow/kubeflow#4870]
Hi,

I'm trying to follow [Using Cloud Filestore
](https://www.kubeflow.org/docs/gke/cloud-filestore/) guide but I have installed Kubeflow on GCP via the UI. It seems that the guide is only for CLI installation. 

Is there a hidden guide? :)

**Comment by FKSI** [comment]
I figured out, thanks a lot to @rmgogogo

# How to use Cloud Filestore with Kubeflow (even installed via UI)

## Create Cloud Filestore

1. Open Cloud Shell
   
   Please make sure it's in the same project and same VPC with the KFP.
    ```
    gcloud filestore instances create kf-nfs-sever \
        --project=[GCP_PROJECT_ID] \
        --zone=[GCP_ZONE] \
        --tier=STANDARD \
        --file-share=name="[NFS_VOLUME_NAME]",capacity=[NFS_VOLUME_CAPACITY] \
        --network=name="default",reserved-ip-range="10.0.7.0/29"
    ```
    ⚠️ `[NFS_VOLUME_CAPACITY]` is at least 1TB
2. Wait the operation to finished then enter the following command to get the NFS IP address: 
   
   `gcloud --project=[GCP_PROJECT_ID] filestore instances list`

3. Keep the IP address somewhere.

## Create K8s resource files for PV and PVC. 

1. Create a file name `pv.yaml`
2. Add the following content: 
   ```
    apiVersion: v1
    kind: PersistentVolume
    metadata:
        name: [PERSISTANT_VOLUME_NAME]
        namespace: kubeflow
    spec:
        capacity:
            storage: [PERSISTENT_VOLUME_CAPACITY] 
        accessModes:
            - ReadWriteMany
        nfs:
            path: /[NFS_VOLUME_NAME]
            server: [NFS_IP_ADRESS] 
   ```
   ⚠️ Please note that `[PERSISTENT_VOLUME_CAPACITY]` should not exceed `[NFS_VOLUME_CAPACITY]`

3. Create file name `pvc.yaml`
4. Add the following content: 
   ```
   apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
        name: [PERSISTANT_VOLUME_CLAIM_NAME]
        namespace: kubeflow
    spec:
        accessModes:
        - ReadWriteMany
        storageClassName: ""
        volumeName: [PERSISTANT_VOLUME_NAME]
        resources:
            requests:
                storage: [PERSISTENT_VOLUME_CLAIM_CAPACITY] 
   ```
    ⚠️ Please note that `[PERSISTENT_VOLUME_CLAIM_CAPACITY]` should not exceed `[PERSISTENT_VOLUME_CAPACITY]`
5. Go to https://console.cloud.google.com/kubernetes/list and connect to the Cluster
6. In Cloud Shell enter `kubectl create -f pv.yaml` then `kubectl create -f pvc.yaml`
