### ISSUE TITLE
Upgrade from 0.7.1 to 1.0.1: spec.selector field is immutable

### ISSUE THREAD

**Issue by Archa91** [kubeflow/kubeflow#4873]
/kind bug

Hi ! I successfully upgraded my kubeflow 0.7.1 to 1.0.1 but not without difficulties. So I wanted to share with you my experience and ask a little question by the way :)

**What steps did you take and what happened:**
I follow steps described at https://www.kubeflow.org/docs/upgrading/upgrade/

Here is my upgrade file:
```yaml
apiVersion: kfupgrade.apps.kubeflow.org/v1alpha1
kind: KfUpgrade
metadata:
  name: kf-upgrade-v1.0.1
spec:
  currentKfDef:
    # Replace with the name of your Kubeflow app
    name: <edited>
    version: v0.7.1
  newKfDef:
    # Replace with the name of your kubeflow app
    name: <edited>
    version: v1.0.1
  baseConfigPath: https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.1.yaml
```

Following the documentation, I started my upgrade with a `kfctl build` to generate the 7-character long hash directory and I have updated the kustomize directory to reflect my changes like the 0.7.1 version kustomize directory (like ingress address or iam instance role in KfAwsPlugin).

During the `kfctl apply` I encountered multiple errors like this:
```
for: "/tmp/kout261677621": Deployment.apps "ml-pipeline" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"ml-pipeline", "app.kubernetes.io/component":"api-service",
 "app.kubernetes.io/instance":"api-service-0.2.0", "app.kubernetes.io/managed-by":"kfctl", "app.kubernetes.io/name":"api-service", "app.kubernetes.io/part-of":"kubeflow", "app.kubernetes.io/version":"0.2.0"}, Ma
tchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable  filename="kustomize/kustomize.go:202"
```

**What did you expect to happen:**
I successful upgrade of Kubeflow from 0.7.1 to 1.0.1.

**Anything else you would like to add:**

After some research, it appears than since apps/v1beta1, spec.selector are indeed immutable.

I ended to delete relevant deployment to allow the re-creation with new spec.selector during the `apply`, and wait for the retry.

Example: `kubectl -n kubeflow delete deploy ml-pipeline`

As documented here: https://kubectl.docs.kubernetes.io/pages/app_management/labels_and_annotations.html

"commonLabels should only be set for immutable labels, since they will be applied to Selectors."

Quick questions: After an upgrade, what should I do with my  7-character long hash directory and my old directory ? How can I merge ? Should I download the 1.0.1 kfctl manifest and build my kustomize directories again now that my cluster is updated ?

**Environment:**

- Kubeflow version: 0.7.1 (1.0.1 for the upgrade)
- kfctl version: 0.7.1 (1.0.1 during the upgrade)
- Kubernetes platform:  AWS EKS
- Kubernetes version: `Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

- OS (e.g. from `/etc/os-release`): 

Thank you for your great work ! :)
