### ISSUE TITLE
Profile Spec to include users other than the owner

### ISSUE THREAD

**Issue by sshakeri** [kubeflow/kubeflow#4885]
/kind feature

Current profile spec used by the profile controller only includes the owner. Since profiles translate to namespaces it seems not possible to add multiple users to the same namespace (profile).  It ends up creating crowded namespaces in a shared cluster.

Instead the namespace could be shared by a team, without creating a namespace for each user.

**Describe the solution you'd like:**

```
kind: Profile
metadata:
  name: team-project
spec:
  owner:
    kind: User
    name: admin@example.com
   users:
     -name: user1@example.com
     -name: user2@example.com
     -name: user3@example.com

```
