### ISSUE TITLE
Is it possible to host centraldashboard on [PUBLIC_URL_CLUSTER]/kf/ path instead of using nodeport or  hosting it on '/' path?

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/kubeflow#4898]
/kind question

**Question:**
In our organization, Kubeflow is getting installed on a platform along with many other applications(data analytics).
In our platform, web access via node port access is discouraged and suggested to use Nginx(accessing the application from '/' is also not recommended).
We tried similar to AWS ingress https://github.com/kubeflow/manifests/blob/044a4e1039681f9e2db8f6a9911ecc1634d7372b/aws/istio-ingress/base/ingress.yaml

I have tried to change the central dashboard public/index.html not to restrict '/'. 

By commenting out the line
https://github.com/kubeflow/kubeflow/blob/06bf3a40679a64cecb463c7a6363c678e5ba42a9/components/centraldashboard/public/index.html#L23 
and changing below path to some other path

https://github.com/kubeflow/manifests/blob/044a4e1039681f9e2db8f6a9911ecc1634d7372b/common/centraldashboard/overlays/istio/virtual-service.yaml#L13

I am able to access the central dashboard menu page but not the main page.

Is there any way we can access the dashboard in another path than '/'

**Comment by hemantha-kumara** [comment]
Error page

![image](https://user-images.githubusercontent.com/26644179/77760794-f6e92c80-705c-11ea-9109-c021176c673f.png)

**Comment by hemantha-kumara** [comment]
ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: kfingress
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /kf/
```
