### ISSUE TITLE
Using Kubeflow with Jupyter & pipelines, how should we share our data among our scientists?

### ISSUE THREAD

**Issue by Shaked** [kubeflow/kubeflow#4901]
/kind question

**Question:**

We have started to migrate our ML infrastructure to [kubeflow](https://www.kubeflow.org/) as we are growing and need a clear structural way to:

1. Develop our algorithms 
2. Run experiments
3. Train our models

Up until now, we have been working with dedicated GPU servers, which contain a `/data/datasets` directory which includes all of our data. Excluding the `hdf5` files, our data is about 200G and growing. 

Moving to kubeflow brings also some challenges, as we want our data scientists to be able to share results with each other but also work alone. 

Currently, we have chosen Google's GKE and we have set kubeflow on it. 

At first, we wanted to create a general Persistent Volume (PV) with a `ReadWriteMany` attribute and then allow all of our kubeflow scientists to mount this PV. However, this is not possible due to the limitation of kuberenets: 

> PersistentVolumes binds are exclusive, and since PersistentVolumeClaims are namespaced objects, mounting claims with “Many” modes (ROX, RWX) is only possible within one namespace.
(https://kubernetes.io/docs/concepts/storage/persistent-volumes/)

We are trying to avoid the scenario where our scientists would have to download the data every time from scratch. We do understand that they would have to **sync** it with new data that is being generated in the meanwhile, and that's completely fine. 

What would be the "right" way or some best practices for this scenario? 

**EDIT**

I have followed the [Google Filestore guide](https://www.kubeflow.org/docs/gke/cloud-filestore/#about-cloud-filestore). However, with this solution it won't be possible to share data between different kubeflow users as it is not possible to share PVC between namespaces and it's not possible to have multiple PVCs claiming the same PV. 

Our datasets weigh more than 200G, so it won't be practical to clone the dataset per each user.

**Comment by Kulikovpavel** [comment]
Finally, i figured out, how to work with NFS volume in different namespaces, Filestore instance

Solution - create several persistent volumes with the same nfs data, and then several PV claims for each namespace
```
apiVersion: v1
kind: PersistentVolume
metadata:
 name: fileserver
spec:
 capacity:
   storage: 50G
 accessModes:
 - ReadWriteMany
 nfs:
   path: /kubeflow
   server: nfs_ip

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: fileserver2
spec:
 capacity:
   storage: 50G
 accessModes:
 - ReadWriteMany
 nfs:
   path: /kubeflow
   server: nfs_ip

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: fileserver-claim
 namespace: kubeflow
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: ""
 volumeName: fileserver
 resources:
   requests:
     storage: 5G


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: fileserver-claim
 namespace: kubeflow-xxx
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: ""
 volumeName: fileserver2
 resources:
   requests:
     storage: 5G
```

And you will get the same data.

Pipelines launch pods in `kubeflow` namespace, so you should create PVC in that namespace for sure
In pipeline itself you should set something like that:
```
training = dsl.ContainerOp(
        name="training model",
        image="image",
        arguments=[
           ...
        ],
        pvolumes={
            "/mnt/fileserver" : PipelineVolume(pvc="fileserver-claim")
        },
```
