### ISSUE TITLE
Upgrading 1.0.0 to 1.0.1 fails with "invalid config: apiVersion is not found."

### ISSUE THREAD

**Issue by lalithvaka** [kubeflow/kubeflow#4911]
/kind bug

**What steps did you take and what happened:**
➜ sudo kfctl build -f /Users/lalithvaka/installs/kfctl_upgrade_spec.yaml -V
INFO[0000] Downloading /Users/lalithvaka/installs/kfctl_upgrade_spec.yaml to /tmp/532268644/update.yaml  filename="v1alpha1/application_types.go:129"
INFO[0000] Found KfCfg with matching name: kf-poc1 version: v1.0.0 at kf-poc1/kfctl_istio_dex.v1.0.0.yaml  filename="kfupgrade/kfupgrade.go:195"
INFO[0001] Downloading https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.1.yaml to /tmp/408838771/tmp_app.yaml  filename="loaders/loaders.go:71"
Error: couldn't load KfUpgrade:  (kubeflow.error): Code 500 with message: Encountered error while creating new KfApp kf-poc1:  (kubeflow.error): Code 500 with message: Could not load https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.1.yaml. Error:  (kubeflow.error): Code 400 with message: invalid config: apiVersion is not found.
Usage:
  kfctl build [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                      		export CONFIG=./kfctl_gcp_iap.yaml
                      	or a URL:
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                      	kfctl build -V --file=${CONFIG}
  -h, --help          help for build
  -V, --verbose       verbose output default is false

couldn't load KfUpgrade:  (kubeflow.error): Code 500 with message: Encountered error while creating new KfApp kf-poc1:  (kubeflow.error): Code 500 with message: Could not load https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.1.yaml. Error:  (kubeflow.error): Code 400 with message: invalid config: apiVersion is not found

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 1.0.0
- kfctl version: (use `kfctl version`): kfctl v1.0.1-0-gf3edb9b
- Kubernetes platform: (e.g. `minikube`) : onPrem
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by krishnadurai** [comment]
@lalithvaka I tried the upgrade flow and wasn't able to reproduce the same issue.

In case you are looking for stable version releases your config URIs should be pointing at v1.0-branch configs. Here's my config for reference:

```
apiVersion: kfupgrade.apps.kubeflow.org/v1alpha1
kind: KfUpgrade
metadata:
  name: kf-upgrade-v1.0.1
spec:
  currentKfDef:
    name: kubeflow-app
    version: v1.0.0
  newKfDef:
    name: kubeflow-app
    version: v1.0.1
  # Replace this with the path to the KfDef that you are upgrading to
  baseConfigPath: https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.1.yaml
```

Let me know in case if I've missed anything.
