### ISSUE TITLE
Securing Your Clusters - kfctl apply fails due to Seldon Component

### ISSUE THREAD

**Issue by anifort** [kubeflow/kubeflow#4932]
https://www.kubeflow.org/docs/gke/private-clusters/

Following the instructions to setup a private cluster on Google Cloud GKE, I reached the point of kfctl apply were i get the following error:

failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error [unable to recognize "/tmp/kout242652420": no matches for kind "Certificate" in version "cer
t-manager.io/v1alpha2", unable to recognize "/tmp/kout242652420": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"]

**Comment by jlewi** [comment]
As a work around you could try removing seldon from your KFDef to skip installing seldon.

Do you have cert manager installed in your cluster?

**Comment by joepeskett** [comment]
For our deployment of Kubeflow onto a private GKE cluster, we had to remove certmanager and seldon components.

**Comment by jlewi** [comment]
@joepeskett How does the firewall issues relate to this particular issue?

I think this issue might have nothing to do with private GKE. I suspect this is the same issue as kubeflow/manifests#1121 and is due to a race condition in which end up trying to create cert-manager resources before cert-manager is fully ready.

Duplicate of kubeflow/manifests/issues/1121

**Comment by jlewi** [comment]
Duplicate of kubeflow/manifests/issues/1121

**Comment by jlewi** [comment]
I stand corrected looks like cert-manager might have specific issues related to private GKE.
https://docs.cert-manager.io/en/release-0.11/getting-started/webhook.html#running-on-private-gke-clusters

Although I think firewall rules blocking the webhook will manifest as errors like the following

```
Error from server (InternalError): error when creating ".build/kubeflow-apps/cert-manager.io_v1alpha2_certificate_admission-webhook-cert.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request
```

I think the original error might have been different and might have been the race condition I indicated above.

**Comment by jlewi** [comment]
Looks like adding a firewall rule like the one below fixed this.

```
# Per https://docs.cert-manager.io/en/release-0.11/getting-started/webhook.html#running-on-private-gke-clusters
# We need an extra firewall rule to allow certmanager webhooks.
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: kfname-cm # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
spec:
  description: "Allow traffic to cert manager webhook"
  allow:
  - protocol: tcp
    ports:    
    - "443"
    - "6443"
  sourceRanges:
  - 172.16.0.32/28
  direction: INGRESS
  networkRef:
    name: kfname # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"kfname"}}}
  # Enable logging to help debugging
  enableLogging: false # {"type":"bool","x-kustomize":{"setter":{"name":"log-firewalls","value":"false"}}}
```

This will be part of the blueprint see: https://github.com/kubeflow/gcp-blueprints/issues/33
