### ISSUE TITLE
Question regarding creating profiles

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4938]
/kind question

**Question:**
When a user first logs into Kubeflow, they are requested to create a profile.  After a profile is created, the Manage Contributors page looks like the below;
![Screen Shot 2020-04-09 at 1 33 38 PM](https://user-images.githubusercontent.com/6708730/78933811-7fa99480-7a6f-11ea-9e41-671102e85e18.png)
Users can then add contributors to this profile.

If a new profile is created with the same owner using this yaml;
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: crd-risk-mgnt
spec:
  owner:
    kind: User
    name: admin@kubeflow.org
```
Manage Contributors looks like;
![Screen Shot 2020-04-09 at 1 34 18 PM](https://user-images.githubusercontent.com/6708730/78934031-d7480000-7a6f-11ea-9126-296f35f33cbc.png)

Contributors can no longer be added to the ds-era profile.  
Is this expected behavior?  It seems like a bug to me.

Likewise, a third profile is created for this user;
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: quant-01
spec:
  owner:
    kind: User
    name: admin@kubeflow.org
```

Manage Contributors looks like;
![Screen Shot 2020-04-09 at 2 53 49 PM](https://user-images.githubusercontent.com/6708730/78935221-f47dce00-7a71-11ea-88eb-b412ce9e3060.png)

In this scenario, neither ds-era nor the newly create quant-01 profile can have contributors added.
