### ISSUE TITLE
Authentication for kubeflow dashboard not working

### ISSUE THREAD

**Issue by paulcarlton-ww** [kubeflow/kubeflow#5006]
/kind bug

**What steps did you take and what happened:**
I installed kubeflow on an AWS EKS cluster using instructions at https://www.kubeflow.org/docs/aws/, I've tried specifying basic auth and cognito without success, I get no login prompt when I point browser at the url.

**What did you expect to happen:**

A login screen

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

My config for basic auth
```yaml
auth:
        basicAuth:
          password:
            name: password
          username: admin
```
for cognito I used
```yaml
plugins:
  - kind: KfAwsPlugin
    metadata:
      creationTimestamp: null
      name: aws
    spec:
      auth:
        cognito:
          certArn: arn:aws:acm:eu-west-1:xxx:certificate/xxx
          cognitoAppClientId: xxx
          cognitoUserPoolArn: arn:aws:cognito-idp:eu-west-1:xxxx:userpool/eu-west-1_xxxx
          cognitoUserPoolDomain: kubeflow.pc.weaveworks-cx.com
      enablePodIamPolicy: true
      region: us-west-1
```

**Environment:**

- kubeflow version: v0.0.2
- kfctl version: fctl v1.0.2-0-ga476281
- Kubernetes platform: aws eks
- Kubernetes version: 
ate:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- OS:
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
