### ISSUE TITLE
Global PodDefault definitions

### ISSUE THREAD

**Issue by ettiee** [kubeflow/kubeflow#5018]
/kind question

**Question:**
[You can ask any question about this project.]
Hi, is it possible to create global PodDefault resources? We want to define PodDefaults to apply to all users (so for all new namespaces)

**Comment by yanniszark** [comment]
Hi @ettiee !
This was discussed before in this issue: https://github.com/kubeflow/kubeflow/issues/4215
A couple of solutions were proposed, ranging from more generic to more specific.
I recall @jlewi 's proposal was to introduce `ClusterPodDefaults` in the image of `Roles`/`ClusterRoles`.
IMO that's a good way to move forward on this.
Personally I don't have the cycles for the implementation, but would be glad to help review changes if someone decides to take it on.

**Comment by ettiee** [comment]
@yanniszark thanks for the linked issue 👍 
We're collecting some feature wish lists and might have a go at implementing this on a hack day soon !

**Comment by abdulsalama** [comment]
@ettiee would it allow for parameterization based on the profile name (and/or the owner). For example, in my case, I want to attach a volume by default, but the subpath will be different for each profile. Like this:

```
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-efs-mounts
  namespace: profile1
spec:
  selector:
    matchLabels:
      add-clnb-efs-mounts: "true"
  desc: "Add EFS mount"
  volumeMounts:
  - name: efs-folder
    mountPath: /opt/{profile-name}
    subPath: "home/{profile-name}"
  volumes:
  - name: efs-folder
    nfs:
      path: /
      server: fs-foo.efs.amazonaws.com 
```
So the PodDefault for profile1 will mount subpath home/profile1 and PodDefault for profile2 will mount subpath home/profile2, and so on...
