### ISSUE TITLE
How manage contributors via kubectl/kfctl 

### ISSUE THREAD

**Issue by Ventals** [kubeflow/kubeflow#5028]
/kind question

**Question:**
How I can manage Contributors via code(kubectl or kfctl)? It's a very useful feature for production usage, but as I see it doesn't implement yet.

Some results of my research - when we add contributors via UI it was creating ServiceRoleBinding, for each contributors:

```
> kubectl get ServiceRoleBinding -n test
NAME                                                  REFERENCE         AGE
owner-binding-istio                                   ns-access-istio   21m
user-test-name-gmail-com-clusterrole-edit             ns-access-istio   20m
```

`owner-binding-istio` default, with info about NS owner. 
`user-test-name-gmail-com-clusterrole-edit` generated ServiceRoleBinding via UI

I try to create new ServiceRoleBinding using the following config:
```
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  annotations:
    role: edit
    user: test.newacc@gmail.com
  name: user-test-newacc-gmail-com-clusterrole-edit
  namespace: test
spec:
  roleRef:
    kind: ServiceRole
    name: ns-access-istio
  subjects:
  - properties:
      request.headers[kubeflow-userid]: test.newacc@gmail.com
```

But after apply I can't see my new account in contributors UI, and can't access it

Maybe I miss some part of the configuration?

**Comment by fakeburst** [comment]
You also need to create a RoleBinding resource for this new user 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: edit
    user: test.newacc@gmail.com
  name: user-test-newacc-gmail-com-clusterrole-edit
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: test.newacc@gmail.com
```
