### ISSUE TITLE
“If you're seeing this Grafana has failed to load its application files” Error Grafana

### ISSUE THREAD

**Issue by Ventals** [kubeflow/kubeflow#5051]
/kind bug

**What steps did you take and what happened:**
Just open a Grafana dashboard by path - **/istio/grafana/** and catch error
```
If you're seeing this Grafana has failed to load its application files
```

**What did you expect to happen:**
Opens Grafana dashboards

**Anything else you would like to add:**
We can fix this by editing **grafana.ini** file

Steps
- **kfctl build**
- Go to **istio-install/base/istio-noauth.yaml** file
- On grafana config we must edit
```
    domain = kubeflow.your.domain
    root_url = https://kubeflow.your.domain/istio/grafana/
    serve_from_sub_path = true
```
- Create **configMap** with grafana config
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-grafana-config-ini
  labels:
    app: grafana
    chart: grafana
    heritage: Tiller
    release: istio
    istio: grafana
data:
  grafana.ini: |-
    #####################Full Grafana Configuration Example #####################
    
---
```
- Found Grafana deployment (**# Source: istio/charts/grafana/templates/deployment.yaml**) and add **volume** 
```
volumes:
      - name: grafana-configuration-ini
        configMap:
          name:  istio-grafana-config-ini
```
and **volumeMounts** 
```
volumeMounts:
- name: grafana-configuration-ini
   mountPath: "/etc/grafana/grafana.ini"
   subPath: grafana.ini
   readOnly: true
```
- **kfctl apply**

**Environment:**
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0.2
- kfctl version: kfctl v1.0.1-0-gf3edb9b
- Kubernetes platform: AWS
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- OS: MacOS
