### ISSUE TITLE
Adding new Node Pool causes UI to be temporarily unavailable

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/kubeflow#5122]
/kind bug

**What steps did you take and what happened:**
When updating the generated Deployment Manager config (in the `gcp_config/cluster.jinja`) to add a new Node Pool resource and then running `kfctl apply`, the node pool is successfully added but the UI becomes inaccessible for anywhere between 5-15 minutes and constantly returns a 401 "Origin Authentication Failed." error message in the browser. 

Edit: This does not happen if I add a node pool manually. Does this mean this issue could have something to do with the Deployment Manager configuration? 

**What did you expect to happen:**
The UI should still be accessible when adding new node pools that don't affect the base pool that the UI/API Pods are scheduled on.

**Anything else you would like to add:**
- The KFP API still works as well as kubectl commands
- An example of an additional node pool configuration we would add looks like this: 

```yaml
- name: {{ HIGH_MEM_POOL }}
  type: gcp-types/container-v1beta1:projects.locations.clusters.nodePools
  properties:
    parent: projects/{{ env['project'] }}/locations/{{ properties['zone'] }}/clusters/{{ CLUSTER_NAME }}
    project: {{ properties['securityConfig']['project'] }}
    zone: {{ properties['zone'] }}
    clusterId: {{ CLUSTER_NAME }}
    nodePool:
      name: high-mem-pool
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 0
        maxNodeCount: 10
      config:
        machineType: n1-highmem-8
        serviceAccount: {{ KF_VM_SA_NAME }}@{{ env['project'] }}.iam.gserviceaccount.com
        oauthScopes: {{ VM_OAUTH_SCOPES }}
  metadata:
    dependsOn: 
    - {{ CLUSTER_NAME }}
```
The above is appended to the end of the `cluster.jinja` file and no modifications are made to any of the base cluster or node pool resources that come in the default configuration. 

**Environment:**

- Kubeflow version: 1.0.2  
- kfctl version: (use `kfctl version`): 1.0.2
- Kubernetes platform: (e.g. `minikube`) GCP 
- Kubernetes version: (use `kubectl version`): 1.16 
- OS (e.g. from `/etc/os-release`): dev_local but using 1.0.2 manifests
