### ISSUE TITLE
Notebook culling not working with Istio and RBAC

### ISSUE THREAD

**Issue by zachomedia** [kubeflow/kubeflow#5128]
/kind bug

**What steps did you take and what happened:**

We deployed Kubeflow with Istio and Istio RBAC (w/ OIDC) enabled and we were looking to use Notebook culling to cull idle notebooks after a period of time. I should also note that we have mTLS enabled on our Istio config.

Notebook culling is not functional due to multiple issues:

* Notebook controller is not on the service mesh, so fails the mTLS check when talking to notebooks

```
2020-07-13T21:11:51.792Z	INFO	culler	Error talking to http://construction-starts.ns.svc.cluster.local/notebook/dsd/construction-starts/api/status	{"error": "Get http://construction-starts.dsd.svc.cluster.local/notebook/dsd/construction-starts/api/status: read tcp 172.21.XX.YY:36004->10.0.XX.YY:80: read: connection reset by peer"}
```

* If we enable injection on the notebook controller, it is not in the ServiceRoleBinding list, so it fails the Istio RBAC check and gets permission denied

We started going down the road of enable istio-injection on the Kubeflow control plane, but this is introduced a bunch of problems. These were the initial steps we tried:

1. Add istio-injection=enabled label to kubeflow namespace
2. Rollout restart all deployments / statefulsets
3. Adding annotation to disable injection on the admission webhook and metadata-envoy-deployment
4. Delete the DestinationRule for the namespace 
5. On the svc for ml-pipeline, change http service name to tcp-http

Things generally worked (after disabling injection on a couple of services), but there were random errors using Kubeflow and we didn't know of what other impacts to functionality there were. We also didn't like diverging that much from the direction of Kubeflow (https://github.com/kubeflow/manifests/pull/712).

**What did you expect to happen:**

Notebook culling should function correctly with Istio and Istio RBAC enabled.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This was also mentioned in https://github.com/kubeflow/kubeflow/pull/3856#issuecomment-612295807.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0.2
- kfctl version: (use `kfctl version`): 1.0.2
- Kubernetes platform: (e.g. `minikube`) AKS
- Kubernetes version: (use `kubectl version`): 1.15.7
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04
- Istio: 1.4.9

**Comment by sylus** [comment]
Possible to get feedback on this as is a crucial detail and useful for cost management for us :D

**Comment by jcooklin** [comment]
Where is this with respect to KF 1.2? #5371

**Comment by Jeffwan** [comment]
@jcooklin I think this may not come to 1.2.0 If this is critical to user. It would be great to get changes ready and we can patch into 1.2.1 patch release

**Comment by LEDfan** [comment]
We faced this issue in a Kubeflow deployment and found a workaround. The idea is to create an Istio `AuthorizationPolicy`, which allows any traffic to the `/api/status` endpoint of the notebook servers. Therefore any pod in the cluster an access the `/api/status` endpoint (also non-istio enabled pods), however, from security POV I believe it's okay to take this risk. Only very limited metadata is of the notebook server is available. Nevertheless, it's possible to create Kubernetes network policies in order to limit the traffic to the notebook servers (e.g. only allow the traffic from the kubeflow namespace).

Here is the `AuthorizationPolicy`:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-policy-notebooks
  namespace: tdekoninck
spec:
  action: ALLOW
  # Note: the notebook pods do not have a general label to identify them as such, therefore we don't have a selector here.
  # Fortunately the endpoint is specific enough so that this should not cause any security issue.
  rules:
   - to:
     - operation:
        methods: ["GET"]
        paths: ["*/api/status"] # wildcard for the name of the notebook server 
```

For reference here is the patch we used for the configuration of the notebook-controller deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-controller-deployment
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: ENABLE_CULLING
          value: "true"
        - name: IDLE_TIME
          value: "1" # 1 minute for testing, use something else in production
        - name: CULLING_CHECK_PERIOD
          value: "1"
```

I hope someday we have an proper, official solution. In the meantime I think this is a feasible workaround.

**Comment by kimwnasptd** [comment]
Hi @LEDfan, your proposed is indeed the way to fix this for now!

I would suggest though that we limit the source of the `AuthorizationPolicy` to just allow the Notebooks controller to access the `/api/status` of each Notebook and not everyone https://istio.io/latest/docs/reference/config/security/authorization-policy/.

This can be part of the [current manifests](https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller/config/overlays/kubeflow) we have for deploying the Controller.
@yanniszark WDYT?

**Comment by LEDfan** [comment]
Hi @kimwnasptd 

Does that mean you will enable the istio-sidecar on the notebooks controller? I don't think we will be able to limit the traffic without having mutual LTS between the notebook servers and the notebook controller. All relevant fields here https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source require mutualLTS. But maybe I'm missing something?

**Comment by kimwnasptd** [comment]
> Does that mean you will enable the istio-sidecar on the notebooks controller? 
> All relevant fields here https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source require mutualLTS. But maybe I'm missing something?

@LEDfan you are spot on! We will need to explicitly allow the sidecar injection in the Notebooks Controller. This should be done here https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/config/manager/manager.yaml#L19. 

Also note that the Profiles controller adds the `istio-injection: "true"` label in every Namespace it creates [[source](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/controllers/profile_controller.go#L127-L136)], so the Notebooks should have a sidecar by default.

Lastly we will need to use the following `AuthorizationPolicy` to allow the Controller to speak to the Notebooks [iteration from the YAML you provided]:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: notebooks-controller-culling
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/kubeflow/sa/notebook-controller-service-account"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["*/api/status"] # wildcard for the name of the notebook server
```

@LEDfan would you like a PR for this?
