### ISSUE TITLE
"Permission denied" - authorization issue on AWS / OIDC

### ISSUE THREAD

**Issue by ykeuter** [kubeflow/kubeflow#5129]
/kind question

**Question:**
I am trying to get authorization to work on AWS (with OIDC). I followed the configuration as in https://www.kubeflow.org/docs/aws/authentication-oidc/ using kfctl_aws_cognito.v1.0.2.yaml (and v1.0-branch). My spec looks like this:
```
spec:
      auth:
        oidc:
          certArn: <certificat arn>
          oAuthClientId: <client id>
          oAuthClientSecret: <client secret>
          oidcAuthorizationEndpoint: https://<oidc>/connect/authorize
          oidcIssuer: https://<oidc>
          oidcTokenEndpoint: https://<oidc>/connect/token
          oidcUserInfoEndpoint: https://<oidc>/connect/userinfo
      region: eu-north-1
      addons:
      - fluentd-cloud-watch
      roles:
      - data-science-kubeflow-worker-role
```
The authentication part seems to be working correctly, but I get this message when calling the ALB hostname:
`PERMISSION_DENIED:authzadaptor-handler.handler.istio-system:`
What am I missing?
