### ISSUE TITLE
Jupyter web app ignores storageClass provided in spawner_ui_config

### ISSUE THREAD

**Issue by fakeburst** [kubeflow/kubeflow#5133]
/kind bug

**What steps did you take and what happened:**
I've modified `spawner_ui_config.yaml` to use `aws-efs` as a storageClass for the notebook server workspace volume:
```yaml
          class:
            # The StrageClass the PVC will use if type is New. Special values are:
            # {none}: default StorageClass
            # {empty}: empty string ""
            value: aws-efs
```
But the pvc created from the UI is of claster's default storagaClass 

**What did you expect to happen:**
The pvc created with the notebook server to be of the storageClass provided in `spawner_ui_config.yaml`

**Anything else you would like to add:**
This is a snippet from jupyter-web-app logs
```logs
2020-07-14 18:28:27,474 | kubeflow_jupyter.common.utils | INFO | Sending config file '/etc/config/spawner_ui_config.yaml'
2020-07-14 18:28:27,484 | kubeflow_jupyter.default.app | INFO | Got Notebook: {'name': 'efs', 'namespace': 'efs', 'image': 'gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0', 'customImage': '', 'customImageCheck': False, 'cpu': '0.5', 'memory': '1.0Gi', 'gpus': {'num': 'none'}, 'noWorkspace': False, 'workspace': {'type': 'New', 'name': 'workspace-efs', 'templatedName': 'workspace-{notebook-name}', 'size': '10Gi', 'mode': 'ReadWriteMany', 'class': '{none}', 'extraFields': {}}, 'datavols': [], 'shm': False, 'configurations': []}
```
Here you can see that `'class' is '{none}'` although it is set to aws-efs in the config file loaded

**Environment:**

- Kubeflow version: 1.0.2
- kfctl version: (use `kfctl version`): kfctl v1.0.2-0-ga476281
- Kubernetes platform: (e.g. `minikube`): EKS
- Kubernetes version: (use `kubectl version`): Client Version: 1.18; Server Version: 1.14+
- OS (e.g. from `/etc/os-release`):
