### ISSUE TITLE
Manually adding a Kubeflow Cluster-Admin

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kubeflow#5144]
/kind feature

**Why you need this feature:**
I am getting requests from users to elevate their profiles to that of "cluster-admins", specifically in order to be able to act as a administrator within the Kubeflow Dashboard. This seems to suggest that the functionality is available (at least for deployments on GCP) and by default the cluster creator also becomes an admin:

https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/

However, I cannot find any clear documentation on how to manually make a user a cluster admin. We are running on AWS where rolling out the cluster results in an IAM user becoming kubernetes cluster admin, so there isn't a direct link to a user such as "karl.schriek@alexanderthamm.com" as is the case on GCP. Additional "cluster-admins" can be added on IAM user level, but I am not sure if a mapping to a Kubeflow profile is even possible.

At least the following clusterrolebinding does not appear to have the desired effect

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: karl.schriek@alexanderthamm.com
```

**Describe the solution you'd like:**
- Map IAM User to a KF Profile (or some alternative method to grant cluster-admin access)
- First user to connect to Central Dashboard becomes cluster admin by default (For AWS at least, this would be useful)
- Clear documentation on how to elevate a user to cluster admin via kubectl
- Ability to elevate other users to cluster admin from within the central dashboard.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
