### ISSUE TITLE
[notebook controller] A validation webhook should be added to notebook controller in order to validate custom resource

### ISSUE THREAD

**Issue by MartinForReal** [kubeflow/kubeflow#5152]
/kind feature
**Why you need this feature:**
The cr resource is not validated and the user may fail to create notebook instance because of typos in spec.

**Describe the solution you'd like:**
A validation webhook should be added to notebook controller

**Comment by MartinForReal** [comment]
related: #5020

**Comment by axelgobletbdr** [comment]
Hi @MartinForReal, we stumbled upon an issue related to this one: when creating a notebook in the UI with wrong resource specs (e.g. "1 Gi" memory), the notebook-controller crashes because it is unable to read the notebook resource.

Your proposed solution can solve this issue as well. Did you already start working on this feature?

**Comment by MartinForReal** [comment]
@axelgobletbdr this issue depends on #5197. FYI

**Comment by axelgobletbdr** [comment]
@MartinForReal I dont understand how these Issues are related. Can you elaborate?

Furthermore, many misconfigurations could potentially be fixed using OpenApi V3 validation: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation
It would work for the memory issue for sure. Would it solve your problems as well?

**Comment by MartinForReal** [comment]
@axelgobletbdr From my point of view, schema validation problem, configuration for Prometheus and cert-manager, and other issues have been handled by the newer version of kubebuilder. So I regenerated the notebook-controller project using v2 kubebuilder and the result shows that newly generated project has a dependency on controller-runtime 0.4.0 or later. So I think it is a good idea to update dependencies first and adopt the kubebuilder v2 later.

**Comment by axelgobletbdr** [comment]
@MartinForReal posting your PR into the kubeflow slack channel has helped me getting it merged quickly in the past.

**Comment by MartinForReal** [comment]
I agree. But the point is nobody actually owns notebook controller.

**Comment by axelgobletbdr** [comment]
I solved my problem by adding an overlay to the notebook CRD in kubeflow/manifests:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: notebooks.kubeflow.org
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            template:
              properties:
                spec:
                  properties:
                    containers:
                      items:
                        properties:
                          resources:
                            properties:
                              limits:
                                properties:
                                  memory:
                                    type: string
                                    pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                                  cpu:
                                    type: string
                                    pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                                type: object
                              requests:
                                properties:
                                  memory:
                                    type: string
                                    pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                                  cpu:
                                    type: string
                                    pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                                type: object
                            type: object
                        type: object
                      type: array
```

This prevents misconfiguration of cpu and memory requests and limits. I still do not fully understand how the notebook-controller update will help here. If it does and when it is merged, I can always remove this patch from kubeflow/manifests.
