### ISSUE TITLE
[GCP] Missing VPC-Native creation options/documentation

### ISSUE THREAD

**Issue by krish0005** [kubeflow/kubeflow#5161]
Hi,

Shared-VPCs are unsafe. You cannot have Anti Spoofing feature without IpAlias.
I'm trying to deploy Kubeflow on a GKE in VPC-Native mode with the following configuration but i'm not able to have it deployed with resulting Alias IP / VPC-Native Flag enabled in GKE (as seen from Google Cloud Console).
Can you please add in the documentation the instructions needed ?
Can you explain what is wrong in my configuration and how to deploy Kubeflow in VPC-Native mode ?

```
imports:
- path: cluster.jinja
resources:
- name: kubeflow
  properties:
    autoprovisioning-config:
      enabled: true
      max-accelerator:
      - count: 16
        type: nvidia-tesla-k80
      max-cpu: 128
      max-memory: 2000
    cluster-version: "1.14"
    cpu-pool-enable-autoscaling: true
    cpu-pool-initialNodeCount: 2
    cpu-pool-machine-type: n1-standard-8
    cpu-pool-max-nodes: 10
    cpu-pool-min-nodes: 0
    enable-workload-identity: true
    enable_tpu: false
    gkeApiVersion: v1beta1
    gpu-number-per-node: 1
    gpu-pool-enable-autoscaling: true
    gpu-pool-initialNodeCount: 0
    gpu-pool-machine-type: n1-standard-8
    gpu-pool-max-nodes: 10
    gpu-pool-min-nodes: 0
    gpu-type: nvidia-tesla-k80
    identity-namespace: XXXXXX
    ipName: XXXXXX
    pool-version: v1
    ipAllocationPolicy:
      useIpAliases: true
      createSubnetwork: false
      subnetworkName: XXXXXX
      clusterIpv4CidrBlock:
      servicesIpv4CidrBlock:
    securityConfig:
      masterAuthorizedNetworksConfigCidr:
      - cidrBlock: 1.2.3.4/32
      masterAuthorizedNetworksConfigEnabled: false
      masterIpv4CidrBlock: 172.16.0.16/28
      podSecurityPolicy: false
      privatecluster: false
      secureNodeMetadata: false
    users:
    - XXXXXX
    zone: europe-west1-b
  type: cluster.jinja
```

Reference GCP docs:
https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#api

Note i have a VPC Network + Subnet already present and to be able to use them i had to set at least in cluster-kubeflow-yaml :

```
    ipAllocationPolicy:
      useIpAliases: true
      createSubnetwork: false
      subnetworkName: XXXXXX
```

I would like to test this (shall i execute kfctl generate again after changing .jinja? or am i supposed only to modify cluster-kubeflow.yaml ?

```
    cluster:
      name: {{ CLUSTER_NAME }}
      network: projects/acn-cpaascgp/global/networks/aip-kubeflow
      subnetwork: projects/acn-cpaascgp/regions/europe-west1/subnetworks/aip-kubeflow
      initialClusterVersion: "{{ properties['cluster-version'] }}"
```

I'm using kfctl apply -V -f kfctl_gcp_iap.v1.0.2.yaml

I added also the following hoping to trigger IpAlias being true but still it's not :

 ```
clusterIpv4CidrBlock:
servicesIpv4CidrBlock:

```

See reference GCP docs, both fields should be at least present even if blank (GKE managed subnets) but they don't affect the resulting GKE deployed by KFCTL/Deployment Manager:

https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#api
"If left blank, a valid range is found and created with a default size."

Lastly: kfctl_gcp_iap.v1.0.2.yaml does not contain any variable to address any of the above settings.

Thanks
Regards
