### ISSUE TITLE
Plugin not recgonized: AwsIamForServiceAccount

### ISSUE THREAD

**Issue by apryiomka** [kubeflow/kubeflow#5186]
/kind bug

With profile controller spec like so in EKS:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kustomize.component: profiles
  name: profiles-deployment
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      kustomize.component: profiles
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        kustomize.component: profiles
    spec:
      containers:
      - args: null
        command:
        - /manager
        - -userid-header
        - $(USERID_HEADER)
        - -userid-prefix
        - $(USERID_PREFIX)
        - -workload-identity
        - $(WORKLOAD_IDENTITY)
        env:
        - name: USERID_HEADER
          valueFrom:
            configMapKeyRef:
              key: userid-header
              name: kubeflow-config
        - name: USERID_PREFIX
          valueFrom:
            configMapKeyRef:
              key: userid-prefix
              name: kubeflow-config
        - name: WORKLOAD_IDENTITY
          valueFrom:
            configMapKeyRef:
              key: gcp-sa
              name: profiles-profiles-config-4mgcmtgk6t
        image: gcr.io/kubeflow-images-public/profile-controller:vmaster-g34aa47c2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        name: manager
        ports:
        - containerPort: 8080
          name: manager-http
          protocol: TCP
      - args: null
        command:
        - /access-management
        - -cluster-admin
        - $(CLUSTER_ADMIN)
        - -userid-prefix
        - $(USERID_PREFIX)
        env:
        - name: USERID_HEADER
          valueFrom:
            configMapKeyRef:
              key: userid-header
              name: kubeflow-config
        - name: USERID_PREFIX
          valueFrom:
            configMapKeyRef:
              key: userid-prefix
              name: kubeflow-config
        - name: CLUSTER_ADMIN
          valueFrom:
            configMapKeyRef:
              key: admin
              name: profiles-profiles-config-4mgcmtgk6t
        image: gcr.io/kubeflow-images-public/kfam:vmaster-gf3e09203
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        name: kfam
        ports:
        - containerPort: 8081
          name: kfam-http
          protocol: TCP
      serviceAccountName: profiles-controller-service-account
```

the profile controller is deployed successfully. OIDC service is enabled, SA to IAM works. When we try to create a profile like so:

```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: profile
spec:
  owner:
    kind: User
    name: me@examle.com
  plugins:
  - kind: AwsIamForServiceAccount
    spec:
      awsIamRole: arn:aws:iam::0000000000000000:role/pod-role-1
  resourceQuotaSpec: {}
```

the `default-editor` service account is created without IAM role annotation:

```
apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default-editor
    namespace: profile
  secrets:
  - name: default-editor-token-tnl48
```
Expected:

```
apiVersion: v1
  kind: ServiceAccount
  metadata:
      annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::0000000000000000:role/pod-role-1
    name: default-editor
    namespace: profile
  secrets:
  - name: default-editor-token-tnl48
```

After evaluating the `profile-deployment` log, found this:

```
2020-08-04T19:45:54.070Z	INFO	controllers.Profile	Plugin not recgonized: 	{"profile": "profile", "Kind": "AwsIamForServiceAccount"}
```
