### ISSUE TITLE
`kf-resource-quota` Resource Quota is not being removed from the namespace after removing it from profile spec and re-applying

### ISSUE THREAD

**Issue by abdulsalama** [kubeflow/kubeflow#5191]
/kind bug

**What steps did you take and what happened:**
Profile controller does NOT do garbage collection for resource quota. 

Repro steps:
- Create a profile specifying resource quota:
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: foo
spec:
  owner:
    kind: User
    name: foo@foo.com
  plugins:
  - kind: AwsIamForServiceAccount
    spec:
      awsIamRole: arn:aws:iam::foo:role/bar-role
  resourceQuotaSpec:
    hard:
      requests.cpu: "5"
      requests.memory: 16Gi
      limits.cpu: "10"
      limits.memory: 32Gi
      requests.nvidia.com/gpu: "1"
```
- Reconfigure the profile without any resource quota specifications:
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: foo
spec:
  owner:
    kind: User
    name: foo@foo.com
  plugins:
  - kind: AwsIamForServiceAccount
    spec:
      awsIamRole: arn:aws:iam::foo:role/bar-role
  resourceQuotaSpec: {}
```

- However, resource quota from before is still being enforced. I expected it not to be enforced anymore.

**What did you expect to happen:**
Resource quota should NOT be enforced any more after removing it from profile spec and re-applying.

**Anything else you would like to add:**
N/A

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): V1.1

- Profile-controller spec:
image: gcr.io/kubeflow-images-public/profile-controller:vmaster-g34aa47c2

- Kubernetes platform: EKS
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-fd1ea7", GitCommit:"fd1ea7c64d0e3ccbf04b124431c659f65330562a", GitTreeState:"clean", BuildDate:"2020-05-28T19:06:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
Debian GNU/Linux 9
