### ISSUE TITLE
Profile label not propagated to Namespace

### ISSUE THREAD

**Issue by TomasPihrt** [kubeflow/kubeflow#5207]
When manually creating a `profile` [referring the docs: manual-profile-creation](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#manual-profile-creation) that contains the `app.kubernetes.io/part-of: kubeflow-profile` label, the label is not further propagated to the linked `namespace`.

**Features affected by this behaviour:**
- Notebook Server Configuration - `PodDefault` is not injected into the pod definition when creating a Notebook Server

**Profile definition:**
```yaml
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: profileName   # replace with the name of profile you want, this will be user's namespace name
  labels:
    app.kubernetes.io/part-of: kubeflow-profile
spec:
  owner:
    kind: User
    name: userid@email.com   # replace with the email of the user
```

**Resulting namespace definition:**
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    owner: profileName
  labels:
    istio-injection: enabled
    katib-metricscollector-injection: enabled
    serving.kubeflow.org/inferenceservice: enabled
  name: profileName
spec:
  finalizers:
  - kubernetes
```

**Awaited namespace definition:**
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    owner: profileName
  labels:
    istio-injection: enabled
    katib-metricscollector-injection: enabled
    serving.kubeflow.org/inferenceservice: enabled
    app.kubernetes.io/part-of: kubeflow-profile # missing label
  name: profileName
spec:
  finalizers:
  - kubernetes
```

**Temporary fix**
To get the `PodDefault` working it's necessary to patch the namespace definition so that the label is applied.
```bash
kubectl patch namespace/$namespace --type merge \
  -p '{"metadata": {"labels": {"app.kubernetes.io/part-of": "kubeflow-profile"}}}'
```

Please could you update the Profile CRD and [documentation page](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/)?
