### ISSUE TITLE
NodeSelector for Jupyter UI and notebooks

### ISSUE THREAD

**Issue by achandras** [kubeflow/kubeflow#5235]
/kind question

I am deploying kubeflow 1.0.2, and the default `spawner-ui-config.yaml` didn't have any indication of where to set node selectors.

I would like the notebook server and notebooks to run on a specifically labeled set of nodes, so any ideas on how to accomplish this would be appreciated

**Comment by MartinForReal** [comment]
```
kind: Notebook
apiVersion: kubeflow.org/v1alpha1
metadata:
  labels:
    app: test
  name: test
  namespace: test
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: resource_type
                    operator: In
                    values:
                      - lycc-p40
      containers:
        - image: 'yourimage'
          imagePullPolicy: Always
          name: test
          resources:
            limits:
              cpu: '8'
              memory: 48Gi
              nvidia.com/gpu: 1
            requests:
              cpu: '8'
              memory: 48Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      hostIPC: true
      hostPID: true
      imagePullPolicy: Always
      initContainers:
          image: 'yourimage'
          name: init-myservice
      securityContext:
        fsGroup: 2000
      serviceAccountName: default-editor
      nodeSelector:
         test: a
      tolerations:
        - effect: NoSchedule
          key: allow-gpu
          operator: Exists
      ttlSecondsAfterFinished: 300
      volumes:
        - name: prophet-tutorial
          persistentVolumeClaim:
            claimName: tutorial
            readOnly: true
        - emptyDir:
            sizeLimit: 2000Gi
          name: cachevol
        - emptyDir:
            medium: Memory
          name: dshm
```

FYI
