### ISSUE TITLE
Azure KeyVault new CSI volume driver doesn't work

### ISSUE THREAD

**Issue by Shaked** [kubeflow/kubeflow#5315]
/kind bug

**What steps did you take and what happened:**

- Install https://github.com/Azure/secrets-store-csi-driver-provider-azure

```
$ helm repo add secrets-store-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
$ helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver
```

- [Create an Azure KeyVault](https://docs.microsoft.com/azure/key-vault/secrets/quick-create-portal)
- [Create your own SecretProviderClass Object](https://github.com/Azure/secrets-store-csi-driver-provider-azure#create-your-own-secretproviderclass-object)
- Create a new `PodDefault`: 

```
NAME=shaked
NAMESPACE=kubeflow-klein-shaked; 
<<EOF | kubectl -n $NAMESPACE apply -f -
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: azure-keyvault-v2
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      azure-keyvault-v2: "true"
  desc: "add azure keyvault v2"
  env:
    - name: WHO_AM_I
      value: $NAME
  volumeMounts:
    - name: secrets-store-inline
      mountPath: /secrets
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-jupyter-default"
        nodePublishSecretRef: 
          name: kvcreds
EOF
```

- Create a new notebook with the above PodDefault

**What did you expect to happen:**

When running a `kubectl describe pod <pod>`, I'd expect to see:

```
Volumes:
  secrets-store-inline:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=azure-jupyter-default
```

However, I only see:

```
  secrets-store-inline:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
```

**Anything else you would like to add:**

- The CSI driver works with a manually crafted pod: 

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: test-shaked
spec:
  containers:
    - name: test-shaked
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: secrets-store-inline
          mountPath: /test
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-jupyter-default"
        nodePublishSecretRef: 
          name: kvcreds
EOF
```

```
$ kubectl describe pod test-shaked | grep -i volumes -A 6

Volumes:
  secrets-store-inline:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=azure-jupyter-default
```

- Using the [old version of Azure KeyVault plugin](https://github.com/Azure/kubernetes-keyvault-flexvol), which is now deprecated, seems to works properly: 

```
NAMESPACE=<YOUR USER NAMESPACE>; 
NAME=<YOUR USER>
AKV_TENANT_ID=<TENANT_ID>>;\
AKV_NAME=<AKV_NAME>;\
AKV_ALIASES="secrets.json";\
AKV_OBJECTS="a-secret-object";\
<<EOF | kubectl -n $NAMESPACE apply -f -
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: azure-keyvault
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      azure-keyvault: "true"
  desc: "add azure keyvault"
  env:
    - name: WHO_AM_I
      value: $NAME
  volumeMounts:
    - name: secret-volume
      mountPath: /secrets
  volumes:
    - name: secret-volume
      flexVolume:
        driver: "azure/kv"
        secretRef:
          name: kvcreds
        options:
          usepodidentity: "false"
          keyvaultname: $AKV_NAME
          keyvaultobjectnames: $AKV_OBJECTS
          keyvaultobjectaliases: $AKV_ALIASES
          keyvaultobjecttypes: "secret;secret"
          tenantid: $AKV_TENANT_ID
EOF
``` 

``` 
$ kubectl describe pod flexvol-notebook-0

  secret-volume:
    Type:       FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:     azure/kv
    FSType:
    SecretRef:  &LocalObjectReference{Name:kvcreds,}
    ReadOnly:   false
    Options:    map[keyvaultname:
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): `build version dev_local`, should be 1.0.1 but can't find where it says... 
- kfctl version: (use `kfctl version`): `kfctl v1.0.2-0-ga476281`
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from `/etc/os-release`): 

```
BUILD_ID=12871.1196.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=c46f8a87c479cd2e964513992d3eab92eff5c160
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=81
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=81
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
```

Thank you!
Shaked
