### ISSUE TITLE
New Profile fails on Kubeflow-UI-dashboard

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/kubeflow#5327]
I have setup Kubeflow on local Ubuntu PC by using microk8s tutorial (https://ubuntu.com/kubeflow/install). After successful install I do:
```
$ microk8s.kubectl get profiles
```
I get response:
```
NAME    AGE
admin   79m
```
On the UI side I get: https://github.com/ajinkya933/tmp-images/blob/main/kubeflow.png

But after I create a new profile using ```profile.yaml``` file (reference: https://www.kubeflow.org/docs/components/multi-tenancy/getting-started) 

profile.yaml
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: sonal   # replace with the name of profile you want, this will be user's namespace name
spec:
  owner:
    kind: User
    name: userid@email.com   # replace with the email of the user

  resourceQuotaSpec:    # resource quota can be set optionally
   hard:
     cpu: "2"
     memory: 2Gi
     nvidia.com/gpu: "1"
     persistentvolumeclaims: "1"
     requests.storage: "5Gi"
```
I apply this yaml file using:
```
microk8s.kubectl create -f profile.yaml
```
I get response:
```
NAME    AGE
admin   4h21m
sonal   168m
```
On the UI side I get: https://github.com/ajinkya933/tmp-images/blob/main/kubeflow.png

Why isn't the new user ```sonal``` added as an additional option in addition to default ```admin(Owner)``` option on dashboard  ?
