### ISSUE TITLE
Add support to display different GPU types, specifically NVIDIA Multi-Instance GPUs

### ISSUE THREAD

**Issue by supertetelman** [kubeflow/kubeflow#5335]
/kind enhancement

NVIDIA recently release a new Multi-Instance GPU feature that changes some of the resourcing naming nomenclature. There are two configuration modes, one of which depends on nodeSelectors (which should be covered by recent changes) and one of which depends on a series of new resource types (`nvidia.com/mig-1g.5gb1`, `nvidia.com/mig-2g.10gb` , ...).

I was looking through some of the new Notebook dashboard code and it looks like the values `nvidia.com/gpu` and `amd.com/gpu` are hardcoded in https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py.

```
def process_gpu(cntr):
    
    # GPUs may not have been assigned to a pod 
    gpu = 0
    gpuvendor = 'nvidia'
    try:
        gpu = cntr["resources"]["limits"]["nvidia.com/gpu"]
    except KeyError:
        try:
            gpu = cntr["resources"]["limits"]["amd.com/gpu"]
            gpuvendor = 'amd'
        except KeyError:
            gpu = 0
            gpuvendor = ''

    return gpu, gpuvendor
```

I haven't tested this latest code on a cluster configured with these new device types, but based on what I see it should still be able to deploy the notebook, but the gpu resources will not properly display (I have a small example of the yaml configuration changed to get MIG working here: https://github.com/NVIDIA/deepops/issues/671):

```
      vendors:
        - limitsKey: "nvidia.com/mig-7g.40gb"
          uiName: "NVIDIA MIG - 7g.40gb"
        - limitsKey: "nvidia.com/mig-4g.20gb"
          uiName: "NVIDIA MIG - 4g.20gb"
        - limitsKey: "nvidia.com/mig-3g.20gb"
          uiName: "NVIDIA MIG - 3g.20gb"
        - limitsKey: "nvidia.com/mig-2g.10gb"
          uiName: "NVIDIA MIG - 2g.10gb"
        - limitsKey: "nvidia.com/mig-1g.5gb"
          uiName: "NVIDIA MIG - 1g.5gb"
        - limitsKey: "amd.com/gpu"
          uiName: "AMD"
```

We already have the necessary CONFIG info from the yaml file loaded here. I'm thinking we could just replace these nested except block with a loop through the Vendor list.

I'm guessing this doesn't have much impact on people deploying in the cloud, but for people looking to run Kubeflow on prem in large GPU clusters this could become annoying.
