### ISSUE TITLE
Kubeflow Installation - Kustomize Manifests

### ISSUE THREAD

**Issue by ptartan21** [kubeflow/kubeflow#5406]
/kind question

**Question:**
Hi - I'm trying to install kubeflow on an Ubuntu machine using kfctl_k8s_istio config. I'm currently doing this by pulling the `.yaml` files that correspond to the kfctl version that I want (1.1.0) from `/manifests`. However, I'm running into an issue where the metadata of resources (such as tf-job-operator, below) does not include any namespaces, but is later referenced in the fieldPath fieldPath. I've pasted an example below. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-job-operator
spec:
  replicas: 1
  template:
    **metadata:**
      labels:
        name: tf-job-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - --alsologtostderr
        - -v=1
        - --monitoring-port=8443
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              **fieldPath: metadata.name**
        image: gcr.io/kubeflow-images-public/tf_operator:kubeflow-tf-operator-postsubmit-v1-5adee6f-6109-a25c
        name: tf-job-operator
      serviceAccountName: tf-job-operator
```

I've tried to modify the `.yaml` locally to have a namespace, but it just gets overwritten. Many other resources/applications have this same issue. Is there a way that I can fix this? I've pasted the error below. 

```
for: "/tmp/kout666725222": Deployment.apps "tf-job-operator" is invalid: [spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty, spec.template.spec.containers[0].env[1].valueFrom: Invalid value: "": may not be specified when `value` is not empty, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"tfjob", "app.kubernetes.io/name":"tf-job-operator", "juju-app":"tf-job-operator", "kustomize.component":"tf-job-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable]]  filename="kustomize/kustomize.go:266"
```

Any help would be appreciated. Thank you!
