### ISSUE TITLE
Kubeflow release process and customization of v1.2.0+ installation

### ISSUE THREAD

**Issue by sylus** [kubeflow/kubeflow#5440]
/kind bug

Hello amazing Kubeflow community!

We’ve been using Kubeflow in an experimental phase since before 1.0 and pretty heavily in our Data Analytics as a Service environment after the 1.0 release and has been working quite well! Very recently we attempted to upgrade to the 1.1.0 release and encountered a bunch of workflow issues.

For reasons specific to our environment, we have to customize the installation of Kubeflow. With the 1.0 release of Kubeflow, we were able to accomplish this by the following:

1. Modified the kfctl_k8s_istio.yaml
2. Ran `kfctl build -f kfctl_k8s_istio`
3. And performed customizations by modifying manifests in the kustomize folder

https://github.com/statcan/kubeflow-manifest

We first attempted the upgrade to 1.1.0 by performing the same task. We re-modified the updates and aligned them with what we needed. However, after deployment, we found out that the manifests in the 1.1.0 tag are not actually the latest manifests for the 1.1.0 release but instead they were made available after the release (I believe in August based on https://github.com/kubeflow/manifests/issues/1364#issuecomment-668415871). However, when attempting to re-apply our modifications to the manifests, the new structure of the release manifests for 1.1 does not allow for the same process. We don’t want to modify the .cache folder (and in fact, we don’t commit the .cache folder) for obvious reasons.

Figuring that we were incorrectly modifying the release manifests we further researched how Kubeflow recommends modifying the release. We found https://www.kubeflow.org/docs/other-guides/kustomize/ which don’t really identify how to actually make changes (it gives some “ideas” but no examples).

Our workflow was dependent on the full output into the kustomize folder like was done in 1.0 and we no longer get that output anymore to modify. We started looking into docs on this and found https://developers.redhat.com/blog/2020/07/23/open-data-hub-and-kubeflow-installation-customization/ which documented some ways to customize the install, which involves a fork and ways of working with it. Our preferred method is #3, which is to use overlays to apply configuration. But according to https://github.com/kubeflow/kfctl/issues/402, the use of overlays has been deprecated.

We were able to add a component say for example creating a dex folder then adding a configmap and then doing a strategic merge. We can then do `kustomize build .` on just that specific component to see our replacement works. So `kustomize build kustomize/dex` works. However when we try `kustomize build kustomize/kubeflow-apps`, we get an error rendering the manifests:

```sh
Error: accumulating resources: accumulateFile "accumulating resources from '../../.cache/manifests/manifests-1.1-branch/stacks/azure': '/Users/XXXXX/Desktop/kubeflow/daaas/.cache/manifests/manifests-1.1-branch/stacks/azure' must resolve to a file", accumulateDirector: "recursed accumulation of path '/Users/XXXXX/Desktop/kubeflow/daaas/.cache/manifests/manifests-1.1-branch/stacks/azure': accumulating resources: accumulateFile \"accumulating resources from '../../admission-webhook/webhook/v3': '/Users/XXXXX/Desktop/kubeflow/daaas/.cache/manifests/manifests-1.1-branch/admission-webhook/webhook/v3' must resolve to a file\", accumulateDirector: \"recursed accumulation of path '/Users/XXXXX/Desktop/kubeflow/daaas/.cache/manifests/manifests-1.1-branch/admission-webhook/webhook/v3': accumulating resources: accumulateFile \\\"accumulating resources from '../overlays/application/application.yaml': security; file '/Users/XXXXX/Desktop/kubeflow/daaas/.cache/manifests/manifests-1.1-branch/admission-webhook/webhook/overlays/application/application.yaml' is not in or below '/Users/XXXXX/Desktop/kubeflow/daaas/.cache/manifests/manifests-1.1-branch/admission-webhook/webhook/v3'\\\", loader.New \\\"Error loading ../overlays/application/application.yaml with git: url lacks host: ../overlays/application/application.yaml, dir: got file 'application.yaml', but '/Users/XXXXX/Desktop/kubeflow/daaas/.cache/manifests/manifests-1.1-branch/admission-webhook/webhook/overlays/application/application.yaml' must be a directory to be a root, get: invalid source string: ../overlays/application/application.yaml\\\"\""
```

Therefore, I think our questions are as follows:

1. What is the officially supported way of applying customizations to the install?
2. With kustomize, how can we preview the changes of our overlays in kubeflow-apps like we were able to do with the other components? Given `kustomize build kustomize/kubeflow-apps` doesn't work.
3. We are also a bit confused about where to find the manifests associated with a release and a fixed set of artifacts. Sometimes we find the manifests references 1.1.0 and otherwise the v1.1 branch. What manifests are we supposed to use? We would expect to pull them from the tagged release in `kubeflow/manifests` (1.1.0)

Thank you in advance for your time and please reach out if you have any questions.

> Note: You can see a list of all the customizations we want to make that were done without issue in Kubeflow 1.0.0 here: https://github.com/StatCan/kubeflow/issues/11

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): 1.1.0
- Kubernetes platform: (e.g. `minikube`): 1.16.15
- Kubernetes version: (use `kubectl version`): 1.16.15
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by sylus** [comment]
@aronchick is it possible you would be able to assist with this? :D

**Comment by sylus** [comment]
So I think I might understand this a bit better now after going through it.

Some of the confusion resulted in that pre v1.1.0 that the full output was in the kustomize folder, however now in v1.1.0+ we are just encouraged on using the delta via strategic merges etc. Due to this I was able to get all of our custom configuration working in the v1.2.0 line though in order to make our customizations we had to explicitly call all of the components that the kubeflow-app calling `stacks/azure` was using.

https://github.com/StatCan/kubeflow-manifest/tree/feat-kubeflow

The biggest problem I was having was how I can test the delta so what I ended up doing was running the following command and then storing in git temporarily the output while was performing the adjustments. This then lets me see the delta and that things were working correctly.

```
kfctl build -V -f ./kfctl_azure.yaml -d > output.yaml
```

Here was the contents of the kfctl_azure.yml which allowed for us to store our overrides in the kustomize folder:

```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: kubeflowmanifests
  namespace: kubeflow
spec:
  applications:
  # Istio installed in istio-system
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: stacks/azure
  #   name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/centraldashboard
    name: centraldashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/jupyter-web-app
    name: jupyter-web-app
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/oidc-authservice
    name: oidc-authservice
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/spark-operator
    name: spark-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/spartakus
    name: spartakus
  # Components
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/webhook/v3
    name: admission-webhook
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: argo/base_v3
    name: argo
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: jupyter/notebook-controller/base_v3
    name: notebook-controller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib/installs/katib-standalone
    name: katib
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kfserving/installs/generic
    name: kfserving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kubeflow-roles/base
    name: kubeflow-roles
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metadata/v3
    name: metadata
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/minio/installs/generic
    name: minio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: mpi-job/mpi-operator/overlays/application
    name: mpi-job
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: mxnet-job/mxnet-operator/overlays/application
    name: mxnet-job
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/mysql/installs/generic
    name: mysql
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/installs/generic
    name: pipeline
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/pipelines-ui/overlays/istio
    name: pipelines-ui
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: profiles/base_v3
    name: profiles
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pytorch-job
    name: pytorch-job
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: tf-training
    name: tf-training
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2-branch.tar.gz
  version: v1.2-branch
status:
  reposCache:
  - localPath: '".cache/manifests/manifests-1.2-branch"'
    name: manifests
```

Then in the above I can still use our envsubst and yq replacements on the kustomize folder to interpolate our OIDC parameters through a GitHub actions P.R.

I think my questions now get reduced to the followin:

1) Does this look correct and is the officially supported way of applying customizations to the install?
2) I noticed that the KFDef now call the manifests-1.2 branch instead of a stable tag is that okay we are doing that?

**Comment by sylus** [comment]
So fixed up the rest of this locally but it should be super easy to upgrade kubeflow now as we made our own “stack” similar to how the azure one is except with our customizations and improvements. It also does it the kustomize way but can see that our kfctl file is now really small and does most of the grunt work. Nice thing is that inheritance works well and is really easy to modify the defaults now without needing tool like yq

https://github.com/StatCan/kubeflow-manifest/tree/feat-kubeflow
https://github.com/StatCan/kubeflow-manifest/blob/feat-kubeflow/kfctl_azure.yaml

Run our KFDefinition file:

```
kfctl build -V -f kfctl_azure.yaml
```

```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  clusterName: k8s-cancentral-01-default-aks
  name: kubeflowmanifests
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: daaas
        path: stacks/daaas
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/oidc-authservice
    name: oidc-authservice
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2-branch.tar.gz
  version: v1.2-branch
status:
  reposCache:
  - localPath: '".cache/manifests/manifests-1.2-branch"'
    name: manifests
  - localPath: '"kustomize"'
    name: daaas
```

This will in turn calls our “DAaaS” stack along with other  application-level components such as OIDC which in turn call the kubeflow components in .cache with our overrides:

```
.
├── application
│   ├── admission-webhook
│   │   └── kustomization.yaml
│   ├── argo
│   │   ├── cluster-role.yaml
│   │   ├── config-map.yaml
│   │   ├── kustomization.yaml
│   │   └── service.yaml
│   ├── centraldashboard
│   │   ├── deployment.yaml
│   │   └── kustomization.yaml
│   ├── jupyter-web-app
│   │   ├── cluster-role.yaml
│   │   ├── configs
│   │   │   └── spawner_ui_config.yaml
│   │   ├── deployment.yaml
│   │   ├── deployment_patch.yaml
│   │   ├── kustomization.yaml
│   │   └── params.env
│   ├── katib
│   │   └── kustomization.yaml
│   ├── kfserving
│   │   └── kustomization.yaml
│   ├── knative
│   │   ├── config-map.yaml
│   │   └── kustomization.yaml
│   ├── kubeflow-roles
│   │   └── kustomization.yaml
│   ├── kustomization.yaml
│   ├── metadata
│   │   └── kustomization.yaml
│   ├── minio
│   │   ├── kustomization.yaml
│   │   └── persistent-volume-claim.yaml
│   ├── mpi-job
│   │   └── kustomization.yaml
│   ├── mxnet-job
│   │   └── kustomization.yaml
│   ├── mysql
│   │   └── kustomization.yaml
│   ├── notebook-controller
│   │   ├── deployment.yaml
│   │   └── kustomization.yaml
│   ├── pipeline
│   │   ├── deployment.yaml
│   │   └── kustomization.yaml
│   ├── profiles
│   │   ├── deployment.yaml
│   │   └── kustomization.yaml
│   ├── pytorch-job
│   │   └── kustomization.yaml
│   ├── spark-operator
│   │   └── kustomization.yaml
│   └── tf-training
│       └── kustomization.yaml
├── kubeflow-apps
│   └── kustomization.yaml
├── metacontroller
│   └── kustomization.yaml
├── namespaces
│   └── kustomization.yaml
├── oidc-authservice
│   ├── configmap.yaml
│   ├── envoy-filter.yaml
│   ├── kustomization.yaml
│   └── statefulset.yaml
└── stacks
    └── daaas
        ├── config
        │   └── params.env
        └── kustomization.yaml
```
