### ISSUE TITLE
Way to "import" existing namespaces

### ISSUE THREAD

**Issue by hightoxicity** [kubeflow/kubeflow#5449]
/kind question

**Question:**
Hi, I deployed main components of kubeflow (multitenant pipelines, istio, dex), I can create new namespaces for profiles using GUI, I can launch pipelines in new created namespace and it properly run.

Now, I have already created namespaces (not by kubeflow), and I would like to "import it" into kubeflow, I have seen that there is a CRD Profile (creating this object appears to not be enough) but what are all the pieces required to enroll those namespaces?

Thanks.

**Comment by hightoxicity** [comment]
OK, only one annotation need to be added to the namespace to enroll:

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    owner: admin@example.com
  name: example
```
