### ISSUE TITLE
How to serve namespaced custom web service behind kubeflow-gateway

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kubeflow#5466]
/kind question

**Question:**

I am trying to figure out how I can place a custom service behind the default authn/authz that is shipped with Kubeflow. Let's say I want to host a small helloworld web app, and want it to be reached a `https://platform.mydomain.com/helloworld`.  I am able to get a simple example up and running as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: kubeflow
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: hello-k8s
        image: paulbouwer/hello-kubernetes:1.7
        ports:
        - containerPort: 8080      
      serviceAccountName: helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: kubeflow
spec:
  selector:
    app: helloworld
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: helloworld
  namespace: kubeflow
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /helloworld
      rewrite:
        uri: /
      route:
        - destination:
            host: helloworld.kubeflow.svc.cluster.local
            port:
              number: 80
      timeout: 300s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: kubeflow
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: helloworld
  name: helloworld
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helloworld
subjects:
- kind: ServiceAccount
  name: helloworld
```

What I haven't been able to figure out yet though, is how I could make use of the namespace filtering / multi-tenancy that was introduced in KF 1.1. I.e., I want to be able to host these apps in specific namespaces and only allow access to namespace owners (and invited guests). I presume for this I would need to switch on istio sidecar injection but am not sure what else is needed.

In effect I would like the AuthN to trigger on

```
platform.mydomain.com/helloworld?ns=karl-schriek
platform.mydomain.com/helloworld?ns=someone-else
```

And want to redirect to the service running in that namespace based on the filtering that is applied. 

Etc.
