### ISSUE TITLE
Notebook servers renders a blank page

### ISSUE THREAD

**Issue by tianhaoz95** [kubeflow/kubeflow#5480]
/kind bug

**What steps did you take and what happened:**
I installed Kubeflow with steps in https://www.kubeflow.org/docs/started/workstation/getting-started-multipass, but the notebook servers tab is empty.

**What did you expect to happen:**

It should show a button for adding notebooks.

**Anything else you would like to add:**

![Screenshot from 2020-12-21 22-54-59](https://user-images.githubusercontent.com/16887772/102859031-1b054e80-43e0-11eb-93cd-813bbabc77d5.png)

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version dev_local
- kfctl version: (use `kfctl version`): kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`) microk8s
- Kubernetes version: (use `kubectl version`): 

```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

- OS (e.g. from `/etc/os-release`):

```bash
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by unijoy** [comment]
+1

**Comment by k402xxxcenxxx** [comment]
+1

**Comment by Dottorepoloni** [comment]
I have same SW-configuration and same error...

**Comment by Dottorepoloni** [comment]
btw any workaround? I'm a bit stuck...

**Comment by tianhaoz95** [comment]
@Dottorepoloni doing it with minikube worked for me if you are in a hurry, but still no luck with microk8s.

**Comment by DavidSpek** [comment]
microk8s uses the Kubeflow charms. It might be worth creating an issue at https://github.com/juju-solutions/bundle-kubeflow.

**Comment by Dottorepoloni** [comment]
With minikube I had no luck, but miniKF is running fine... even if miniKF is actually built with minikube 🤔

**Comment by k402xxxcenxxx** [comment]
I think the root cause is the routing problem to jupyter-web

I install the kubeflow on Ubuntu 20.04 using microk8s and follow the installation steps on [official doc](https://www.kubeflow.org/docs/started/workstation/getting-started-multipass/)

I found that after it finished the installation, the virtual service configuration for jupyter-web isn't there.
So I do the walk around (referenced by [istio example](https://istio.io/latest/docs/examples/microservices-istio/istio-ingress-gateway/) and [manifist yaml files](https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/overlays/istio/virtual-service.yaml)) to manually setup the virtual service configuration.

the command I use:
```
microk8s kubectl patch virtualservices jupyter-web -n kubeflow --patch "$(cat patch-jupyter-web.yaml)" --type=merge
```
the patch-jupyter-web.yaml I use:
```yaml
# patch-jupyter-web.yaml
spec:
  gateways:
  - kubeflow
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /jupyter
    match:
    - uri:
        prefix: /jupyter/
    rewrite:
      uri: /
    route:
    - destination:
        host: jupyter-web.kubeflow.svc.cluster.local
        port:
          number: 5000
```

It should make notebook server comeback and you can create/delete jupyter notebook container.

But still has trouble when you press the CONNECT button, it will show  `/notebook/{namespace}/{jupyter-name}` is not a valid page even if the jupyter notebook container is really created.
I think it could be solved by correct the istio gateway configuration in jupyter-controller(some bundle will call it notebook-controller).

I'm not sure it is a good way to solve this problem. Please give me some response.

**Comment by k402xxxcenxxx** [comment]
The "`/notebook/{namespace}/{jupyter-name}` is not a valid page" problem can be solved by doing the workaround that manually add the new gateway named `kubeflow-gateway`. 

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: null
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```
