### ISSUE TITLE
Env variables not attached in the notebook pod

### ISSUE THREAD

**Issue by vanaraj-az** [kubeflow/kubeflow#5534]
/kind question

**Question:**
[You can ask any question about this project.]
I need to add some env variables in the notebook pod. So that I have used PodDefault manifest as informed in the document. The file contents which is below

```
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: add-database-info
  namespace: kubeflow-vinay
spec:
  desc: my database credentials and configs
  selector:
    matchLabels:
      add-database-info: "true"
  envFrom:
  - secretRef:
      name: db-user-creds
```
I have run the below command to create the configmap

`kubectl create -n kubeflow-vinay secret generic db-user-creds --from-literal=DB_USER=root --from-literal=DB_PASSWORD=l3tm3in`

I am able to see this in the notebook configuration dropdown. If I select the configuration, the values are not attached to the notebook pod

Do I need to add anything else?

Thanks in advance

**Comment by solarist** [comment]
I thought it was solved in https://github.com/kubeflow/kubeflow/issues/5369?

**Comment by jbottum** [comment]
/priority p2
/area jupyter

@vanaraj-az did you get this resolved?

**Comment by jaiganeshp** [comment]
I am facing the same issue in Kubeflow 1.3. I am able to see the configuration in the dropdown menu but it is not copying the volumes, volume mounts, and environment variables from the Poddefault. I am using this definition of PodDefault. 

```
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-pipeline
spec:
  desc: Allow access to Kubeflow Pipelines
  selector:
    matchLabels:
      access-ml-pipeline: "true"
  volumeMounts:
  - mountPath: /var/run/secrets/ml-pipeline
    name: volume-ml-pipeline-token
    readOnly: true
  volumes:
  - name: volume-ml-pipeline-token
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 7200
          audience: ml-pipeline
  env:
  - name: ML_PIPELINE_SA_TOKEN_PATH
    value: /var/run/secrets/ml-pipeline/token  # this is dependent on the volume mount path and SAT path
```
This pod default was copied from the comment here: https://github.com/kubeflow/pipelines/issues/5138#issuecomment-797003710

Has anyone else run into this issue with Kubeflow 1.3?
