### ISSUE TITLE
Unable to start Notebook Server on EKS

### ISSUE THREAD

**Issue by AahanSingh** [kubeflow/kubeflow#5563]
/kind bug

**What steps did you take and what happened:**
I have followed the tutorial here: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ to install Kubeflow on an EKS cluster. Initially the eks cluster had 3 servers running. When I try to create a notebook server the prompt next to the spawning server initially said `1 Too Many Pods 7 Insufficient CPU`. After increasing the desired capacity to 4 a few things happened. As expected a new node was spawned. I tried to spawn a server again and after waiting for about 5 mins it had still not spawned. Next I noticed that something caused 4 new nodes to be spawned. Now I have 8 nodes in this cluster which seems excessive. There are no other services running on this cluster apart from the ones started by kubeflow after installation and during the process of spawning the notebook. I have also not done anything else on kubeflow so far apart from trying to spawn the notebook server. After about 15 mins the prompt next to the spawning notebook says `Reissued from pod/hello-world-0: Back off restarting failed container`. After 20 mins the status is `The pod has terminated` and the whole process restarts again. I'm a beginner and don't really know whats happening. Any help would be greatly appreciated.

**What did you expect to happen:**
The notebook server should have spawned. 

**Anything else you would like to add:**
Cluster Config for the eks cluster:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubeflow-gpu
  region: ap-southeast-1

managedNodeGroups:
  - name: managed-ng-1
    instanceType: g4dn.xlarge
    desiredCapacity: 3
    minSize: 2
    maxSize: 10
    volumeSize: 100
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1beta1
- kfctl version: (use `kfctl version`):kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`): Amazon EKS
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04
