### ISSUE TITLE
ALB cannot be created / Existing nginx ingress

### ISSUE THREAD

**Issue by Jboulery** [kubeflow/kubeflow#5586]
/kind question
/platform aws

eksctl version: 0.31.0
kubectl version: v1.17.12-eks-7684af
kfctl version: v1.2.0-0-gbc038f9

**Question:**
I'm trying to apply [the following configuration](https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws_cognito.v1.2.0.yaml) to deploy Kubeflow with authentication.
It's an existing cluster where an Nginx ingress controller is already there (and the related ELB). 

I followed the instructions [here](https://www.kubeflow.org/docs/aws/authentication/). So far the only issue I have is that AWS certificate remains in "pending validation" state even though I added the mentioned CNAME record to the DNS configuration. 

A couple of minutes after deployment, ALB isn't available:
```bash
$ kubectl get ingress istio-ingress -n istio-system
NAME            HOSTS   ADDRESS   PORTS   AGE
istio-ingress   *                 80      43m
```
And issues mentioned [here](https://www.kubeflow.org/docs/aws/troubleshooting-aws/#alb-can-not-be-created) seem unrelated to the issue as cluster name is correctly set and subnets correctly tagged.

I thought it could be normal since an ELB is already there, so I added the following configuration to make nginx ingress redirect kubeflow related requests to istio-ingressgateway. Kubeflow dashboard became available at kubeflow.mycompany.com as expected.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeflow-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kubeflow.mycompany.com
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /
```

Unfortunately authentication is still not working and if the logout button (seems we're logged in by default?) is clicked, then the page keeps being refreshed indefinitely, so here are my questions:
1) Is it possible to deploy Kubeflow on a cluster along an Nginx ingress or is it causing conflicts with istio? If yes, what should I modify in the configuration?
2) Can it be that the pending validation state of the certificate blocks authentication from being available?
