### ISSUE TITLE
Attaching ROX volume to a notebook

### ISSUE THREAD

**Issue by arunnalpet** [kubeflow/kubeflow#5676]
Hi, 
      Using the KubeFlow Notebook UI, while Im spinning up a new notebook server, I am attaching a 'data volume'. This is an existing PVC with 'ROX' privileges. I have training data in it and I want to present it as read-only. While this notebook was being spun up, I see the 'fsgroup-init' is trying to change the group ids for the folder/files in 'ROX' volume. Its failing with below error, to change the group permissions as the PVC is readOnly. 

```
chgrp: /home/jovyan/data-vol-1/bigfile2.txt: Read-only file system
chgrp: /home/jovyan/data-vol-1/bigfile1.txt: Read-only file system
chgrp: /home/jovyan/data-vol-1: Read-only file system
```

**How is notebook controller designed to deal with ROX volumes? It should not ideally be executing chgrp commands!** 

Here is the definition of ROX volume im trying to attach as data volumes:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-adadmin1-pvc
spec:
  storageClassName: "default-cluster"
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
```

**Comment by arunnalpet** [comment]
Hi @DavidSpek, I have tried this with gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-cpu:v0.5.0 image.. but this happens with any notebook image..

**Comment by arunnalpet** [comment]
May be we should check the PVC attributes, and accordingly, we should be skipping setting 'DefaultFSGroup' for ROX volumes?

**Comment by DavidSpek** [comment]
@arunnalpet I believe this section in the notebook-controller is what is causing this behavior. 
https://github.com/kubeflow/kubeflow/blob/98fc2dcb57fe0a5311abed28510a4df58a506971/components/notebook-controller/controllers/notebook_controller.go#L353

**Comment by jbottum** [comment]
@arunnalpet is this in an on-prem cluster i.e. openshift?   please let us know.   your answer will help us to route to the right platform/distribution team.

**Comment by arunnalpet** [comment]
@jbottum .. this is not openshift.. this is vanilla Kubernetes which is deployed and managed by HPE Ezmeral platform.. and yes this is on-prem cluster.

**Comment by abreu4** [comment]
I'm facing a similar problem.
I'm trying to connect multiple notebooks within the same namespace to the same persistent volume using the same persistent volume claim. The persistent volume is backed by a GCE persistent disk.
The claim and volume manifests look like this

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  storageClassName: ""
  capacity:
    storage: 20G
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: my-namespace
    name: example-pvc
  gcePersistentDisk:
    pdName: example-disk
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20G
```

When applying this manually, I can see the claim in the volumes tab of my-namespace, but when I spin up a notebook server, the volume is mounted as ReadWriteOnce.

Any tips? Is rebuilding the jupyter-web-server app the only way?
