### ISSUE TITLE
Logout from Kubeflow application with Auth0 causing infinite loop

### ISSUE THREAD

**Issue by avg00r** [kubeflow/kubeflow#5704]
/kind bug

**What steps did you take and what happened:**
Setup authentication to Kubeflow with Auth0 following [Authentication using OIDC](https://www.kubeflow.org/docs/aws/authentication-oidc/) steps.
With the difference, I use google account instead of github as a IdP on the Auth0 side.
This is the file which we are using to deploy kubeflow `kfctl_aws_cognito.v1.2.0.yaml`
I am able to login with my Google account to kubeflow via auth0 (my email whitelisted in auth0 rule which allowing connection to the kubeflow application).
When I click to logout link in kubeflow it is running into an infinite loop. 

**What did you expect to happen:**
Logout successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
On the Auth0 side I see  Failed Login event with message:

> Callback URL mismatch. https://`ip-address`/oauth2/idpresponse is not in the list of allowed callback URLs

Instead of that `ip-address` I use hostname, so are there any configurable variable to setup the callback URL on kubeflow side?

**Environment:**

- Kubeflow version build version v1beta1
- kfctl version : v1.2.0-0-gbc038f9
- Kubernetes platform : AWS EKS
- Kubernetes version:  Client Version: v1.19.0 , Server Version: v1.18.9-eks-d1db3c
- OS : Debian ( this is the OS on EKS nodes )

**Comment by kim-sardine** [comment]
Same issue here!!

[This youtube link](https://youtu.be/cAEtjMI1KcQ?t=2128) says that two steps are required

1. set expiration time of the authentication session cookie to `-1`
2. redirect client to ldp logout endpoint. (eg. `https://mydomain.auth.us-east-1.amazoncognito.com/logout?
client_id=ad398u21ijw3s9w3939&
logout_uri=https://myclient/logout`)

but our central dashboard just redirect client to `https://myclient/logout` page

**Comment by MarcandreBoulon** [comment]
> Same issue here with `kfctl_aws_cognito.v1.2.0.yaml`!! infinite loop when user click logout button.
> 
> [This youtube link](https://youtu.be/cAEtjMI1KcQ?t=2128) says that two steps are required to logout.
> 
> 1. set expiration time of the authentication session cookie to `-1` (delete cookie)
> 2. redirect client to ldp logout endpoint. (eg. `https://mydomain.auth.us-east-1.amazoncognito.com/logout? client_id=ad398u21ijw3s9w3939&logout_uri=https://myclient/logout`)
> 
> (I was able to logout successfully when I did above process myself)
> 
> but it seems like our centraldashboard just redirect client to `https://myclient/logout` page. and it makes infinite loop
> 
> https://github.com/kubeflow/kubeflow/blob/98fc2dcb57fe0a5311abed28510a4df58a506971/components/centraldashboard/public/components/main-page.js#L235-L237

in a similar fashion I confirm the process below works for me : 

1. delete cookie 
2. https://{auth.mydomain}/logout?response_type=code&client_id={my_client_id}&redirect_uri={my_callback_uri}&state=STATE&scope=openid+profile+aws.cognito.signin.user.admin      >   as described in https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html (example 2)

my_callback_uri not my_signout_uri

**Comment by AlecZebrick** [comment]
Same issue here, infinite loop on logout.

**Comment by jbottum** [comment]
@ninja-tester @AlecZebrick @MarcandreBoulon @kim-sardine have you tried this test log-out test case with Kubeflow 1.3 ?

**Comment by DavidSpek** [comment]
This can be fixed with a virtual service. Here is a link for a virtual service that fixes sign out when using Oauth2-Proxy and Keycloak. 

https://github.com/argoflow/argoflow-aws/blob/master/distribution/oidc-auth/overlays/keycloak/oauth2-proxy-signout-virtual-service.yaml

**Comment by AlecZebrick** [comment]
> @ninja-tester @AlecZebrick @MarcandreBoulon @kim-sardine have you tried this test log-out test case with Kubeflow 1.3 ?

Is that supported on AWS? According to this: https://www.kubeflow.org/docs/started/installing-kubeflow/ 1.2 is for AWS and 1.3 is for GC

**Comment by AlecZebrick** [comment]
> This can be fixed with a virtual service. Here is a link for a virtual service that fixes sign out when using Oauth2-Proxy and Keycloak.
> 
> https://github.com/argoflow/argoflow-aws/blob/master/distribution/oidc-auth/overlays/keycloak/oauth2-proxy-signout-virtual-service.yaml

Thank you for this, might be pointing me in the right direction. I've never used a virtual proxy before in k8's, do you think this would work with cognito?

**Comment by DavidSpek** [comment]
@AlecZebrick It's an Istio configuration that redirects requests from the central-dashboard logout button to wherever you need. You’ll just need to change it for your logout URL and OIDC provider.

**Comment by MauGeo** [comment]
> This can be fixed with a virtual service. Here is a link for a virtual service that fixes sign out when using Oauth2-Proxy and Keycloak.
https://github.com/argoflow/argoflow-aws/blob/master/distribution/oidc-auth/overlays/keycloak/oauth2-proxy-signout-virtual-service.yaml

I am having the same issue with the Azure deployment. Infinite loop on logout. I tried modifying the solution with the virtual service for Azure, but it does not work. Is anyone having the same issues with Azure? 

Does anyone know to which service the /logout request is sent? I think this could help me.

**Comment by harmeet-singh-discovery** [comment]
I installed Kubeflow 1.4 with Cognito.
When I try to logout, it goes into infinite loop and does not logout.

**Comment by atbraoy** [comment]
kind bug
/priority p1

I can't believe no one from Kubeflow team wants to pay attention to this issue/bug! I'm having the same infinite logout loop (dex auth). Forget about the pain we went through to get kubeflow working on a local kubernetes server!

At least point out to workaround until you fix it!

**Comment by jbottum** [comment]
@kubeflow/wg-notebooks-leads double checking on this...do you have comments on this ?

**Comment by Alec-Zebrick** [comment]
Following, was never able to get it solved either. Infinite logout loop as described by OP

**Comment by snps-sagarrao** [comment]
I was able to successfully logout if I close the browser (Chrome) and reopen the kubeflow URL again and click on logout. I was using KeyCloak by replacing the Dex in my case in OIDC.

**Comment by hockic** [comment]
here's how i got arround it on a gateway-api setup using keycloak as idp:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: oauth2-proxy-logout
  namespace: oauth2-proxy
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: oauth2-proxy
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "request.info", {
                  path = request_handle:headers():get(":path"),
                  method = request_handle:headers():get(":method"),
                  xredirect = request_handle:headers():get("x-auth-request-redirect"),
                })
              end

              function envoy_on_response(response_handle)
                local meta = response_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.lua")["request.info"]
                
                if meta.path == "/oauth2/sign_out" and meta.method == "POST" and response_handle:headers():get(":status") == "302" then
                  response_handle:headers():replace(":status", "202")
                  response_handle:headers():remove("location")
                  local content_length = response_handle:body(true):setBytes("{\"afterLogoutURL\":\"" .. meta.xredirect .. "\"}")
                  response_handle:headers():replace("content-type", "application/json")
                  response_handle:headers():replace("content-length", content_length)
                end
              end
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: oauth2-proxy-kubeflow
  namespace: oauth2-proxy
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: kubeflow
  to:
  - group: ""
    kind: Service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: centraldashboard-logout
  namespace: kubeflow
  labels:
    sirius.hockic.com/component: kubeflow
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kubeflow-ingressgateway
      namespace: kubeflow-system
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: oauth2-proxy
          namespace: oauth2-proxy
          port: 80
          weight: 1
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: x-auth-request-redirect
                value: http://keycloak.keycloak.svc.cluster.local/realms/main/protocol/openid-connect/logout
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /oauth2/sign_out
              type: ReplacePrefixMatch
      matches:
        - path:
            type: PathPrefix
            value: /authservice/logout
```
