### ISSUE TITLE
Kubeflow on GCP - setup error III

### ISSUE THREAD

**Issue by SaschaHeyer** [kubeflow/kubeflow#5760]
/kind bug

**What steps did you take and what happened:**

1. Followed the guidelines https://master.kubeflow.org/docs/distributions/gke/deploy/deploy-cli/#configure-kubeflow
2. Step make apply fails with the following error message

```
istioctl manifest generate -f ./upstream/manifests/gcp/v2/asm/istio-operator.yaml -o .build/istio
Error: validation errors (use --force to override):
unknown field "env" in v1alpha1.ProxyConfig
```

istio-operator.yaml

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  clusterName: "xyz/us-west1-b/kubeflow" # {"$kpt-set":"asm-cluster-name"}
spec:
  profile: asm
  hub: gcr.io/gke-release/asm
  tag: 1.4.10-asm.15
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    global:
      meshID: "proj-xyz" # {"$kpt-set":"asm-mesh-id"}
      trustDomain: "xyz.svc.id.goog" # {"$kpt-set":"identity-ns"}
      sds:
        token:
          aud: "xyz.svc.id.goog" # {"$kpt-set":"identity-ns"}
      proxy:
        env:
          GCP_METADATA: "zyx|xyz|kubeflow|us-west1-b" # {"$kpt-set":"asm-gcp-metadata"}
    nodeagent:
      env:
        GKE_CLUSTER_URL: "https://container.googleapis.com/v1/projects/xyz/locations/us-west1-b/clusters/kubeflow" # {"$kpt-set":"asm-cluster-url"}
```
**What did you expect to happen:**
no error

**Anything else you would like to add:**
/

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): installation
- kfctl version: (use `kfctl version`): kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`) GKE
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCo
mmit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate
:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/
amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.12
10", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean",
BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platf
orm:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):
