### ISSUE TITLE
AwsIamForServiceAccount plugin is incompatible with apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by alasdairtran** [kubeflow/kubeflow#5812]
In `apiextensions.k8s.io/v1`, object properties with no types are pruned (more info [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema)).

So using the current CustomResourceDefinition for Profile, when I use the `AwsIamForServiceAccount` plugin, the field `awsIamRole` always gets pruned when I create a profile.

Making the type [here](https://github.com/kubeflow/kubeflow/blob/ebc0c4f073397537412694f9f255dbb3fbdf2043/components/profile-controller/config/crd/bases/kubeflow.org_profiles.yaml#L65) more specific, e.g.:

```
plugins:
  items:
      spec:
        properties:
          awsIamRole:
            description: AWS IAM Role
            type: string
```

allows me to annotate the IAM role again.
