### ISSUE TITLE
Logo Trademarks: Remove logos from JWA

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#5821]
/kind bug
### Problem Statement

The new Jupyter Web App comes with logos for Jupyter, VSCode and RStudio. The logos for RStudio and VSCode come with complicated guidelines and need for explicit written legal permission, which is a process the community doesn't have a method of handling from a legal/trademark standpoint. Likely we will need to ask Google to handle this on behalf of the community.
This is a problem for vendors/platforms building their distributions, as they need to be careful what they include. 

### Proposed Solution

For these reasons, we should remove the logos from JWA and use text instead.

cc @kubeflow/wg-notebooks-leads 
cc @bobgy @castrojo @theadactyl

**Comment by DavidSpek** [comment]
I've already been discussing this issue with @Bobgy and am busy with providing a solution for this. I do want to point out that an agreement with RStudio for the use of their logo is being worked on, but that would be for the Kubeflow project and not all the distributions. If a distribution that is just providing manifests that build on the Kubeflow manifests are actually redistributing the logos is questionable in my eyes (but distributions like EKF that are selling the actual distribution would definitely need a licensing agreement with RStudio).

**Comment by yanniszark** [comment]
@DavidSpek @Bobgy thanks for looking into this. If possible, could you or bobgy fill the rest of us in on the plan in this issue? I'd like to make sure we're synced on this.

**Comment by DavidSpek** [comment]
@yanniszark Is it alright if I do this tomorrow? I've been at it for 10 hours without a break again today so I'm pretty tired now and this will be an involved explanation.

**Comment by ReggieCarey** [comment]
Equally problematic is removing attribution for a software product. If the vscode and rstudio logos are part of their distribution, what justification do you have for removing them?  If the software was not written by either company then substitute a kubeflow or other logo and let kf installers customize for their environments.

**Comment by DavidSpek** [comment]
@ReggieCarey My original plan was to make the logos in the UI configurable, and I will try and get that implemented tomorrow. The issue here is that Kubeflow and anybody installing it themselves can most likely use the logos without any problems, but companies offering distributions cannot. The Kubeflow project can have permission to include the logos, but distributions provided by companies will likely need to make their own agreements with the given parties. But I do think that distributions shouldn't restrict agreements the Kubeflow project makes with third parties. It should be made easy for distributions to configure the logos in this case, but I don't think they should be outright removed just because it means the distributions need to put in minimal effort for this.

**Comment by thesuperzapper** [comment]
@ReggieCarey I think its complex (from a legal perspective) [disclaimer: not legal advice], because its unclear if the distributions would be doing anything more than "linking" to the ECR hosted example images, that is, they will not be "distributing" any RStudio binary code.

**Comment by castrojo** [comment]
None of us are lawyers, let's not block 1.3.0 for this and just punt it to a point release, we should just remove it for now until we have a clear understanding on how to proceed, right now our only blockers should be the critical bugfixes that the distributions need -- we're about a month from KubeCon + CloudNativeCon and I'm willing to bet distributions have plans to market/push Kubeflow there, we have blog posts in the queue, and there's still lots of work we're trying to land for docs, etc. 

Let's just put this on the list for 1.3.1/1,4, what do people think?

**Comment by Bobgy** [comment]
Agree with @castrojo.

To add to it, I think our current structure  allows distributions to pick different versions from what's in kubeflow/manifests, because kubeflow/manifests is only reference versions.

So if you release a new version of notebooks, distributions can integrate it individually using their own judgements.

**Comment by DavidSpek** [comment]
@castrojo I think all that is needed to fix this problem is change the manifests and add a configmap with whatever SVG logos you want in there. Then distributions (and users afterwards) are free to configure the UI to show whatever they are allowed and want. I think I can get this sorted in this weekend so it should be on time for the release and we don't need to remove a feature many users were hoping for (for years) and was promised to them.

**Comment by thesuperzapper** [comment]
@Bobgy @yanniszark @DavidSpek the solution is very simple to remove the issue of logos/trademark entirely.

__Steps:__
1. Replace the 3 "image-buttons" with 3 "text-buttons"
    1. Make the default text for each "text-button": "Jupyter", "Group 1", "Group 2"
    1. Use the same name (on hover) in the notebooks overview table
2. Change the spawner_config.yaml structure to:

```yaml
spawnerFormDefaults:
  image:
    name: "Jupyter"
    value: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:master-1831e436
    options:
      - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:master-1831e436
   
  imageGroup1:
    name: "Group 1"
    value: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python:master-1831e436
    options:
      - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python:master-1831e436

  ## SOME DOC TO WARN users that this group adds the a different rewrite-header 
  imageGroup2:
    name: "Group 2"
    value: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse:master-164fa2ea
    options:
      - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse:master-164fa2ea
```

---

This is a very simple change, which I can make a PR for in the next day if we agree.

@Bobgy thoughts?
