### ISSUE TITLE
PodDefault tolerations are not being added to notebook pod

### ISSUE THREAD

**Issue by mygulamali** [kubeflow/kubeflow#5842]
/kind question

**Question:**
[You can ask any question about this project.]
Kubeflow v1.2 introduced the ability to add tolerations to a PodDefault (PR #4852), so that they might be added to a pod running a notebook server. However when I try to do this the tolerations are not added to the notebook pod whilst other aspects of the pod default are.

For example, if I have the following pod default:

```yaml
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: example-selector
  namespace: example-namespace
spec:
  desc: "Example tolerations selector"
  selector:
    matchLabels:
      example-selector: "true"
  env:
  - name: EXAMPLE-ENV-NAME
    value: "example-env-value"
  tolerations:
  - key: "myToleration"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
```

I can choose this pod default in the config section of the Kubeflow Notebooks UI when I create a new notebook server. Then, when I describe the pod that is running the notebook server I see something similar to:

```yaml
Name:         example-0
Namespace:    example-namespace
Priority:     0
Node:         ...
Start Time:   Fri, 16 Apr 2021 15:54:28 +0100
Labels:       app=example
              controller-revision-hash=example-85f68994d4
              example-selector=true
              notebook-name=example
              statefulset=example
              statefulset.kubernetes.io/pod-name=example-0
Annotations:  kubernetes.io/psp: eks.privileged
              poddefault.admission.kubeflow.org/poddefault-example-selector: 240496625
Status:       Running
IP:           ...
IPs:
  IP:           ...
Controlled By:  StatefulSet/example
Init Containers:
  ...
Containers:
  example:
    Container ID:   ...
    Image:          ...
    Image ID:       ...
    Port:           8888/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 16 Apr 2021 15:54:48 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:     500m
      memory:  1Gi
    Environment:
      NB_PREFIX:                    /notebook/example-namespace/example
      EXAMPLE-ENV-NAME:             example-env-value
    Mounts:
      /dev/shm from dshm (rw)
      /home/jovyan from workspace-example (rw)
  istio-proxy:
    Container ID:  ...
    Image:         gcr.io/istio-release/proxyv2:release-1.3-latest-daily
    Image ID:      docker-pullable://gcr.io/istio-release/proxyv2@sha256:de1bcf19d8d709dc6c66aab1d2b9f13f27626b86ab0690a015fb4c72b062eb1d
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      example.$(POD_NAMESPACE)
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15011
      --zipkinAddress
      zipkin.istio-system:9411
      --dnsRefreshRate
      300s
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      MUTUAL_TLS
      --statusPort
      15020
      --applicationPorts
      8888
    State:          Running
      Started:      Fri, 16 Apr 2021 15:54:48 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                          example-0 (v1:metadata.name)
      ISTIO_META_POD_PORTS:              [
                                             {"name":"notebook-port","containerPort":8888,"protocol":"TCP"}
                                         ]
      ISTIO_META_CLUSTER_ID:             Kubernetes
      POD_NAMESPACE:                     example-namespace (v1:metadata.namespace)
      INSTANCE_IP:                        (v1:status.podIP)
      SERVICE_ACCOUNT:                    (v1:spec.serviceAccountName)
      ISTIO_META_POD_NAME:               example-0 (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:       example-namespace (v1:metadata.namespace)
      SDS_ENABLED:                       true
      ISTIO_META_INTERCEPTION_MODE:      REDIRECT
      ISTIO_META_INCLUDE_INBOUND_PORTS:  8888
      ISTIO_METAJSON_ANNOTATIONS:        {"kubernetes.io/psp":"eks.privileged","poddefault.admission.kubeflow.org/poddefault-example-selector":"240496625"}
                                         
      ISTIO_METAJSON_LABELS:             {"app":"example","controller-revision-hash":"example-85f68994d4","example-selector":"true","notebook-name":"example","statefulset":"example","statefulset.kubernetes.io/pod-name":"example-0"}
                                         
      ISTIO_META_WORKLOAD_NAME:          example
      ISTIO_META_OWNER:                  kubernetes://api/apps/v1/namespaces/kubeflow-anonymous/statefulsets/example
    Mounts:
       ...
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  workspace-example:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  workspace-example
    ReadOnly:   false
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
   ...
```

As you can see, the `EXAMPLE-ENV-NAME` environment variable has been added to the pod, but the tolerations have not. Am I doing something wrong?

Some things of note:
* I noticed that the manifest for the PodDefault CRD ([here](https://github.com/kubeflow/manifests/blob/v1.2.0/admission-webhook/webhook/base/crd.yaml)) doesn't contain the `tolerations` property. Could this be an issue?
* Open issue #5825 is a feature request for tolerations and node selectors to be added to PodDefaults, so it seems like other users might be having a similar issue (with respect to adding tolerations, at least).

Thanks in advance!
