### ISSUE TITLE
unable to access kubeflow endpoint | istio ingress has no address assoicated

### ISSUE THREAD

**Issue by ahsan-n** [kubeflow/kubeflow#5879]
/kind question

**Question:**
Hi, so I followed this [document without cognito](https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/) for eks 1.19, after deployed when i ran command: 

`kubectl get ingress -n istio-system` 

i get following output without address: 

```
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME            CLASS    HOSTS   ADDRESS   PORTS   AGE
istio-ingress   <none>   *                 80      22m
```
Now to my understanding there should be elb endpoint but I got nothing, then I updated gateway service directly and replaced node-port with elb but still get no response from server. 

I have eks version 1.19 and kubeflow is 1.2

`kubectl -n istio-system edit service istio-ingressgateway`

```
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: <aws-elb-endpoint>

```

would really appreciate it if i can get some guidance regarding this looking forward to use this awesome project thanks.
