### ISSUE TITLE
Is there a way to add `dnsConfig` to `Notebook` from the UI?

### ISSUE THREAD

**Issue by fahadh4ilyas** [kubeflow/kubeflow#5886]
I want to add `dnsConfig.nameservers[]` field to `Notebook` but I can't using `PodDefault` to do that. Is there a way to add it without patch it manually to `Notebook`? Here is my `PodDefault` yaml file:
```yaml
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: dns-nameserver
  namespace: kubeflow
spec:
 selector:
  matchLabels:
    dns-nameserver: "true"
 desc: "change dns nameserver to 8.8.8.8"
 dnsConfig:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"
```
