### ISSUE TITLE
There is no way to change the session timeout

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/kubeflow#5892]
/kind bug

If you login via dex to the central dashboard, the authservice_session cookie is set with a 24h expiration time.
This is annoying for notebook users where the notebook just errors out after 24h sometimes loosing unsaved work.

SO i went into the dex documentation and increased the tokenid timeout 

in the namespace auth i edit the dex configmap according to the dex documentation
```
...
      http: 0.0.0.0:5556

    #https://github.com/dexidp/dex/blob/81c4dc79945413d93cfc404ffb023e1c399484fe/examples/config-dev.yaml#L75
    #specify units using only s, m and h suffixes 
    expiry:
      idTokens: "168h" # one week

    logger:
...
```
I restarted all pod and cleared all browser caches.

The dex pod in the namespace auth also correctly applies the 168 hours.
```
time="2021-05-07T12:15:49Z" level=info msg="config storage: kubernetes"
time="2021-05-07T12:15:49Z" level=info msg="config static client: Dex Login Application"
time="2021-05-07T12:15:49Z" level=info msg="config connector: local passwords enabled"
time="2021-05-07T12:15:49Z" level=info msg="config skipping approval screen"
time="2021-05-07T12:15:49Z" level=info msg="config id tokens valid for: 168h0m0s"
time="2021-05-07T12:15:49Z" level=info msg="listening (http) on 0.0.0.0:5556"
```

**What did you expect to happen:**

the expiration of the authservice_session cookie should change, but it does not.

**Environment:**

- Kubeflow version: 1.3
- kfctl version: (use `kfctl version`):
- Kubernetes platform: Openshift 4.7
- Kubernetes version: 1.20
