### ISSUE TITLE
AWS configuration with istio Gateway and ALB with Kubeflow 1.3

### ISSUE THREAD

**Issue by EKami** [kubeflow/kubeflow#5949]
/kind question

**Question:**
I'm trying to automatically start an ALB in my EKS cluster by using the [aws-load-balancer-controller](https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller) and by patching Kubeflow 1.3.

This is what the logs of my deployment look like:
```
$ kubectl logs -n kube-system deployment.apps/aws-load-balancer-controller
Found 2 pods, using pod/aws-load-balancer-controller-6d9894cf4-57rlq
{"level":"info","ts":1621805437.8682935,"msg":"version","GitVersion":"v2.2.0","GitCommit":"68c417a7ea37ff153f053d9ffef1cc5c70d7e211","BuildDate":"2021-05-14T21:49:05+0000"}
{"level":"info","ts":1621805441.0391128,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1621805441.042128,"logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":1621805441.042287,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1621805441.0423834,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1621805441.04245,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1621805441.0425208,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1beta1-ingress"}
{"level":"info","ts":1621805441.0435557,"logger":"setup","msg":"starting podInfo repo"}
{"level":"info","ts":1621805443.0431697,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I0523 21:30:43.043172       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/aws-load-balancer-controller-leader...
I0523 21:30:43.061542       1 leaderelection.go:252] successfully acquired lease kube-system/aws-load-balancer-controller-leader
{"level":"info","ts":1621805443.1433892,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":1621805443.1435783,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.1437511,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.143842,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.1441207,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc000090500"}
{"level":"info","ts":1621805443.1442277,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc000090550"}
{"level":"info","ts":1621805443.1447785,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.1448064,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.1448874,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.1447225,"logger":"controller","msg":"Starting EventSource","controller":"service","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.145254,"logger":"controller","msg":"Starting Controller","controller":"service"}
{"level":"info","ts":1621805443.1451356,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1621805443.1455188,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
{"level":"info","ts":1621805443.145757,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
{"level":"info","ts":1621805443.2442284,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.2452686,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc0000905a0"}
{"level":"info","ts":1621805443.2455094,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.2455108,"logger":"controller","msg":"Starting workers","controller":"service","worker count":3}
{"level":"info","ts":1621805443.3447967,"logger":"controller","msg":"Starting Controller","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding"}
{"level":"info","ts":1621805443.3450336,"logger":"controller","msg":"Starting workers","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","worker count":3}
{"level":"info","ts":1621805443.345854,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1621805443.345981,"logger":"controller","msg":"Starting Controller","controller":"ingress"}
{"level":"info","ts":1621805443.346044,"logger":"controller","msg":"Starting workers","controller":"ingress","worker count":3}
```

And the annotations in my kustomize ingress config (I'm patching [Kubeflow 1.3](https://www.kubeflow.org/) config):
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    # create AWS Application LoadBalancer
    kubernetes.io/ingress.class: alb
    # external type
    alb.ingress.kubernetes.io/scheme: internet-facing
    # AWS Certificate Manager certificate's ARN
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-2:1111111:certificate/xxx-xxx-xxx"
    # open ports 80 and 443 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # ExternalDNS settings: https://rtfm.co.ua/en/kubernetes-update-aws-route53-dns-from-an-ingress/
    external-dns.alpha.kubernetes.io/hostname: kubeflow.my-domain.com
    # redirect all HTTP to HTTPS
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```

Here is how I patch the config in `kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- ./manifests-1.3.0/common/cert-manager/cert-manager-kube-system-resources/base
- ./manifests-1.3.0/common/cert-manager/cert-manager-crds/base
- ./manifests-1.3.0/common/cert-manager/cert-manager/overlays/self-signed
# Istio
- ./manifests-1.3.0/common/istio-1-9-0/istio-crds/base
- ./manifests-1.3.0/common/istio-1-9-0/istio-namespace/base
- ./manifests-1.3.0/common/istio-1-9-0/istio-install/base
# OIDC Authservice
- ./manifests-1.3.0/common/oidc-authservice/base
# Dex
- ./manifests-1.3.0/common/dex/overlays/istio
# KNative
- ./manifests-1.3.0/common/knative/knative-serving-crds/base
- ./manifests-1.3.0/common/knative/knative-serving-install/base
- ./manifests-1.3.0/common/knative/knative-eventing-crds/base
- ./manifests-1.3.0/common/knative/knative-eventing-install/base
- ./manifests-1.3.0/common/istio-1-9-0/cluster-local-gateway/base
# Kubeflow namespace
- ./manifests-1.3.0/common/kubeflow-namespace/base
# Kubeflow Roles
- ./manifests-1.3.0/common/kubeflow-roles/base
# Kubeflow Istio Resources
- ./manifests-1.3.0/common/istio-1-9-0/kubeflow-istio-resources/base

# Kubeflow Pipelines
- ./manifests-1.3.0/apps/pipeline/upstream/env/platform-agnostic-multi-user
# KFServing
- ./manifests-1.3.0/apps/kfserving/upstream/overlays/kubeflow
# Katib
- ./manifests-1.3.0/apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ./manifests-1.3.0/apps/centraldashboard/upstream/overlays/istio
# Admission Webhook
- ./manifests-1.3.0/apps/admission-webhook/upstream/overlays/cert-manager
# Notebook Controller
- ./manifests-1.3.0/apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Jupyter Web App
- ./manifests-1.3.0/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ./manifests-1.3.0/apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ./manifests-1.3.0/apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Web App
- ./manifests-1.3.0/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Controller
-  ./manifests-1.3.0/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# TFJob Operator
- ./manifests-1.3.0/apps/tf-training/upstream/overlays/kubeflow
# Pytorch Operator
- ./manifests-1.3.0/apps/pytorch-job/upstream/overlays/kubeflow
# MPI Operator
- ./manifests-1.3.0/apps/mpi-job/upstream/overlays/kubeflow
# MXNet Operator
- ./manifests-1.3.0/apps/mxnet-job/upstream/overlays/kubeflow
# XGBoost Operator
- ./manifests-1.3.0/apps/xgboost-job/upstream/overlays/kubeflow

# User namespace
- ./manifests-1.3.0/common/user-namespace/base

patches:
- target:
    kind: Ingress
    name: istio-ingress
  path: istio/ingress.yaml
```

But so far nothing happens, no alb is being created.

```
$ kubectl get services -n istio-system
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
authservice             ClusterIP   172.20.17.19     <none>        8080/TCP                                                                     39m
cluster-local-gateway   ClusterIP   172.20.0.189     <none>        15020/TCP,80/TCP                                                             39m
istio-ingressgateway    NodePort    172.20.81.219    <none>        15021:31033/TCP,80:31875/TCP,443:31517/TCP,31400:32737/TCP,15443:32018/TCP   39m
istiod                  ClusterIP   172.20.186.197   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                        39m
```

(The NodePort is supposed to be replaced by an ALB here I believe).
I'm out of idea on how to debug this, I guess I'm not patching the right resource? Any help would be greatly appreciated, Thank you.

**Comment by DavidSpek** [comment]
@EKami @karlschriek and I have been working hard on [ArgoFlow-AWS](https://github.com/argoflow/argoflow-aws), which deploys Kubeflow 1.3 using Argo CD and integrates with AWS services such as S3, RDS and SSM. Naturally, everything is open source and we are not trying to sell a product :). We also re-implemented auth so that it is more secure and easier to customize. Of course, the AWS loadbalancer is also configured for it to work properly in AWS. If you have any further questions you can always ping me on Slack or create an issue on the repo.

**Comment by toshi-k** [comment]
@EKami What can you see commanding as below ?
`$ kubectl get ingress -A`

**Comment by DavidSpek** [comment]
Just to clarify, the setup I’ve been using is with an NLB in instance mode. This way TLS is “terminated” by Istio rather than the ingress controller. If you’re using an ALB that terminates TLS and passing it on to the Istio ingressgateway using HTTP that kind of break the idea of a service mesh, and adds another step that complicates the networking chain.

**Comment by DavidSpek** [comment]
With [ArgoFlow-AWS](https://github.com/argoflow/argoflow-aws) we use the Istio operator to instal Istio, and OAuth2-Proxy for the authentication. Here is the isto-spec we use with the operator (which also contains the OAuth2-Proxy setup which you can ignore for now).

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: default
  tag: 1.10.0 # istio/operator
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    enablePrometheusMerge: true
    extensionProviders: 
    - name: "oauth2-proxy"
      envoyExtAuthzHttp:
        service: "oauth2-proxy.auth.svc.cluster.local"
        port: "4180" # The default port used by oauth2-proxy.
        #includeHeadersInCheck: ["authorization", "cookie"]  # headers sent to the oauth2-proxy in the check request.
        includeHeadersInCheck: # headers sent to the oauth2-proxy in the check request.
            # https://github.com/oauth2-proxy/oauth2-proxy/issues/350#issuecomment-576949334
            - "cookie"
            - "x-forwarded-access-token"
            - "x-forwarded-user"
            - "x-forwarded-email"
            - "authorization"
            - "x-forwarded-proto"
            - "proxy-authorization"
            - "user-agent"
            - "x-forwarded-host"
            - "from"
            - "x-forwarded-for"
            - "accept"
        headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token", "x-auth-request-user-groups"] # headers sent to backend application when request is allowed.
        headersToDownstreamOnDeny: ["content-type", "set-cookie"] # headers sent back to the client when request is denied.
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        service:
          type: LoadBalancer
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-name: nlb-my-cluster
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
          proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 2 } }'
          external-dns.alpha.kubernetes.io/hostname: my-cluster.my-domain.com
```

To be able to use the NLB load balancer in instance mode you also need to add these 2 EnvoyFilters:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-settings
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          skip_xff_append: false
          use_remote_address: true
          xff_num_trusted_hops: 1
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
```

You can find all the Istio resources necessary for Kubeflow in [this folder](https://github.com/argoflow/argoflow-aws/tree/master/distribution/istio-resources), which also includes the necessary files to setup monitoring with the `kube-prometheus-stack` helm chart (but this should work with any Prometheus Operator and Grafana deployment. 

If you don't feel like digging through all this yourself, you follow the REAMDE in the [ArgoFlow-AWS](https://github.com/argoflow/argoflow-aws) repository which explains how to install the entire setup. For the Kubeflow components they are installed directly from the upstream manifests of each component which makes upgrading very easy, especially as the repository has been setup to use [Renovate](https://github.com/renovatebot/renovate) to automate the creation of PRs for component manifest updates (as well as most other things in the repository).

**Comment by EKami** [comment]
@toshi-k 
Here is the output:
```
$ kubectl get ingress -A
No resources found
```

@DavidSpek

Thanks, I'll try your solution and let you know :)

**Comment by toshi-k** [comment]
@EKami I think you have to create the ingress object. aws-load-balancer-controller create a loadbalancers based on it.

> The AWS Load Balancer Controller creates an Application Load Balancer when an Ingress object is created using the kubernetes.io/ingress.class: alb annotation. The Ingress resource configures the Application Load Balancer to route HTTP or HTTPS traffic to different pods within your Amazon EKS cluster. You can use AWS WAF to monitor the HTTP or HTTPS requests that are forwarded to the Application Load Balancer.

https://aws.amazon.com/premiumsupport/knowledge-center/eks-alb-ingress-aws-waf/?nc1=h_ls

**Comment by EKami** [comment]
@toshi-k I believe I did by doing this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    # create AWS Application LoadBalancer
    kubernetes.io/ingress.class: alb
    # external type
    alb.ingress.kubernetes.io/scheme: internet-facing
    # AWS Certificate Manager certificate's ARN
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-2:1111111:certificate/xxx-xxx-xxx"
    # open ports 80 and 443 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # ExternalDNS settings: https://rtfm.co.ua/en/kubernetes-update-aws-route53-dns-from-an-ingress/
    external-dns.alpha.kubernetes.io/hostname: kubeflow.my-domain.com
    # redirect all HTTP to HTTPS
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```

or maybe I don't know enough of k8s yet to figure this out :(

**Comment by toshi-k** [comment]
@EKami Is it all of your manifest ? You have to write not only metadata but **specs**.
KF1.2 had an Ingress object itself (but KF 1.3 doesn't have), and you can see it as a reference.
https://github.com/kubeflow/manifests/blob/v1.2-branch/aws/istio-ingress/base/ingress.yaml

**Comment by EKami** [comment]
@toshi-k Oh, I thought KF 1.3 did have one that's why I didn't define the specs since my plan was to overwrite the Ingress object of KF 1.3 with this:
```
patches:
- target:
    kind: Ingress
    name: istio-ingress
  path: istio_custom/ingress.yaml
``` 
with `istio_custom/ingress.yaml`:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    # create AWS Application LoadBalancer
    kubernetes.io/ingress.class: alb
    # external type
    alb.ingress.kubernetes.io/scheme: internet-facing
    # AWS Certificate Manager certificate's ARN
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-2:1111111:certificate/xxx-xxx-xxx"
    # open ports 80 and 443 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # ExternalDNS settings: https://rtfm.co.ua/en/kubernetes-update-aws-route53-dns-from-an-ingress/
    external-dns.alpha.kubernetes.io/hostname: kubeflow.my-domain.com
    # redirect all HTTP to HTTPS
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```

So I will try with this instead:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - istio_custom/ingress.yaml
```

with `istio_custom/ingress.yaml`:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    # create AWS Application LoadBalancer
    kubernetes.io/ingress.class: alb
    # external type
    alb.ingress.kubernetes.io/scheme: internet-facing
    # AWS Certificate Manager certificate's ARN
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-2:1111111:certificate/xxx-xxx-xxx"
    # open ports 80 and 443 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # ExternalDNS settings: https://rtfm.co.ua/en/kubernetes-update-aws-route53-dns-from-an-ingress/
    external-dns.alpha.kubernetes.io/hostname: kubeflow.my-domain.com
    # redirect all HTTP to HTTPS
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /* 
```

and report back. Thanks!

**Comment by toshi-k** [comment]
@EKami Later one seems more reasonable configuration. Good Luck !

**Comment by EKami** [comment]
@toshi-k It's working indeed! With the ALB now being created, thank you so much! I'm getting a 502 bad gateway but I guess I just have to figure out how to fix that in the `specs` now

**Comment by toshi-k** [comment]
@EKami I'm glad to hear that. Make a little more effort !

**Comment by EKami** [comment]
I'll still implement @DavidSpek solution at some point since using an ALB defeats the purpose of istio (I still have to understand why). Thanks for all!

**Comment by EKami** [comment]
@DavidSpek I tried to use your solution but I'm unable to create an NLB, I also tried patching the Istio `Gateway` with:
```
patches:
- target:
    kind: Gateway
    name: istio-ingressgateway
  path: istio_custom/gateway.yaml
```
and `istio_custom/gateway.yaml`:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - kubeflow.domain.com
    port:
      name: http
      number: 80
      protocol: HTTP
    # Upgrade HTTP to HTTPS
    tls:
      httpsRedirect: true
  - hosts:
    - kubeflow.domain.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: kubeflow-ingressgateway-certs
```
but nothing happens, here are the logs that I'm getting from the ingress deployment:
```
$ aws-vault exec pw_research -- kubectl get deployment -n istio-system
Enter passphrase to unlock /home/ekami/.awsvault/keys/:
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
cluster-local-gateway   1/1     1            1           31m
istio-ingressgateway    1/1     1            1           31m
istiod                  1/1     1            1           31m
(base) ✔ ~/workspace/kubeflow-aws [master|✚ 6]
22:42 $ aws-vault exec pw_research -- kubectl logs deployment/istio-ingressgateway -n istio-system
Enter passphrase to unlock /home/ekami/.awsvault/keys/:
2021-06-06T20:12:14.789917Z     info    FLAG: --concurrency="0"
2021-06-06T20:12:14.789949Z     info    FLAG: --domain="istio-system.svc.cluster.local"
2021-06-06T20:12:14.789955Z     info    FLAG: --help="false"
2021-06-06T20:12:14.789959Z     info    FLAG: --log_as_json="false"
2021-06-06T20:12:14.789962Z     info    FLAG: --log_caller=""
2021-06-06T20:12:14.789969Z     info    FLAG: --log_output_level="default:info"
2021-06-06T20:12:14.789972Z     info    FLAG: --log_rotate=""
2021-06-06T20:12:14.789975Z     info    FLAG: --log_rotate_max_age="30"
2021-06-06T20:12:14.789980Z     info    FLAG: --log_rotate_max_backups="1000"
2021-06-06T20:12:14.789984Z     info    FLAG: --log_rotate_max_size="104857600"
2021-06-06T20:12:14.789989Z     info    FLAG: --log_stacktrace_level="default:none"
2021-06-06T20:12:14.790000Z     info    FLAG: --log_target="[stdout]"
2021-06-06T20:12:14.790007Z     info    FLAG: --meshConfig="./etc/istio/config/mesh"
2021-06-06T20:12:14.790011Z     info    FLAG: --outlierLogPath=""
2021-06-06T20:12:14.790015Z     info    FLAG: --proxyComponentLogLevel="misc:error"
2021-06-06T20:12:14.790020Z     info    FLAG: --proxyLogLevel="warning"
2021-06-06T20:12:14.790025Z     info    FLAG: --serviceCluster="istio-ingressgateway"
2021-06-06T20:12:14.790029Z     info    FLAG: --stsPort="0"
2021-06-06T20:12:14.790033Z     info    FLAG: --templateFile=""
2021-06-06T20:12:14.790038Z     info    FLAG: --tokenManagerPlugin="GoogleTokenExchange"
2021-06-06T20:12:14.790051Z     info    Version 1.9.0-b63e1966c245924b10a0915a671a656540ed7a45-Clean
2021-06-06T20:12:14.790283Z     info    Apply mesh config from file accessLogFile: /dev/stdout
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata: {}
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
enablePrometheusMerge: true
rootNamespace: istio-system
trustDomain: cluster.local
2021-06-06T20:12:14.791918Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 0
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
parentShutdownDuration: 60s
proxyAdminPort: 15000
proxyMetadata: {}
serviceCluster: istio-ingressgateway
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411

2021-06-06T20:12:14.791951Z     info    Proxy role      ips=[10.0.1.232] type=router id=istio-ingressgateway-56d9b7fdb-zlwmz.istio-system domain=istio-system.svc.cluster.local
2021-06-06T20:12:14.791959Z     info    JWT policy is third-party-jwt
2021-06-06T20:12:14.791971Z     info    Pilot SAN: [istiod.istio-system.svc]
2021-06-06T20:12:14.791977Z     info    CA Endpoint istiod.istio-system.svc:15012, provider Citadel
2021-06-06T20:12:14.792021Z     info    Using CA istiod.istio-system.svc:15012 cert with certs: var/run/secrets/istio/root-cert.pem
2021-06-06T20:12:14.792153Z     info    citadelclient   Citadel client using custom root cert: istiod.istio-system.svc:15012
2021-06-06T20:12:14.866239Z     info    ads     All caches have been synced up in 77.563638ms, marking server ready
2021-06-06T20:12:14.877543Z     info    sds     SDS server for workload certificates started, listening on "./etc/istio/proxy/SDS"
2021-06-06T20:12:14.877584Z     info    xdsproxy        Initializing with upstream address "istiod.istio-system.svc:15012" and cluster "Kubernetes"
2021-06-06T20:12:14.877881Z     info    Starting proxy agent
2021-06-06T20:12:14.878028Z     info    sds     Start SDS grpc server
2021-06-06T20:12:14.878101Z     info    Opening status port 15020
2021-06-06T20:12:14.879400Z     info    Received new config, creating new Envoy epoch 0
2021-06-06T20:12:14.879456Z     info    Epoch 0 starting
2021-06-06T20:12:14.883685Z     info    Envoy command: [-c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.0.1.232~istio-ingressgateway-56d9b7fdb-zlwmz.istio-system~istio-system.svc.cluster.local --local-address-ip-version v4 --bootstrap-version 3 --log-format %Y-%m-%dT%T.%fZ    %l      envoy %n        %v -l warning --component-log-level misc:error]
2021-06-06T20:12:15.006181Z     warning envoy runtime   Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size
2021-06-06T20:12:15.006234Z     warning envoy runtime   Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size
2021-06-06T20:12:15.006838Z     warning envoy runtime   Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size
2021-06-06T20:12:15.006879Z     warning envoy runtime   Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size
2021-06-06T20:12:15.085488Z     info    cache   Root cert has changed, start rotating root cert
2021-06-06T20:12:15.085518Z     info    ads     XDS: Incremental Pushing:0 ConnectedEndpoints:0 Version:
2021-06-06T20:12:15.085550Z     info    cache   generated new workload certificate      latency=218.848633ms ttl=23h59m59.914460201s
2021-06-06T20:12:15.109514Z     info    xdsproxy        connected to upstream XDS server: istiod.istio-system.svc:15012
2021-06-06T20:12:15.184096Z     info    ads     ADS: new connection for node:router~10.0.1.232~istio-ingressgateway-56d9b7fdb-zlwmz.istio-system~istio-system.svc.cluster.local-1
2021-06-06T20:12:15.184459Z     info    sds     SDS: PUSH       resource=ROOTCA
2021-06-06T20:12:15.187742Z     info    ads     ADS: new connection for node:router~10.0.1.232~istio-ingressgateway-56d9b7fdb-zlwmz.istio-system~istio-system.svc.cluster.local-2
2021-06-06T20:12:15.187844Z     info    cache   returned workload certificate from cache        ttl=23h59m59.812164689s
2021-06-06T20:12:15.187959Z     info    sds     SDS: PUSH       resource=default
2021-06-06T20:12:16.505003Z     info    Initialization took 1.736224566s
2021-06-06T20:12:16.505025Z     info    Envoy proxy is ready
```

I'm a bit lost since I believe `Gateway` is the ingress equivalent for istio but it doesn't seem to spawn any LB.

**Comment by DavidSpek** [comment]
@EKami Is the Istio-ingressgateway service set to loadbalancer instead of ClusterIP or NodePort?

**Comment by EKami** [comment]
Nope, lemme patch that

**Comment by EKami** [comment]
Something like this would work?

`kustomization.yaml`
```
patches:
- target:
    kind: Service
    name: istio-ingressgateway
  path: istio_custom/service.yaml
```
and `istio_custom/service.yaml`:
```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: LoadBalancer
```

I can't find this patching in the repo that you shared
