### ISSUE TITLE
Deploying Kubeflow to Azure with DNS and TLS termination 

### ISSUE THREAD

**Issue by lauradang** [kubeflow/kubeflow#5976]
/kind feature

Similarly to the [documentation regarding deploying Kubeflow to IBM Cloud with DNS and TLS termination](https://www.kubeflow.org/docs/distributions/ibm/deploy/authentication/#exposing-the-kubeflow-dashboard-with-dns-and-tls-termination), it would be great to have similar documentation for deploying Kubeflow to Azure with DNS and TLS termination. Right now, it only shows us how to deploy with a self-signed certificate, which results in a untrusted certificate connection situation. I'm trying to do it myself without knowing much Azure, and it's proven to be quite difficult. 

If anyone has their own solution, I would really appreciate hearing it.

Thanks!

**Comment by DavidSpek** [comment]
I recently ran @pablofiumara through the process of creating a proper certificate on Azure and setting up the Istio Gateway to use that certificate. I haven't had the time yet to write more docs about this, but maybe he can help you out with this a bit.

**Comment by pablofiumara** [comment]
I will post some guidelines in the next days to have SSL enabled on Azure. Meanwhile I suggest reading readme file here and its code: https://github.com/argoflow/argoflow-azure

**Comment by pablofiumara** [comment]
@lauradang Execute this commands

1) 
az group create -n resourcetest3 -l westus
2) 
az aks create -g resourcetest3 -n clustertest3 -s Standard_D4s_v3 -c 4 -l westus --generate-ssh-keys --kubernetes-version 1.19.11
3) 
az aks get-credentials -n clustertest3 -g resourcetest3 --overwrite-existing

4) Buy a domain (not one owned by Azure) and you assign it to resourcetest2. You can do it here (App Service Domains): https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.DomainRegistration%2Fdomains
5) 
Fork https://github.com/argoflow/argoflow-azure
6) 
git clone yourForkUrl (something like this: https://github.com/yourUser/argoflow-azure  )
7) 
cd argoflow-azure/


8) 
AZURE_CERT_MANAGER_SP_NAME=certmanagerserviceprincipalresourcetest3
9) 
AZURE_CERT_MANAGER_DNS_RESOURCE_GROUP=resourcetest3
10) 
AZURE_CERT_MANAGER_DNS_NAME=yourdomain.com
11) 
DNS_SP=$(az ad sp create-for-rbac --name $AZURE_CERT_MANAGER_SP_NAME)
12) 
AZURE_CERT_MANAGER_SP_APP_ID=$(echo $DNS_SP | jq -r '.appId')
13) 
AZURE_CERT_MANAGER_SP_PASSWORD=$(echo $DNS_SP | jq -r '.password')

14) 
az role assignment delete --assignee $AZURE_CERT_MANAGER_SP_APP_ID --role Contributor
15) 
DNS_ID=$(az network dns zone show --name $AZURE_CERT_MANAGER_DNS_NAME --resource-group $AZURE_CERT_MANAGER_DNS_RESOURCE_GROUP --query "id" --output tsv)
16) 
az role assignment create --assignee $AZURE_CERT_MANAGER_SP_APP_ID --role "DNS Zone Contributor" --scope $DNS_ID
17) 
az role assignment list --assignee $AZURE_CERT_MANAGER_SP_APP_ID

18) 
kubectl create namespace cert-manager
19) 
kubectl create secret -n cert-manager generic azuredns-config --from-literal=CLIENT_SECRET=$AZURE_CERT_MANAGER_SP_PASSWORD
20) 
echo "Principal: $AZURE_CERT_MANAGER_SP_APP_ID"    
21) 
echo "Password: $AZURE_CERT_MANAGER_SP_PASSWORD"   

This will create an app here: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps  Reference: https://docs.cert-manager.io/en/release-0.11/tasks/issuers/setup-acme/dns01/azuredns.html



22a) 
vim distribution/cert-manager/lets-encrypt-dns-01/patches/cluster-issuer.yaml

22b) Paste this:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:  
  selfSigned:
    $patch: delete
  acme:
    email: yourEmail@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
          name: gateways-issuer-account-key
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: yourSubscriptionId
          resourceGroupName: resourcetest3
          hostedZoneName: yourdomain.com
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud
          clientID: yourClientIdGetItFromAboveAZURE_CERT_MANAGER_SP_APP_ID
          clientSecretSecretRef:
            name: azuredns-config
            key: CLIENT_SECRET
          tenantID: yourTenantId



```
yourSubscriptionId: Get it from here https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade
tenantId: Enter into your client and copy your tenant id https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps





22c) 
vim examples/setup.conf 

 (suppose your email is user@gmail.com  ) and write the following:

<<__git_repo.url__>>=yourForkUrl
<<__git_repo.target_revision__>>=main
<<__domain__>>=yourdomain.com
<<__subdomain_dashboard__>>=kubeflow
<<__subdomain_serving__>>=serving
<<__subdomain_argocd__>>=argocd
<<__subdomain_auth__>>=auth
<<__subdomain_grafana__>>=grafana
<<__subdomain_kiali__>>=kiali
<<__subdomain_kubecost__>>=kubecost
<<__oidc.issuer__>>=https://auth.my-cluster.my-domain.com
<<__cert_manager.email_user__>>=user
<<__cert_manager.email_domain__>>=gmail.com
<<__cert_manager.server__>>=https://acme-v02.api.letsencrypt.org/directory
<<__cloudflare.email__>>=info@my-domain.com


23) 
vim distribution/kustomization.yaml

Cert manager section should look like this:

```
  # - argocd-applications/cert-manager-self-signing.yaml
   -  argocd-applications/cert-manager-dns-01.yaml

```
24) 
wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/kubeseal-linux-amd64 -O kubeseal

25) 
sudo install -m 755 kubeseal /usr/local/bin/kubeseal
26) 
pip install passlib==1.7.4

27)  Install kustomize 3.2.0. Tutorial: https://kubectl.docs.kubernetes.io/installation/kustomize/source/  

28) 
cd distribution/
 
29)
 ~/go/bin/kustomize build argocd/base/ | kubectl apply -f -

30) 
kubectl apply -f argocd-applications/sealed-secrets.yaml
31)
cd ..
32)
./setup_repo.sh ./examples/setup.conf

When asked a question and you need to answer yes or no, press 2 (no) and then enter

33) 
git add .
34)
git commit -m "installation"
35)
git push -u origin main
36)
kubectl apply -f distribution/kubeflow.yaml

37) 
kubectl get pods --all-namespaces 

After one minute, many pods will appear. Wait until every pod (except kfserving-controller-manager) have Running status

38)
 kubectl get svc -n istio-system istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0]}'

39) Get the ip from previous step, choose your dns zone here: https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Network%2FdnsZones

40) Click on record set

name is kubeflow
Type the ip
Press OK

41) Add a record set for auth and for serving as well (ip is the same)

42) 
vim distribution/oidc-auth/overlays/keycloak/keycloak.yaml

Delete these lines:

      - name: metrics.enabled
        value: "true"
      - name: metrics.serviceMonitor.enabled
        value: "true"
      - name: metrics.serviceMonitor.namespace
        value: monitoring
        
43)  
git add . && git commit -m "deleted metrics" && git push origin main       

44)
kubectl apply -f distribution/oidc-auth/overlays/keycloak/keycloak.yaml


47)

kubectl edit mutatingwebhookconfiguration istio-sidecar-injector -n kubeflow

48) Add this below metadata.annotations:

   admissions.enforcer/disabled: "true"
   
49) Under namespaceSelector.matchExpressions delete lines

    - key: control-plane
      operator: DoesNotExist
      
There are 4 places where you need to delete those lines

50) 

kubectl delete pods --all -n kubeflow

51)
kubectl get pods -n kubeflow

Wait until every pod is on Running state except kfserving-controller-manager



Login to kubeflow.yourdomain
