### ISSUE TITLE
Create link for application in central dashboard for inner cluster service

### ISSUE THREAD

**Issue by danizavtz** [kubeflow/kubeflow#5979]
/kind question
I would like to set a reference in Central Dashboard for a new service (frontend) running in the same cluster of kubeflow.
I was able to customize the central dashboard docker image with a link for my application.
![tempsniphelloapp](https://user-images.githubusercontent.com/3859647/121949683-200fde80-cd2f-11eb-9afa-f340c79b0339.png)

But I couldn't communicate with my application from the central dashboard. 

It gives error 500 and a message: `sorry: /hello-world is not a valid page` 

Here are the steps I followed to produce my results: 

1. Cloned Kubeflow repository from master branch. 
2. Edited `main-page.pug` in kubeflow/components/centraldashboard/public/components/main-page.pg 
    Added code: 

```
a(href$='[[_buildHref("/hello-world", queryParams.*)]]', tabindex='-1')
                paper-item.menu-item#hello-world
                    iron-icon(icon='maps:beenhere')
                    | Hello-world
```
3. Created a hello-world deployment manifest in Kubernetes cluster (namespace Kubeflow same namespace where lives the central dashboard) 
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello-world
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80

```

4. Created a hello-world service for expose my deployment in cluster. (namespace Kubeflow) 

```
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http

```

5. Changed image deployed in centraldashboard service to point to my newly generated docker image (centraldashboard) private container registry and forced a redeployment  from Pod. 

The image above is the error I’m receiving.

I know I'm not serving a web-app, but It is a proof of concept to start integrating our service with kubeflow. In the moment I could not search a good documentation on how to do this.

If necessary I can edit my question to add more information.
**Question:**

Are there a documentation on how to achieve this kind of integration?

**Comment by DavidSpek** [comment]
@danizavtz You will need to expose the service using an Istio VirtualService on the kubeflow Istio Gateway.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world
  namespace: default
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /hello-world
    match:
    - uri:
        prefix: /hello-world/
    rewrite:
      uri: /
    route:
    - destination:
        host: hello-world.default.svc.cluster.local
        port:
          number: 80
```
