### ISSUE TITLE
PodDefault doesn't apply to Pods generated from Deployment 

### ISSUE THREAD

**Issue by SebBlin** [kubeflow/kubeflow#6027]
/kind bug

**What steps did you take and what happened:**
I defined a simple PodDefault that should inject a simple environnement variable:
```
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-env
spec:
 selector:
  matchLabels:
    my-add-env: 'true'
 env:
 - name: "var"
   value: "my-value"
```

When I deploy a pod directly such as this one:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-direct-pod
  labels:
    app: nginx
    my-add-env: 'true'
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
``` 
and the PodDefault is applied correctly

but if I deploy a Pod by using a Deployment object as this one:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    my-add-env: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        my-add-env: 'true'
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
the PodDefault is not applied, whereas the label that should trigger the PodDefault clearly exist in the Pod that is created by the deployement.

**What did you expect to happen:**
The PodDefault should be applied to the pod created by the deployement.

**Environment:**

- Kubeflow version: 1.2 and 1.3
- Kubernetes platform: on-prem kubernetes 
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-r0-CCE20.8.1.3.B001-17.36.5", GitCommit:"d61c11191a704802f93e5d86877a8fcffe208d58", GitTreeState:"clean", BuildDate:"2020-10-16T09:38:58Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
