### ISSUE TITLE
Manually transfer profile ownership

### ISSUE THREAD

**Issue by JessicaBarh** [kubeflow/kubeflow#6054]
/kind question

**Question:**
To manually create a new profile, the following can be used https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#manual-profile-creation. 
However, if I need to transfer ownership of a profile for whatever reason (user no longer working on project, vacation, etc...) is there a way to change ownership to a different user? I was thinking editing the `profile.yaml` to use the new user's email but I'm sure it requires a bit more than that...any ideas?

Thanks :)

**Comment by kd303** [comment]
Is it not possible to add the new user as contributor to that namespace as owner?

**Comment by JessicaBarh** [comment]
Yes but I'm wondering if there's a way to add/modify owner or contributors (as an Admin) on someone else's profile.

**Comment by Sharathmk99** [comment]
Create `rolebinding` in existing namespace

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: admin
    user: <new user id>
  name: namespaceAdmin<new user id>
  namespace: <existing namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: <new user id>
```

This should add `<new user id>` as owner to existing profile/namespace.

Hope this helps.
