### ISSUE TITLE
Issue with Central Dashboard Custom Links

### ISSUE THREAD

**Issue by munagekar** [kubeflow/kubeflow#6118]
/kind bug

Weird Behaviour for custom internal links in kubeflow central dashboard when no namespace is specified.

**What steps did you take and what happened:**

Docker Image for Central dashboard: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.4-rc.0

Links Configuration
```yaml
        {
          "type": "item",
          "link": "/{ns}/mlflow/",
          "text": "MLFlow",
          "icon": "editor:show-chart"
        }
```

Clicked on the MLFlow link in the sidebar with no namespace selected. This opened up another iframe for the centraldashboard within the centraldashboard. 

<img width="1790" alt="Screen Shot 2021-09-02 at 13 57 15" src="https://user-images.githubusercontent.com/10258799/131810829-1dea973b-e385-41fe-bee3-df8621e55a20.png">

**What did you expect to happen:**

CentralDashboard to raise an error, prompt user to select a namespace. 

Note: That that custom link works correctly when the namespace is selected.

**Anything else you would like to add:**

- Feature Issue: https://github.com/kubeflow/kubeflow/issues/5863
- Kubeflow version: 1.3
- CentralDashboard Image: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.4-rc.0 This contains the fix from #5871.

cc: @toshi-k
