### ISSUE TITLE
Admission Webhook Service Name is Wrong in MutatingWebhookConfiguration

### ISSUE THREAD

**Issue by vinayan3** [kubeflow/kubeflow#6221]
In the manifest version 1.3.1 when I render out the kustomize the service name is within the `MutatingWebhookConfiguration` is literally `service`.   This means that Kube is not able to contact the admission webhook to mutate the pod with the defaults. 

This is what I have seen rendered out
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/admission-webhook-cert
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle:  [ SOME VALU]
    service:
      name: service
      namespace: kubeflow
      path: /apply-poddefault
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  name: admission-webhook-deployment.kubeflow.org
  namespaceSelector:
    matchLabels:
      app.kubernetes.io/part-of: kubeflow-profile
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
```

The manifest and it's 
kustomize.yaml doesn't seem to replace the service name: 
https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/manifests/base/mutating-webhook-configuration.yaml#L9

There is the params.yaml https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/manifests/base/params.yaml
