### ISSUE TITLE
KFAM is unprotected and any user can manage all profiles / namespaces of other users.

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/kubeflow#6228]
/kind bug

Kubeflow version: 1.4
KFAM is completely unprotected.

Any user can just start a Jupyterlab and add itself to other namespaces , delete profiles / namespaces and create new ones according to https://github.com/kubeflow/kubeflow/tree/master/components/access-management#apis.
Some examples:
`curl -X POST http://profiles-kfam.kubeflow.svc.cluster.local:8081/kfam/v1/profiles -H 'Content-Type: applica-tion/json' -d '{"metadata":{"name":"dev-exploit"},"spec":{"owner":{"kind":"User","name":"dev-1@kubeflow.org"}}}'`
`curl/wget http://profiles-kfam.kubeflow.svc.cluster.local:8081/kfam/v1/bindings`

With the following change i get the desired 403 errors from inside and outside of the mesh (metacontroller, jupyterlab) Connecting to profiles-kfam.kubeflow.svc.cluster.local:8081 (172.30.217.39:8081) wget: server returned error: HTTP/1.1 403 Forbidden

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: kfam
  namespace: kubeflow
  labels:
    kustomize.component: profiles
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [cluster.local/ns/kubeflow/sa/centraldashboard]
    to:
    - operation:
        methods: ["GET"]
    - operation:
        methods: ["POST"]
    - operation:
        methods: ["DELETE"]
  selector:
    matchLabels:
      kustomize.component: profiles
```

and we need to set sidecar.istio.io/inject: 'true' for profiles-deployment and central-dashboard via overlys:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: centraldashboard
  namespace: kubeflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kustomize.component: profiles
  name: profiles-deployment
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      kustomize.component: profiles
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
```

I can create pull requests for all problems @thesuperzapper @Bobgy 

It is also sensible to add a networpolicy that in general protects the kubeflow namespace. In my instance i even protect the user namespaces with networkpolices.

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: NotIn
        values:
          - minio        # artifact storage
          - ml-pipeline  # pipeline api server
          - poddefaults  # mutating webhook 
          - cache-server # mutating webhook
      - key: component
        operator: NotIn
        values:
          - metadata-grpc-server # metadata server
      - key: katib.kubeflow.org/component
        operator: NotIn
        values:
          - controller # katib mutating webhook to add metrics logger
          - db-manager # the metrics loggers write directly to this database
      - key: control-plane
        operator: NotIn
        values:
          - kfserving-controller-manager # mutating webhook
          - seldon-controller-manager # validating webhook
  ingress:
    - from:
        - namespaceSelector: # istio-system is essential
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - istio-system
        - podSelector: {} # allow all pods from the same namespace
  policyTypes:
    - Ingress
```

kubernetes.io/metadata.name cannot be changed even by cluster-admins. So it is a safe identifier for the istio-system namespace

Another approach would be to use multiple policies:
1. deny all ingress except from istio-system and kubeflow
2. allow profile namespaces (app.kubernetes.io/part-of=kubeflow-profile) to ingress app=minio,ml-pipeline,poddefaults,cache-server and component=metadata-grpc-server

We need to trust the other kubeflow components anyway, so it does not make sense to block profiles-deployment (KFAM) separately.
Anyone controlling its own namespace can add the label app.kubernetes.io/part-of=kubeflow-profile so the two separate rules do not improve security.

I also recommend a profile namespace networkpolicy to the pipelines-profile-controller sync.py

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-non-profile-namespaces
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - kubeflow
                  - istio-system # needed for jupyterlabs
                  - knative-serving # mutating webhooks
                  - knative-eventing # mutating webhook
        - podSelector: {}
  policyTypes:
    - Ingress
```
