### ISSUE TITLE
Notebook culling not working

### ISSUE THREAD

**Issue by d-gol** [kubeflow/kubeflow#6253]
/kind bug

**What steps did you take and what happened:**
Deployed Kubeflow 1.4 from https://github.com/kubeflow/manifests and edited notebook controller deployment to support notebook culling, by adding envs:

```
containers:
- name: manager
  env:
  - name: ENABLE_CULLING
    value: "true"
  - name: IDLE_TIME
    value: "3" # 3 minutes, testing
  - name: CULLING_CHECK_PERIOD
    value: "1"
```

Still, there seems to be an issue accessing the notebooks, and they are not removed. 
Checking logs of the notebook controller

```
kubectl -n kubeflow logs notebook-controller-deployment-POD manager
```

gives:

```
2021-12-17T13:29:44.737Z	INFO	culler	Warning: GET to http://testlab.kubeflow-user-example-com.svc.cluster.local/notebook/kubeflow-user-example-com/testlab/api/status: 403
```

**What did you expect to happen:**
Notebook controller to properly obtain status from the running notebooks, and remove the unused ones.

**Anything else you would like to add:**
This issue was raised in a couple of other comments:
https://github.com/kubeflow/kubeflow/pull/3856#issuecomment-612295807
https://github.com/kubeflow/kubeflow/issues/1394#issuecomment-612295197

Are there any additional steps that I am missing to make this work?

**Environment:**

- Kubeflow version: 1.4
- Kubernetes platform: On-premise cluster
- Kubernetes version: 1.21
- Authentication: Dex
