### ISSUE TITLE
Add user failed to get namespace  on kubeflow 1.4

### ISSUE THREAD

**Issue by 631068264** [kubeflow/kubeflow#6292]
/kind bug

**What steps did you take and what happened:**
admin.yaml
```yaml
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-admin-example-com
spec:
  owner:
    kind: Admin
    name: admin@example.com
---
apiVersion: v1
data:
  profile-name: kubeflow-admin-example-com
  user: admin@example.com
kind: ConfigMap
metadata:
  name: default-install-config-admin
```

apply it
```
kubectl apply -f admin.yaml
```

edit and update dex config-map
```
    staticPasswords:
    - email: user@example.com
      hash: $2y$12$4K/VkmDd1q1Orb3xAt82zu8gk7Ad6ReFR4LCP9UeYE90NLiN9Df72
      # https://github.com/dexidp/dex/pull/1601/commits
      # FIXME: Use hashFromEnv instead
      username: user
      userID: "15841185641784"
    - email: admin@example.com
      hash: $2y$12$uTQwnB7afyNhob.6ETtbdOSTtwvFgqdo9/6yyDi3RZZuk6OqWgsR6
      username: admin
```

restart the pod for dex

I can use new username and password  to login, but can't get any namespace
![image](https://user-images.githubusercontent.com/8144089/149747307-a09aa5af-529c-4058-a0dc-d801b96c797b.png)

**Environment:**

Install follow https://github.com/kubeflow/manifests in v1.4.1
KFP SDK version: build version dev_local
k3s Kubernetes 1.19 v1.19.5+k3s2  (rancher + k3s)
Centos 7
