### ISSUE TITLE
Installing Kubeflow on AWS EKS

### ISSUE THREAD

**Issue by batawfic** [kubeflow/kubeflow#6329]
I had tried so many option without success, my final configuration run kfctl on EC2 following the [instruction](https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/) is:

```
kfctl version
kfctl v1.2.0-0-gbc038f9
```

eks have Kubernetes version 1.21

I tried to change the yaml

from

```
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz
  version: v1.2-branch
```

to

```
repos:
  - name: manifests
    uri: /home/ec2-user/tmp/v1.2.0.tar.gz
  version: v1.2-branch
```

error that keep occurring for ever

```
WARN[0008] Encountered error applying application istio:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout209765219": admission webhook "validation.istio.io" denied the request: configuration is invalid: TLS match must have at least one SNI host  filename="kustomize/kustomize.go:284"
WARN[0008] Will retry in 5 seconds.                      filename="kustomize/kustomize.go:285"
```

until final error is:

```
ERRO[0610] Permanently failed applying application istio:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout568084052": admission webhook "validation.istio.io" denied the request: configuration is invalid: TLS match must have at least one SNI host  filename="kustomize/kustomize.go:288"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout568084052": admission webhook "validation.istio.io" denied the request: configuration is invalid: TLS match must have at least one SNI host
```

Any suggestion is much appreciated
