### ISSUE TITLE
"Encountered error applying application cert-manager" for AWS and kubeflow manifest v1.2

### ISSUE THREAD

**Issue by cgebbe** [kubeflow/kubeflow#6375]
/kind question

**What steps did you take and what happened:**
Follow https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/#configure-kubeflow to setup Kubeflow on AWS:

### Successfully created EKS cluster

using `eksctl` and the following configuration file

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-kubeflow
  version: "1.18"
  region: eu-central-1

managedNodeGroups:
- name: kubeflow-mng
  desiredCapacity: 3
  instanceType: t2.micro
```

### Install kubeflow 

- Use manifest https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws.v1.2.0.yaml.
- `kfctl apply -V -f kfctl_aws.yaml` yields the following error

```
WARN[0028] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout834892597": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:284"
WARN[0028] Will retry in 13 seconds.                     filename="kustomize/kustomize.go:285"
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`): kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`): AWS
- Kubernetes version: (use `kubectl version`): v1.23.4
- OS (e.g. from `/etc/os-release`): Linux Mint 19 Tara
- aws-cli/1.18.69 Python/3.6.9 Linux/4.15.0-124-generic botocore/1.16.19
- eksctl version 0.84.0
- aws-iam-authenticator version v0.5.0

**Next steps**

Will look at 
- https://github.com/kubeflow/kubeflow/issues/4762
- https://github.com/cert-manager/cert-manager/issues/2640#issuecomment-601872165
