### ISSUE TITLE
Integration with Kubeflow's PodDefault (or PodPreset) doesn't seem to work with CSI driver in AWS

### ISSUE THREAD

**Issue by anskanwe** [kubeflow/kubeflow#6539]
/kind bug

**What steps did you take and what happened:**
Installed the CSI driver in AWS EKS.

https://aws.amazon.com/blogs/security/how-to-use-aws-secrets-configuration-provider-with-kubernetes-secrets-store-csi-driver/

After that when I am manually spinning up a pod it is working fine as shown in the above documentation.

But when I am using the pod defaults for the notebooks it is behaving abruptly 

This is the pod default yaml for the reference.

```
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: aws-secret
  namespace: cd-msr
spec:
  desc: "aws-secret"
  selector:
    matchLabels:
      aws-secret: "true"
  serviceAccountName: default-editor
  volumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets"
    readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: secrets-provider
```

**What did you expect to happen:**

After creating pod defaults with CSI driver I should be able to access the secret inside my notebook, but getting a empty directory 

**Anything else you would like to add:**

This is what we found in the descriptions for the pod which was created manually.
Mounts:
      /mnt/secrets from secrets-store-inline (ro)
Volumes:
secrets-store-inline:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:            
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=secrets-provider

Getting this when using pod defaults in notebook.
Mounts:
      /met/secrets from secrets-store-inline (ro)
secrets-store-inline:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>

Found the reference links for the same issue.

https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/239
https://github.com/kubeflow/pipelines/issues/4325

**Environment:**

- Kubeflow version:1.4
- Kubernetes platform: EKS 1.21
- Kubernetes version: (use `kubectl version`):1.24.1
