### ISSUE TITLE
Notebook's annotations are not included

### ISSUE THREAD

**Issue by youngMan4** [kubeflow/kubeflow#6677]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1. create a notebook.yaml
```yaml
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: notebook-sample-v1
  annotations:
    notebooks.kubeflow.org/server-type: "foo"
spec:
  template:
    spec:
      containers:
        - name: notebook-sample-v1
          image: kubeflownotebookswg/jupyter:v1.6.0-rc.0

```

2. kubectl create -f notebook.yaml

3. The annotation of pod is none, `notebooks.kubeflow.org/server-type: "foo"` is not included.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/116160255/196847250-a46c0569-8d6e-4879-bcf7-f52374e59d19.png">

**What did you expect to happen:**
I expect that the annotation of `notebooks.kubeflow.org/server-type: "foo"`  to be included.

like this :
<img width="919" alt="image" src="https://user-images.githubusercontent.com/116160255/196849366-8ff26440-ebe1-476a-a87e-ffd6515c5be9.png">

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The generateStatefulSet func doesn't copy all the Notebook annotations to the pod now.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform:  minikube
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
