### ISSUE TITLE
Unable to get kubeflow working on hyperkube in a circleci vm

### ISSUE THREAD

**Issue by s1113950** [kubeflow/kubeflow#674]
Status of pods:

```
root@bfdfa013445c:/usr/share/mlt# kubectl get pods -n kubeflow
NAME                                READY     STATUS             RESTARTS   AGE
ambassador-7789cddc5d-75hwb         1/2       CrashLoopBackOff   8          19m
ambassador-7789cddc5d-b5xfq         1/2       CrashLoopBackOff   8          19m
ambassador-7789cddc5d-j9jmw         1/2       CrashLoopBackOff   8          19m
tf-hub-0                            1/1       Running            0          19m
tf-job-dashboard-8699ccb5ff-lflzb   0/1       CrashLoopBackOff   8          19m
tf-job-operator-646bdbcb7-kjwc8     0/1       CrashLoopBackOff   8          19m
```

Error in the tf-job-operator docker container:

```
circleci@default-d8db7b56-d2e6-40a6-b8ce-7d0a243b5273:~$ docker logs k8s_tf-job-operator_tf-job-operator-646bdbcb7-kjwc8_kubeflow_fc4b46aa-4280-11e8-85c6-0242ac120008_8
{"filename":"app/server.go:60","level":"info","msg":"KUBEFLOW_NAMESPACE not set, using default namespace","time":"2018-04-17T21:07:56Z"}
{"filename":"app/server.go:65","level":"info","msg":"[Version: 0.3.0+git Git SHA: a7511ff Go Version: go1.9.2 Go OS/Arch: linux/amd64]","time":"2018-04-17T21:07:56Z"}
{"filename":"tf-operator/main.go:46","level":"fatal","msg":"open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or **directory\n","time":"2018-04-17T21:07:56Z"}
```

So I went to check out what's going on with serviceaccount tokens:

```
root@bfdfa013445c:/usr/share/mlt# kubectl get secrets -n kubeflow
NAME                           TYPE                                  DATA      AGE
ambassador-token-k2jrg         kubernetes.io/service-account-token   3         20m
default-token-2bmxq            kubernetes.io/service-account-token   3         20m
jupyter-hub-token-l6tpq        kubernetes.io/service-account-token   3         20m
tf-job-dashboard-token-n5t2d   kubernetes.io/service-account-token   3         20m
tf-job-operator-token-lv7fr    kubernetes.io/service-account-token   3         20m
```
And they are all there, so I `describe`d the tf-operator:

```
Mounts:
      /etc/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from tf-job-operator-token-lv7fr (ro)

Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      tf-job-operator-config
    Optional:  false
  tf-job-operator-token-lv7fr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tf-job-operator-token-lv7fr
    Optional:    false
```
It is supposedly being mounted there.

Events from the tf-operator:
```
Events:
  Type     Reason                 Age                From                Message
  ----     ------                 ----               ----                -------
  Normal   Scheduled              23m                default-scheduler   Successfully assigned tf-job-operator-646bdbcb7-kjwc8 to 127.0.0.1
  Normal   SuccessfulMountVolume  23m                kubelet, 127.0.0.1  MountVolume.SetUp succeeded for volume "config-volume"
  Normal   SuccessfulMountVolume  23m                kubelet, 127.0.0.1  MountVolume.SetUp succeeded for volume "tf-job-operator-token-lv7fr"
  Normal   Pulling                23m                kubelet, 127.0.0.1  pulling image "gcr.io/kubeflow-images-staging/tf_operator:v20180329-a7511ff"
  Normal   Pulled                 22m                kubelet, 127.0.0.1  Successfully pulled image "gcr.io/kubeflow-images-staging/tf_operator:v20180329-a7511ff"
  Normal   Created                21m (x4 over 22m)  kubelet, 127.0.0.1  Created container
  Normal   Pulled                 21m (x3 over 22m)  kubelet, 127.0.0.1  Container image "gcr.io/kubeflow-images-staging/tf_operator:v20180329-a7511ff" already present on machine
  Normal   Started                21m (x4 over 22m)  kubelet, 127.0.0.1  Started container
  Warning  BackOff                21m (x5 over 22m)  kubelet, 127.0.0.1  Back-off restarting failed container
  Warning  FailedSync             3m (x86 over 22m)  kubelet, 127.0.0.1  Error syncing pod
```

I checked what was in ` /var/run/secrets/kubernetes.io/serviceaccount` and there's nothing there, which means the token isn't being mounted for some reason.

My hyperkube setup:

```
version: "2"

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.2"
    command: "etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379"
    ports:
      - 2379:2379

  kubernetes:
    image: "gcr.io/google-containers/hyperkube-amd64:v1.8.5"
    depends_on:
      - "etcd"
    privileged: true
    command: "/hyperkube apiserver --insecure-bind-address=0.0.0.0 --etcd-servers=http://etcd:2379 --service-cluster-ip-range=10.0.0.0/16 --storage-backend=etcd2
--storage-media-type=application/json --admission-control=NamespaceLifecycle,NamespaceExists,ServiceAccount,LimitRanger,ResourceQuota"
    ports:
      - 8080:8080
    volumes:
      - /var/run/kubernetes:/var/run/kubernetes:rw

  kubelet:
    image: gcr.io/google_containers/hyperkube-amd64:v1.8.5
    ports:
      - 8080
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./resources:/resources:rw
      - /var/lib/docker:/var/lib/docker:rw
      - /var/lib/kubelet:/var/lib/kubelet:rw
    command: "/hyperkube kubelet --hostname-override=127.0.0.1 --enable-server --kubeconfig=/resources/config.yaml --v=2 --fail-swap-on=false --cluster-dns=10.0.0.1 --cluster-domain=cluster.local --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice"

  proxy:
    image: gcr.io/google_containers/hyperkube-amd64:v1.8.5
    pid: host
    privileged: true
    command: "/hyperkube proxy --master=http://kubernetes:8080 --v=2 --conntrack-max=0 --conntrack-max-per-core=0"

  controller-manager:
    image: gcr.io/google_containers/hyperkube-amd64:v1.8.5
    pid: host
    volumes:
      - /var/run/kubernetes:/var/run/kubernetes:rw
    command: "/hyperkube controller-manager --master=http://kubernetes:8080 --v=2 --service-account-private-key-file=/var/run/kubernetes/apiserver.key --root-ca-file=/var/run/kubernetes/apiserver.crt"

  scheduler:
    image: gcr.io/google_containers/hyperkube-amd64:v1.8.5
    pid: host
    command: "/hyperkube scheduler --master=http://kubernetes:8080 --v=2"

  registry:
    image: "registry:2"
    ports:
      - 5000:5000

  test:
    image: "mlt"
    depends_on:
      - "kubernetes"
      - "registry"
    environment:
      - KUBECONFIG=/usr/share/mlt/resources/config.yaml
    command: "sleep inf"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

I can get pytorch and other jobs to run on this cluster.

My PR where I'm making these hyperkube changes: https://github.com/IntelAI/mlt/pull/146

Any help would be appreciated! From the internet it seems there can be a ton of different reasons as to why a servicetoken won't be mounted properly :(
