### ISSUE TITLE
Error in retry strategy timing

### ISSUE THREAD

**Issue by LaurenzReitsam** [kubeflow/kubeflow#6870]
I am not sure if this is a Kubeflow, Argo, or Vertex AI bug. Hope this is correct here.

**What steps did you take and what happened:**

When I set the retry strategy as follows, the retry is executed after `60s` instead of `1 hour` as defined.

```python
@kfp.v2.dsl.component
def foo() -> None:
    raise RuntimeError("foo")

@ kfp.v2.dsl.pipeline(name="foo")
def pipeline():
    foo().set_retry(num_retries=3, backoff_duration="1 hour", backoff_factor=1)

``` 

![Screenshot 2023-01-04 113106](https://user-images.githubusercontent.com/51755866/210536383-8125b610-0975-4325-8fc3-3c0444887d9b.png)

The DSL is correctly compiled into the ``pipeline.json`` file:
```yaml
...
"retryPolicy": {
    "backoffDuration": "3600s",
    "backoffFactor": 1.0,
    "backoffMaxDuration": "3600s",
    "maxRetryCount": 3.0
},
...
```

**What did you expect to happen:**
Expected the first retry to be executed after 1 hour (`=backoff_duration`), not after 1 minute

**Environment:**

- Google Cloud - Vertex AI (europe-west1)
