### ISSUE TITLE
Controllers should always set a status

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6999]
/kind feature

We started looking into this with @elenzio9 and @apo-ger while trying to improve the UX of the Notebooks web app where is always shows a spinner, even if there's a problem and a notebook will never become ready. The web app should try and at least have a ⚠️ icon, so users are not confused on whether something has gone wrong or if the image is getting pulled.

This created the question of how should a client (web app in this case) know what happens with a K8s object. IMO the answer to that is; the `.status` of an object should always reflect what is going on with the K8s object (CR or native object)

The problem right now is that there are cases where the controller might still end up with having no information at all, and result in an "empty" status like:
```yaml
status:
  replicas: 0
  conditions: []
  containerState: {}
```

Let's use this issue to coordinate the effort for better improving how we are exposing errors in both our CRDs (notebooks, tensorboards etc) and also how to extend the web apps in a uniform way. A first step for this is https://github.com/kubeflow/kubeflow/pull/6952

cc @orfeas-k @elenzio9 @apo-ger

**Comment by kimwnasptd** [comment]
The problematic scenario that can result with no status is the following yaml:
```yaml
apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: serviceaccountnotexist
  namespace: kubeflow-user
spec:
  template:
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: serviceAccountnotexist
          resources:
            requests:
              cpu: 10m
              memory: 1Mi
      serviceAccountName: test  # this SA doesn't exist!
status:
  conditions: []
  containerState: {}
  readyReplicas: 0
```
In this case though the Notebook has an event that exposes what is going on:
``` Warning  FailedCreate  49m   notebook-controller  Reissued from statefulset/serviceaccountnotexist: create Pod serviceaccountnotexist-0 in StatefulSet serviceaccountnotexist failed error: pods "serviceaccountnotexist-0" is forbidden: error looking up service account kubeflow-user/test: serviceaccount "test" not found```

But there are some problems with this:
1. Events will get deleted after some time
2. The `.status` is not helpful at all

We'll need to extend the Notebook Controller to always try and expose in the status what the issue is
cc @apo-ger
