### ISSUE TITLE
Kubeflow Notebooks 2.0 (Kubeflow Workspaces)

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#7156]
/kind feature

Here is my proposal for Kubeflow Notebooks 2.0, which can be called "Kubeflow Workspaces".

My main idea has always been to make the Notebook CRD not just a wrapper around PodSpec, with the goal of abstracting away the Kubernetes resources from end users, while also giving cluster admins the ability to define a set of "templates" which end users can choose from.

__The high-level overview is to split the Notebook CRD into these two CRDs:__

- `Workspace` (namespaced resource)
  - this is the resource that end-users create via the "Workspace Spawner UI" or `kubectl`
  - it is NOT a wrapper around PodSpec
- `WorkspaceKind` (cluster resource)
  - this is the resource that cluster-admins create
  - it specifies the template for a Workspace (e.g. "JupyterLab", "VSCode", "RStudio")
  - initially, we would only support a "podTemplate" kind, which is very similar to the existing Notebook CRD,
    but in the future, we could support other types of templates (e.g. "helmTemplate")

__The main benefits of this approach are:__

- end-users can create Workspaces without needing to know anything about Kubernetes, because the UI literally becomes 3 dropdowns:
   - Choose a WorkspaceKind (e.g. "jupyter-lab", "vs-code", "rstudio")
   - Choose an image from the approved list
   - Choose a pod-config (e.g. "small_cpu", "big_gpu")
   - Create/Mount a home volume (optional)
   - Create/Mount data volumes (optional)
- cluster-admins can update the definitions of WorkspaceKinds without breaking existing Workspaces:
  - they simply add a new image/pod-config option, and redirect the old one to the new one
  - we can even provide a config to make the controller wait for a Workspace to restart before applying the redirect
    (we can also make the Spawner UI display a warning that the Workspace needs to be restarted to get the new config)
- scheduling Pods with GPU resources often requires a number of Pod configs to be correctly aligned (e.g. tolerating a taint, and setting a resource limit), collecting all these configs into a single pod-config allows cluster-admins to provide drop-down options, rather than requiring users to understand the structure of their Kubernetes cluster.

### Workspace (namespaced resource)

Here is an example `Workspace`, which uses the `WorkspaceKind/jupyter-lab` that we define later:

```yaml
apiVersion: kubeflow.org/v1
kind: Workspace
metadata:
  name: my-notebook
  namespace: my-namespace
spec:
  ## if the workspace is running
  paused: false

  ## the WorkspaceKind to use
  kind: juptyer-lab

  ## options for "podTemplate"-type WorkspaceKind
  podTemplateOptions:
    image: "jupyter_scipy_171"
    podConfig: "big_gpu"
    homeVolume: "my-home-pvc"
    dataVolumes:
      - name: my-data-pvc
        mountPath: /data/my-data
```

### WorkspaceKind (cluster resource)

Here is an example `WorkspaceKind`, which allows users to run JupyterLab Notebooks in Pods:

```yaml
apiVersion: kubeflow.org/v1
kind: WorkspaceKind
metadata:
  name: jupyter-lab
spec:
  ## configs for how this WorkspaceKind should be displayed in the Workspace Spawner UI
  spawner:
    name: "JupyterLab Notebook"
    description: "A Workspace which runs JupyterLab in a Pod"
    hidden: false

    ## in the future, we might also support specifying a ConfigMap (or CRD) which contains the UI config
    ## (this would require us to make the spawner automatically serve the logo file)
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Jupyter_logo.svg"

  ## configs for a "podTemplate"-type WorkspaceKind (very similar to the existing Notebooks)
  ##  - in future we may want to support other types of Workspace templates (e.g. "helmTemplate")
  podTemplate:
    
    ## configs which are specific to this kind of template
    configs:
      httpRewritePath: "/"
      httpRStudioHeader: false
      httpPort: 8888

      homePath: "/home/jovyan"

    ## options which are set in each Workspace instance (and exposed in the Workspace Spawner UI)
    options:

      ## "image" options
      ##  - sets the container images which can be chosen for the Pod
      image:
        default: "jupyter_scipy_171"

        ## the allowed values for this option
        ##  - to prevent breaking existing Workspaces, values can NOT be removed, but can be hidden or redirected
        values:
          - id: "jupyter_scipy_170"
            spawner:
              displayName: "jupyter-scipy:v1.7.0"
              hidden: true
            spec:
              image: "docker.io/kubeflownotebookswg/jupyter-scipy:v1.7.0"

            ## the "redirect" field can be used to redirect from one value to another
            ##  - if "redirect.waitForRestart" is true, the controller waits for the Workspace to restart before applying the redirect
            ##    (in this case, the Spawner UI will display a warning that the Workspace needs to be restarted)
            redirect:
              to: "jupyter_scipy_171"
              waitForRestart: true

          - id: "jupyter_scipy_171"
            spawner:
              displayName: "jupyter-scipy:v1.7.1"
            spec:
              image: "docker.io/kubeflownotebookswg/jupyter-scipy:v1.7.1"
      
        ## "podConfig" options
        ##  - sets options for Pod configs other than image/volume 
        ##    (e.g. resource requests, node selectors, tolerations, affinity)
        podConfig:
          default: "small_cpu"

          ## the allowed values for this option
          ##  - to prevent breaking existing Workspaces, values can NOT be removed, but can be hidden or redirected
          values:
            - id: "small_cpu"
              spawner:
                displayName: "Small CPU"
              spec:
                affinity: {}
                nodeSelector: {}
                resources:
                  requests:
                    cpu: 1
                    memory: 2Gi
                tolerations: []

            - id: "big_gpu"
              spawner:
                displayName: "Big GPU"
              spec:
                affinity: {}
                nodeSelector: {}
                resources:
                  requests:
                    cpu: 4
                    memory: 16Gi
                  limits:
                    nvidia.com/gpu: 1
                tolerations:
                  - key: "nvidia.com/gpu"
                    operator: "Exists"
                    effect: "NoSchedule"
```
