### ISSUE TITLE
I have Error 403 - authorisation issues when trying to use azure OIDC on kubeflow

### ISSUE THREAD

**Issue by nelson2000** [kubeflow/kubeflow#7196]
/kind bug

**What steps did you take and what happened:**

I am setting up kubeflow to have my authentication and authorization through azure active directory and completely avoid dex
I have edited the oidc-authservice-parameters config map as follows;
```
############################
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-authservice-parameters
  namespace: istio-system
data:
  AUTHSERVICE_URL_PREFIX: https://<my domain>/authservice/
  OIDC_REDIRECT_URI: https://<my domain>/authservice/oidc/callback
  OIDC_AUTH_URL: https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize
  OIDC_PROVIDER: https://login.microsoftonline.com/<tenant-id>/v2.0
  OIDC_SCOPES: profile email
  STORE_PATH: /var/lib/authservice/data.db
  SKIP_AUTH_URLS: ""
  CLIENT_ID: <client_id>
  APPLICATION_SECRET: <client secret>
  USERID_CLAIM: email
  USERID_HEADER: kubeflow-userid
  USERID_PREFIX: ""

#########################

this is my dex config map, though i dont actaully need it as i am completely going through AAD for OIDC

apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: auth
data:
  config.yaml: |
    issuer: https://login.microsoftonline.com/cf5bcce4-b29c-4270-abd3-c4a0a9005c45/v2.0
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    staticClients:
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
    connectors:
    - type: microsoft
      id: microsoft
      name: Microsoft
      config:
        clientID: <client id>
        clientSecret: <client secret>
        redirectURI: https://<my domain>/authservice/oidc/callback
        scopes:
        - profile
        - email
 ```
On azure, i have registered an app and set the redirect_uri to https://<my domain name>/authservice/oidc/callback and given a api permission of openid, email and profile, user.read(default). 

when i go to <my-domain>.com it takes me to microsoft login page, i log in successfully but after the login session i get a 403 error page

```



****ERROR 403****
![microsoft1](https://github.com/kubeflow/kubeflow/assets/20236706/1aad3754-3254-4f94-9eba-a0b0ba5c35d4)

```

**What did you expect to happen:**

To take me to kubeflow front page

![microsoft2](https://github.com/kubeflow/kubeflow/assets/20236706/959d6478-814b-43b7-85c8-d8d282f82724)

**Anything else you would like to add:**

Please who has been able to do this successfully, i need help, i have been debugging this for days now with no result.

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

I am running kubeflow on AKS and my domain name is secured with https.

- Kubeflow version: 1.7v
- Kubernetes platform:  AKS
- Kubernetes version:  1.27
- OS (e.g. from `/etc/os-release`):
