### ISSUE TITLE
CentralDashBoard with openLDAP log in cannot log out

### ISSUE THREAD

**Issue by korjwl1** [kubeflow/kubeflow#7221]
I am using kubeflow build version dev_local on RKE1(v1.25.11).
I recently configured the kubeflow with openldap login, and want to try log out but it does not yield anything.
The only way of using other ID is to use the inprivate browser...

https://github.com/kubeflow/kubeflow/assets/72062804/5868fce0-f9c1-4cb0-9428-675203a39e53

Such a log comes out from the istio

```
2023-07-25T07:38:51.887140Z	info	xdsproxy	connected to upstream XDS server: istiod.istio-system.svc:15012
[2023-07-25T07:42:39.508Z] "POST /logout HTTP/1.1" 404 - via_upstream - "-" 0 146 2 1 "10.42.1.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "02e327aa-fd20-9901-bc1c-0c905cfd77b0" "211.171.108.146:30617" "10.42.0.143:8082" outbound|80||centraldashboard.kubeflow.svc.cluster.local 10.42.0.253:54428 10.42.0.253:8080 10.42.1.0:31263 - -
```

The dex-configmap file I used is like below

```
issuer: http://dex.auth.svc.cluster.local:5556/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
staticClients:
- idEnv: OIDC_CLIENT_ID
  redirectURIs: ["/authservice/oidc/callback"]
  name: 'Dex Login Application'
  secretEnv: OIDC_CLIENT_SECRET
connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    host: <my own ldap host>
    insecureNoSSL: true
    bindDN: <DN>
    bindPW: <PWD>
    usernamePrompt: LDAP Username
    userSearch:
      baseDN: <DN>
      filter: "(objectClass=inetOrgPerson)"
      username: uid
      idAttr: uid
      emailAttr: mail
      nameAttr: cn
    groupSearch:
      baseDN: <DN>
      filter: "(objectClass=posixGroup)"
      userMatchers:
      - userAttr: dn
        groupAttr: memberUid
      nameAttr: cn
```

All I changed is to use http instead of https by editing the params in jupyter and volume, and also changed the param in centraldashboard in order to let ldap users to make own namespaces

I am not sure why the log out button is not working at all... Does anybody know how to handle it?

**Comment by subasathees** [comment]
Issue with external auth, logout is calling /logout, ideally it should be /authservice/logout . try to apply below proxy redirect by creating virtual service. This is route all /logout to /authservice/logout .

File: authservice-logout.yaml

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authservice-logout
  namespace: istio-system
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /logout
      rewrite:
        uri: /authservice/logout
      route:
        - destination:
            host: authservice.istio-system.svc.cluster.local
            port:
              number: 8080
```
