### ISSUE TITLE
How to access models via Kubeflow and Istio and hosted on a Triton Server

### ISSUE THREAD

**Issue by hasnainkothawala** [kubeflow/kubeflow#7235]
/kind question

**Question:**
Hi Team , 
I am trying to host multiple models using Kubeflow , the models are hosted on Triton server. However I am facing issues while trying to access the models via API.

Background 
Kubeflow has been successfully installed and accessible via browser. The models seem to be running properly  and I have tested them by port forwarding the pods. 

I am hoping to scale the models (triton server pods) as the traffic increases however I am getting below error while trying to access the model via Istio Ingress Gateway.

Can someone help me here ?

Files attached , 

![image](https://github.com/kubeflow/kubeflow/assets/46241927/e106febe-8e05-407d-8263-b09d632c1585)
 
**Below is the deployment file**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "bert-v4"
  annotations:
    autoscaling.knative.dev/target: "3"
spec:
  predictor:
    volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    serviceAccountName: sa
    triton:
      runtimeVersion: 21.09-py3
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      resources:
        limits:
          cpu: "4"
          memory: 14Gi
        requests:
          cpu: "1"
          memory: 4Gi
      storageUri: "s3://ppai-seldon-models/vision-and-language"
```
**Below is the script I use for Inferencing , this works just fine when I deploy a model with predictor type as `tensorflow`**
```
import requests
import os
import json
import concurrent.futures
import requests

CLUSTER_IP = os.environ.get("CLUSTER_IP", "localhost:8080")
DASHBOARD_URL = f"http://{CLUSTER_IP}"
NAMESPACE = "kubeflow-user-example-com"
MODEL_NAME = "bert-v4"
SERVICE_HOSTNAME = "bert-v4.kubeflow-user-example-com.example.com"
URL = f"http://{CLUSTER_IP}/v2/models/bert-v4/infer"
HEADERS = {"Host": "bert-v4.kubeflow-user-example-com.example.com", "Content-Type": "application/json"}
USERNAME = os.environ.get("USERNAME", "user@example.com")
PASSWORD = os.environ.get("PASSWORD", "12341234")

num_requests = 1
response = None
text = "Hello World"
e_text = str(text.encode('utf-8').strip())

data = json.dumps({
    "inputs": [
        {
            "name": "TEXT",
            "shape": [1, 1],
            "datatype": "BYTES",
            "data": [e_text]
        }
    ]
})


def session_cookie(host, login, password):
    session = requests.Session()
    response = session.get(host)
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
    }
    data = {"login": login, "password": password}
    session.post(response.url, headers=headers, data=data)
    session_cookie = session.cookies.get_dict()["authservice_session"]
    return session_cookie


cookie = {"authservice_session": session_cookie(DASHBOARD_URL, USERNAME, PASSWORD)}
print(f'{cookie=}')
print("Sending request to:", URL)
print(f"{SERVICE_HOSTNAME=}")

for i in range(num_requests):
    response = requests.post(URL, headers=HEADERS, json=data, cookies=cookie)
    status_code = response.status_code
    print("Status Code", status_code)
    print(response.content)
    print(response.__dict__)
```
[triton-server-logs.txt](https://github.com/kubeflow/kubeflow/files/12334819/triton-server-logs.txt)
