### ISSUE TITLE
Can I exclude some paths(or apps) from dex authorization?

### ISSUE THREAD

**Issue by igikorea-kajoong-yoon** [kubeflow/kubeflow#7249]
I've created a cluster following the guide at [KUBEFLOW ON AWS](https://awslabs.github.io/kubeflow-manifests/docs/).

I think I changed not so much from the document so my cluster must be very simple.

I found that any access via `istio-ingressgateway` is checked whether it has JWT or not for authorization. There's no problem for using kubeflow, notebook and sort of apps deployed as default.

The problem is, I've deployed another app like ArgoCD and exposed it using istio's `VirtualService` and then I cannot login ArgoCD with CLI.

Some says I can exclude some route from authorization using `EnvoyFilter` but I couldn't make any valid setup.

Can I get any help or hint? 😢
Belows are my cluster's data.

## Gateways
```
apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    labels:
      release: istio
    name: cluster-local-gateway
    namespace: istio-system
  spec:
    selector:
      app: cluster-local-gateway
      istio: cluster-local-gateway
    servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    labels:
      release: istio
    name: istio-ingressgateway
    namespace: istio-system
  spec:
    selector:
      app: istio-ingressgateway
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    labels:
      app.kubernetes.io/component: net-istio
      app.kubernetes.io/name: knative-serving
      app.kubernetes.io/version: 1.8.0
      networking.knative.dev/ingress-provider: istio
    name: knative-local-gateway
    namespace: knative-serving
  spec:
    selector:
      app: cluster-local-gateway
      istio: cluster-local-gateway
    servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 8081
        protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    name: kubeflow-gateway
    namespace: kubeflow
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
kind: List
metadata:
  resourceVersion: ""
```

## VirtualServices
```
apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    labels:
      app: argocd-server
    name: argocd-virtualservice
    namespace: argocd
  spec:
    gateways:
    - kubeflow/kubeflow-gateway
    hosts:
    - '*'
    http:
    - match:
      - uri:
          prefix: /argocd
      route:
      - destination:
          host: argocd-server
          port:
            number: 80
```

## EnvoyFilters
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          http_service:
            authorization_request:
              allowed_headers:
                patterns:
                - exact: authorization
                - exact: cookie
                - exact: x-auth-token
            authorization_response:
              allowed_upstream_headers:
                patterns:
                - exact: kubeflow-userid
            server_uri:
              cluster: outbound|8080||authservice.istio-system.svc.cluster.local
              timeout: 10s
              uri: http://authservice.istio-system.svc.cluster.local
  workloadSelector:
    labels:
      istio: ingressgateway
```

## EnvoyFilters (not worked)
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bypass-auth
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      routeConfiguration:
        vhost:
          name: kubeflow.some.domain.com:443
    patch:
        operation: MERGE
        value:
          per_filter_config:
            envoy.ext_authz:
              disabled: true
```

**Comment by juliusvonkohout** [comment]
/close

Please check your oidc-authservice configuration

**Comment by pashtet04** [comment]
I want to publish some services via Istio in the Kubeflow Kubernetes cluster, for example, `prometheus.mydomain.examle.com` or `mlflow.mydomain.examle.com`. While my kubeflow central dashboard is available by `mydomain.examle.com`

I created my own Gateway and VirtualService for each endpoint, and also added an exception for authentication via oidc-authservice to the Envoy Filter `authn-filter`

Now, everything seems to be working, but if you go to one of the URLs, then the next one will not open. In short, if you use a private tab, the first URL requested is always opened. Why and how to fix it?

```yaml
---
# https://github.com/adeo/dp--deploy-kubeflow/blob/v1.7-branch/common/oidc-authservice/base/envoy-filter.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: metrics
  namespace: metrics
spec:
  gateways:
  - metrics-gateway
  hosts:
  - 'prometheus.mydomain.examle.com'
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: prometheus-kube-prometheus-prometheus.metrics.svc.cluster.local
        port:
          number: 9090
```

```yaml
---
# https://github.com/adeo/dp--deploy-kubeflow/blob/v1.7-branch/common/oidc-authservice/base/envoy-filter.yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: metrics-gateway
  namespace: metrics
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'prometheus.mydomain.examle.com'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: tls
      mode: SIMPLE
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    # https://github.com/adeo/dp--deploy-prometheus/blob/master/helm/values/istio-kubeflow-resources
    - applyTo: VIRTUAL_HOST
      match:
        routeConfiguration:
          vhost:
            name: mlflow.ml.data.lmru.tech:443
      patch:
          operation: MERGE
          value:
            typed_per_filter_config:
              envoy.filters.http.ext_authz:
                '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                disabled: true
    # https://github.com/adeo/dp--deploy-prometheus/blob/master/helm/values/istio-kubeflow-resources
    - applyTo: VIRTUAL_HOST
      match:
        routeConfiguration:
          vhost:
            name: prometheus.mydomain.examle.com:443
      patch:
          operation: MERGE
          value:
            typed_per_filter_config:
              envoy.filters.http.ext_authz:
                '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                disabled: true
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        # For some reason, INSERT_FIRST doesn't work
        operation: INSERT_BEFORE
        value:
          # See: https://www.envoyproxy.io/docs/envoy/v1.17.0/configuration/http/http_filters/ext_authz_filter#config-http-filters-ext-authz
          name: "envoy.filters.http.ext_authz"
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              server_uri:
                uri: http://$(AUTHSERVICE_SERVICE).$(AUTHSERVICE_NAMESPACE).svc.cluster.local
                cluster: outbound|8080||$(AUTHSERVICE_SERVICE).$(AUTHSERVICE_NAMESPACE).svc.cluster.local
                timeout: 10s
              authorization_request:
                allowed_headers:
                  patterns:
                    # XXX: MUST be lowercase!
                    - exact: "authorization"
                    - exact: "cookie"
                    - exact: "x-auth-token"
              authorization_response:
                allowed_upstream_headers:
                  patterns:
                    - exact: "kubeflow-userid"

```
