### ISSUE TITLE
Profile controller creates ResourceQuotas, but not modifying values after creation

### ISSUE THREAD

**Issue by subasathees** [kubeflow/kubeflow#7258]
/kind bug

**What steps did you take and what happened:**
1. Create ResourceQuota 1st time - working fine
```
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: ss-test-eot-lab2
spec:
  owner:
    kind: User
    name: sathees@msds.example.com
  resourceQuotaSpec:
    hard:
      nvidia.com/gpu: "1"
      cpu: "5"
      memory: 1Gi
      requests.storage: 10Gi
```
2. Modify the ResourceQuota values -> KF Profile updating using kubectl but it's not updating ResourceQuota in respective namespace
* Modify the memory limit from 1Gi to 2Gi, this is not getting reflected on namespace resource
* Or add new Quota if not added earlier , it's not showing anything on the namespace Quota
```
      memory: 2Gi
```
kubectl describe ns ss-test-eot-lab2
```
kubectl describe ns ss-test-eot-lab3
Name:         ss-test-eot-lab2
Labels:       app.kubernetes.io/part-of=kubeflow-profile
              istio-injection=enabled
              katib.kubeflow.org/metrics-collector-injection=enabled
              kubernetes.io/metadata.name=ss-test-eot-lab2
              pipelines.kubeflow.org/enabled=true
              serving.kubeflow.org/inferenceservice=enabled
Annotations:  owner: sathees@msds.example.com
Status:       Active

Resource Quotas
  Name:           kf-resource-quota
  Resource        Used  Hard
  --------        ---   ---
  nvidia.com/gpu  0     0
```

**What did you expect to happen:**
1. Create ResourceQuota 1st time - working fine
2. Modify the ResourceQuota values -> should work and profile quota should auto sync with namespace level ResourceQuota

**Anything else you would like to add:**
NA

**Environment:**

- Kubeflow version: 1.7.0
- kfctl version: (use `kfctl version`): v1.0.2-0-ga476281
- Kubernetes platform:  On-prem
- Kubernetes version: 1.23.5
- OS (e.g. from `/etc/os-release`): RHEL7.9
