### ISSUE TITLE
Deny pip install on kubeflow notebook

### ISSUE THREAD

**Issue by subasathees** [kubeflow/kubeflow#7271]
/kind feature

**Why you need this feature:**
Kubeflow notebook users are installing pip packages after the launch their notebook server, this is creating security issues in our environment. we would like to restrict this activity. 

**Describe the solution you'd like:**
"pip install" should not download any package. need to block the default pip repo server url traffic in pod, i.e https://pypi.org/simple
This should be on selective Profiles only.

**Anything else you would like to add:**
we can blocked the "https://pypi.org/" traffic by creating below network rules, but this is out of kubeflow control.
kindly share any way to block the pip install command to avoid external URL access from kubeflow.

Network policy:
pip_deny_out.yaml
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: ss-test-eot
spec:
  podSelector:
    matchExpressions:
      - key: notebook-name
        operator: Exists
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 151.101.0.223/32
      ports:
        - protocol: TCP
          port: 443
```

**Versions:**
Kubeflow: v1.7.0
Kubernetes: v1.23.5
