### ISSUE TITLE
Use Pod Preset to add environment variables and volume mounts to pods

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#732]
We have a number of cases where we need to add volume mounts and environment variables to pods;
e.g.
  - #564 add secrets/credentials
 - Set volume mounts for GPU devices.

We currently do this by using jsonnet to add appropriate environment variables and volume amounts.

I think a better approach would be to create an admission controller.

It would be nice if this admission controller was easily customizable so we could have a single controller that could be configured to add different environment variables and volume mounts to pods matching certain criteria.

Maybe something already exists if not maybe we could write one.

/cc @wbuchwalter 
/cc @elsonrodriguez

**Comment by elsonrodriguez** [comment]
If we're sticking to env vars and volumes, the existing Podpresets admission controller would be the way to go.

**Comment by jlewi** [comment]
This seems like the way to go. I think we should do the following

- Define pod presets for various clouds
- Selectively enable those pod presets based on "cloud" or other values
- Use a consistent set of labels on Kubeflow pods so that pod presets are applied

**Comment by ankushagarwal** [comment]
Did some initial research. It is not clear to me whether GKE supports `PodPreset` admission controller.

**Comment by ankushagarwal** [comment]
According to https://kubernetes.io/docs/admin/admission-controllers/, the PodPreset admission controller is not a recommended admission controller - maybe that's why it's not available in GKE right now. Should be re-address this once PodPreset is available in GKE?

**Comment by jlewi** [comment]
Is this just a matter of PodPreset's being Alpha see [here](https://kubernetes.io/docs/concepts/workloads/pods/podpreset/).

Would we just need to create an Alpha cluster to use PodPresets?

**Comment by ankushagarwal** [comment]
Here is an example pod preset which injects service account credentials into a pod:

Create the service account, get its credentials and store it as a secret

```
SERVICE_ACCOUNT=kubeflow-gcp-service-account
PROJECT=kubeflow-example-project
gcloud iam service-accounts --project=${PROJECT} create ${SERVICE_ACCOUNT} \
  --display-name "GCP Service Account for use with kubeflow"

KEY_FILE=${HOME}/secrets/${SERVICE_ACCOUNT}@${PROJECT}.iam.gserviceaccount.com.json
gcloud iam service-accounts keys create ${KEY_FILE} \
  --iam-account ${SERVICE_ACCOUNT}@${PROJECT}.iam.gserviceaccount.com

kubectl create secret generic kubeflow-gcp-service-account-credentials --from-file=kubeflow-service-acount.json="${KEY_FILE}"
```

Create a PodPreset to

* Create env GOOGLE_APPLICATION_CREDENTIALS : /secrets/gcp-service-account-credentials/kubeflow-service-acount.json
* Create a volume referring to the secret
* Create a volume mount for the secret volume


```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: inject-kubeflow-gcp-service-account
spec:
  selector:
    matchLabels:
      gcp_service_account: kubeflow-gcp-service-account
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secrets/gcp-service-account-credentials/kubeflow-service-acount.json
  volumeMounts:
    - mountPath: /secrets/gcp-service-account-credentials
      readOnly: true
      name: kubeflow-gcp-service-account-credentials
  volumes:
    - name: kubeflow-gcp-service-account-credentials
      secret:
         secretName: kubeflow-gcp-service-account-credentials
```

> Note : Although not explicitly mentioned in the docs, PodPreset seems to be a Namespace-scoped object rather than a Cluster Scoped Object
