### ISSUE TITLE
The MAX memory shows  1288490188800m

### ISSUE THREAD

**Issue by Alansyf** [kubeflow/kubeflow#7369]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Create a notebook from scratch, everything leave as default. 

<img width="694" alt="image" src="https://github.com/kubeflow/kubeflow/assets/34836936/9467d471-4c57-4b3c-99cb-24cc6deb0eb7">

When created, it showed 
<img width="700" alt="image" src="https://github.com/kubeflow/kubeflow/assets/34836936/d848bba9-f28b-4185-bc23-22652144fd17">

And even get notebook yaml in runtime, it showed

    ```
    resources:
          limits:
            cpu: 600m
            memory: 1288490188800m
          requests:
            cpu: 500m
            memory: 1Gi
```

**What did you expect to happen:**
It should set Max RAM properly. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.7
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`): Openstack
- Kubernetes version: (use `kubectl version`): v1.25.10
- OS (e.g. from `/etc/os-release`):
