### ISSUE TITLE
Question about tensorboard

### ISSUE THREAD

**Issue by 453875726** [kubeflow/kubeflow#7409]
I use tensorboard of kubeflow dashboard to check logs about mnist-cnn training process which is saved in PV. I name the tensorboard "mnist-cnn". However, after I clicked the 'create' button, the tensorboard is still unavailible after a few hours. Therefore, I check the event of 'mnist-cnn'. 
```
user@ubuntu:~/manifests$ kubectl get events -n mynamespace | grep "mnist-cnn"
53m         Warning   FailedCreate   replicaset/mnist-cnn-6bdd8cfc8   Error creating: pods "mnist-cnn-6bdd8cfc8-kxvsr" is forbidden: failed quota: kf-resource-quota: must specify cpu,memory
36m         Warning   FailedCreate   replicaset/mnist-cnn-6bdd8cfc8   Error creating: pods "mnist-cnn-6bdd8cfc8-7zpqx" is forbidden: failed quota: kf-resource-quota: must specify cpu,memory
20m         Warning   FailedCreate   replicaset/mnist-cnn-6bdd8cfc8   Error creating: pods "mnist-cnn-6bdd8cfc8-kch64" is forbidden: failed quota: kf-resource-quota: must specify cpu,memory
3m23s       Warning   FailedCreate   replicaset/mnist-cnn-6bdd8cfc8   Error creating: pods "mnist-cnn-6bdd8cfc8-vbsr7" is forbidden: failed quota: kf-resource-quota: must specify cpu,memory
```
I wonder why the cpu,memory of tensorboard needs to be set, I think it should have been given a default set after the kubeflow is installed. If it needs to be set, can it be set with kubectl command, not by .yaml file?

**Comment by inesBam** [comment]
I get the same error. Did you find a solution to this yet ?

**Comment by 453875726** [comment]
> I get the same error. Did you find a solution to this yet ?

1. Yes, it has been solved, at first I used a yaml file to create my own profile as followed. 

```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: mynamespace   # replace with the name of profile you want, this will be user's namespace name
spec:
  owner:
    kind: User
    name: mynamespace@email.com   # replace with the email of the user
  resourceQuotaSpec:
   hard:
     cpu: "10"
     memory: "16Gi"  
     requests.nvidia.com/gpu: "6"
     persistentvolumeclaims: "10" 
     requests.storage: "100Gi" 
```

2. Then I switch to the default user 'kubeflow-user-example-com', the default user can create tensorboard . Therefore I think maybe I should checked the difference between the profile 'mynamespace ' I created and the default profile 'kubeflow-user-example-com'. As expected, I found the default profile 'kubeflow-user-example-com' didn't specify resourceQuotaSpec including cpu, memory, gpu, pv, etc. 

Run kubectl get profile, the output is as follow:
```
NAME                        AGE
kubeflow-user-example-com   23d
mynamespace                 75s
```

kubectl describe profile mynamespace
```
Name:         mynamespace
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  kubeflow.org/v1
Kind:         Profile
Metadata:
  Creation Timestamp:  2023-11-30T00:52:57Z
  Finalizers:
    profile-finalizer
  Generation:  1
  Managed Fields:
    API Version:  kubeflow.org/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:owner:
          .:
          f:kind:
          f:name:
          f:resourceQuotaSpec:
          .:
          f:hard:
            .:
            f:cpu:
            f:memory:
            f:persistentvolumeclaims:
            f:requests.nvidia.com/gpu:
            f:requests.storage:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-11-30T00:52:57Z
    API Version:  kubeflow.org/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"profile-finalizer":
    Manager:         manager
    Operation:       Update
    Time:            2023-11-30T00:52:57Z
  Resource Version:  43531120
  UID:               36ec349b-7975-4307-bf4d-72a2efdf89d5
Spec:
  Owner:
    Kind:  User
    Name:  mynamespace@email.com
  Resource Quota Spec:
    Hard:
      Cpu:                      10
      Memory:                   16Gi
      Persistentvolumeclaims:   10
      requests.nvidia.com/gpu:  6
      requests.storage:         100Gi
Events:                         <none>
```

kubectl describe profile kubeflow-user-example-com
```
Name:         kubeflow-user-example-com
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  kubeflow.org/v1
Kind:         Profile
Metadata:
  Creation Timestamp:  2023-11-06T07:42:03Z
  Finalizers:
    profile-finalizer
  Generation:  2
  Managed Fields:
    API Version:  kubeflow.org/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:owner:
          .:
          f:kind:
          f:name:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-11-06T07:42:03Z
    API Version:  kubeflow.org/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"profile-finalizer":
      f:spec:
        f:resourceQuotaSpec:
    Manager:         manager
    Operation:       Update
    Time:            2023-11-06T08:13:30Z
  Resource Version:  16133
  UID:               22717d90-8db1-4149-a80f-1ba736dfce22
Spec:
  Owner:
    Kind:  User
    Name:  user@example.com
  Resource Quota Spec:
Events:  <none>
```
3. Therefore, I edited my profile.yaml.
My yaml is as follow, I have commented out the lines that specify resource quota
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: mynamespace   # replace with the name of profile you want, this will be user's namespace name
spec:
  owner:
    kind: User
    name: mynamespace@email.com   # replace with the email of the user
  # resourceQuotaSpec:
  #  hard:
  #    cpu: "10"
  #    memory: "16Gi"  
  #    requests.nvidia.com/gpu: "6"
  #    persistentvolumeclaims: "10" 
  #    requests.storage: "100Gi" 
```
You can use kubectl describe your namespace to check the details.
4. Then I apply the edited yaml profile as followed, the tensorboard works. I don't know why, but this solution works for me. I hope it helps.
```
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: mynamespace   # replace with the name of profile you want, this will be user's namespace name
spec:
  owner:
    kind: User
    name: mynamespace@email.com   # replace with the email of the user
  # resourceQuotaSpec:
  #  hard:
  #    cpu: "10"
  #    memory: "16Gi"  
  #    requests.nvidia.com/gpu: "6"
  #    persistentvolumeclaims: "10" 
  #    requests.storage: "100Gi" 
     

```
