### ISSUE TITLE
How to do container mount like '-v /path/a:/path:b' in kubeflow yaml component?

### ISSUE THREAD

**Issue by stevezkw1998** [kubeflow/kubeflow#7522]
component.yaml
```yaml
name: op_a
description: op_a

inputs:
  - { name: a, type: String }
  - { name: b, type: String }

implementation:
  container:
    image: xxx.com/op_a:latest
    command:
     .....

      - { inputValue: a }
      - { inputValue: b }
```
I want to do `-v /path/a:/path:b` as docker container can do in this kubeflow component
How can I conduct that?

**Comment by AbhijithGanesh** [comment]
Heyy @stevezkw1998 . To mount a volume in a notebook you can follow this:
```yaml
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: add-gcp-secret
  namespace: MY_PROFILE_NAMESPACE
spec:
 selector:
  matchLabels:
    add-gcp-secret: "true"
 desc: "add gcp credential"
 volumeMounts:
 - name: secret-volume
   mountPath: /secret/gcp
 volumes:
 - name: secret-volume
   secret:
    secretName: gcp-secret
```


https://www.kubeflow.org/docs/components/notebooks/quickstart-guide/
