### ISSUE TITLE
How to disable Multi User Isolation/ Remove Manage Contributors from UI

### ISSUE THREAD

**Issue by brianmoran** [kubeflow/kubeflow#7565]
/kind question

**Question:**

I have a specific need to completely disable Multi-User Isolation, preventing users from sharing notebooks. Is it possible to remove the Manage Contributors section from the UI, similar to the customizing the UI via a ConfigMap?

![Screenshot 2024-04-26 at 10 13 08 AM](https://github.com/kubeflow/kubeflow/assets/5261397/03595e94-637e-4a50-a5bb-f435c5fecd74)

**Comment by brianmoran** [comment]
In the interim, I added an `AuthorizationPolicy` to deny the `add-contributor` and `remove-contributor` paths. Still would be nice to have a feature flag to disable Multi User Isolation.

**Comment by thesuperzapper** [comment]
@brianmoran for now, adding that authorization policy is the best approach because it also prevents people doing it with the KFAM API calls directly (even if the UI prevented it).

Do you want to share your AuthorizationPolicy resource YAML?

**Comment by brianmoran** [comment]
@thesuperzapper here's the `AuthorizationPolicy`. 

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: central-dashboard-deny-manage-users
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: centraldashboard
  action: DENY
  rules:
  - to:
    - operation:
        paths:
          - "/api/workgroup/add-contributor/*"
          - "/api/workgroup/remove-contributor/*"
```

Not a great UX but our users know they are restricted from sharing.
