### ISSUE TITLE
How can I login to the dashboard as a cluster admin

### ISSUE THREAD

**Issue by Shimada666** [kubeflow/kubeflow#7600]
/kind question

**Question:**
[You can ask any question about this project.]

 I have installed Kubeflow 1.8.1 on the cluster, modified the email and name in dex's configmap, and successfully logged in. However, in `manage contributors` tab, I am only an owner, not a cluster admin. How can I login to the dashboard as a cluster admin? I expect to see the following content:
<img width="1356" alt="image" src="https://github.com/kubeflow/kubeflow/assets/33391300/b2c195ce-96d8-4a79-9ad1-e0dedf4fea1a">

This is mine:
<img width="1163" alt="image" src="https://github.com/kubeflow/kubeflow/assets/33391300/d879210a-ee12-44b3-8817-1db4abc9e9cc">

#4998 
I have tried that but it does not work:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
subjects:
- kind: User
  name: 649940882@qq.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
