### ISSUE TITLE
Dex Microsoft connector gives me "Unregistered redirect_uri ("/oauth2/callback")."

### ISSUE THREAD

**Issue by JCoupalK** [kubeflow/kubeflow#7609]
/kind question

**What steps did you take and what happened:**
I configured the Dex config-map.yaml to use the Microsoft connector following those instructions:
https://dexidp.io/docs/connectors/microsoft/

Applied and restarted the deployments.

And when I clicked Login with Microsoft I got this:
![image](https://github.com/kubeflow/kubeflow/assets/108779415/fd5912c1-ccb6-43a2-ad6e-c206ea37a464)

I tried to modify the config but anything I tried seemed to result in this Bad request.

Not sure if that's purely a Dex issue or the way it is in Kubeflow.

**What did you expect to happen:**

To be able to login with my Microsoft Azure AD account and access the dashboard.

**Anything else you would like to add:**
My current (censored) config-maps.yaml at ./manifests/common/dex/base/config-map.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/authservice/oidc/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
    connectors:
      - type: microsoft
        id: microsoft
        name: Microsoft
        config:
          clientID: client-id-here
          clientSecret: secret-here
          redirectURI: https://external.domain.com/dex/callback
          tenant: organizations
          emailToLowercase: true
```
My (censored) Azure app:
![image](https://github.com/kubeflow/kubeflow/assets/108779415/9deb7ce7-4b29-45ac-8bc8-5bbf7cfbd0b5)
![image](https://github.com/kubeflow/kubeflow/assets/108779415/2221c31d-181b-4bfe-8cf5-d406be55bfc7)
![image](https://github.com/kubeflow/kubeflow/assets/108779415/713510a4-612c-47e3-b772-2d700f1f521c)

**Environment:**

- Kubeflow version: 1.8.0
- Kubernetes platform: K3S
- Kubernetes version: 1.26.15
- OS: Ubuntu 22.04 LTS
- The istio gateway is also behind an external nginx reverse proxy
