### ISSUE TITLE
SparkApplication + volcano scheduler do not take into account batchSchedulerOptions.queue specification

### ISSUE THREAD

**Issue by danc** [kubeflow/kubeflow#7683]
Hi, as described on https://www.kubeflow.org/docs/components/spark-operator/user-guide/volcano-integration/
I'm trying to use volcano queues when submitting SparkApplications.
This works, but the `default`volcano queue is always used, despite the batchSchedulerOptions.queue of the yaml, as this one : 

```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  #generateName: spark-pi-
  namespace: default
spec:
  imagePullSecrets:
    - acr-auth
  type: Scala
  mode: cluster
  image: our.repo/spark:volcano-latest
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.13-3.4.1.jar
  sparkVersion: 3.4.1
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: 1200m
    memory: 512m
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: 512m
  batchScheduler: "volcano" 
  batchSchedulerOptions:
    queue: "test"
```

Note that I've rebuilt the spark distribution with the `-Pvolcano` option and can successfully use volcano queues via the classic `spark-submit` method , using

```
        --conf spark.kubernetes.scheduler.name=volcano \
        --conf spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
        --conf spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
        --conf spark.kubernetes.authenticate.driver.serviceAccountName=$K8S_SERVICE_ACCOUNT_NAME \
        --conf spark.kubernetes.scheduler.volcano.podGroupTemplateFile=$PODGROUP_TEMPLATE \
```
So I suspect that 

```
  batchSchedulerOptions:
    queue: "test"
```
is not working properly.
Currently playing with latest spark-operator and volcano version

```
helm -n spark-operator list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS     CHART                   APP VERSION
spark-operator  spark-operator  1               2025-02-14 14:47:06.528579 +0100 CET    deployed   spark-operator-2.1.0    2.1.0    

helm -n volcano-system list 
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
volcano volcano-system  1               2025-02-14 14:46:16.986659 +0100 CET    deployed        volcano-1.11.0  1.11.0   
```

Thanks for your thoughts,

 [Some more details on volcano github](https://github.com/volcano-sh/volcano/issues/4006)
